ingredients_mappings = {
    "aioli": "aioli",
    "alfredo sauce": "alfredo sauce",
    "almond": "almond",
    "almond extract": "almond extract",
    "aluminum foil": "aluminum foil",
    "amaretto": "amaretto",
    "angel food cake": "angel food cake",
    "apple": "apple",
    "apple cider": "apple cider",
    "apple cider vinegar": "apple cider vinegar",
    "apple juice": "apple juice",
    "applesauce": "apple sauce",
    "apricot": "apricot",
    "artichoke": "artichoke",
    "artichoke heart": "artichoke heart",
    "arugula": "arugula",
    "asiago cheese": "asiago cheese",
    "asparagus": "asparagus",
    "avocado": "avocado",
    "baby spinach": "baby spinach",
    "bacon": "bacon",
    "baguette": "baguette",
    "baked bean": "baked bean",
    "baking powder": "baking powder",
    "baking sheet": "baking sheet",
    "baking soda": "baking soda",
    "balsamic vinegar": "balsamic vinegar",
    "bamboo skewer": "bamboo skewer",
    "banana": "banana",
    "barbecue sauce": "barbecue sauce",
    "barley": "barley",
    "basil": "basil",
    "basmati rice": "basmati rice",
    "bay leaf": "bay leaf",
    "bean": "bean",
    "bean sprout": "bean sprout",
    "beef": "beef",
    "beef broth": "beef broth",
    "beef stock": "beef stock",
    "beer": "beer",
    "beet": "beet",
    "beetroot": "beet",
    "bell pepper": "bell pepper",
    "berry": "berry",
    "biscuit": "biscuit",
    "black bean": "black bean",
    "black olive": "black olive",
    "black pepper": "black pepper",
    "blue cheese": "blue cheese",
    "blueberry": "blueberry",
    "boiling water": "boiling water",
    "bourbon": "bourbon",
    "brandy": "brandy",
    "bread": "bread",
    "bread bowl": "bread bowl",
    "breadcrumb": "breadcrumb",
    "breadstick": "breadstick",
    "brine": "brine",
    "broccoli": "broccoli",
    "broth": "broth",
    "brown rice": "brown rice",
    "brown sugar": "brown sugar",
    "brownie": "brownie",
    "bun": "bun",
    "butter": "butter",
    "buttermilk": "buttermilk",
    "butternut squash": "butternut squash",
    "butterscotch chip": "butterscotch chip",
    "cabbage": "cabbage",
    "cake": "cake",
    "cake flour": "cake flour",
    "canola oil": "canola oil",
    "caper": "caper",
    "capsicum": "capsicum",
    "caramel": "caramel",
    "caramel sauce": "caramel sauce",
    "caraway seed": "caraway seed",
    "cardamom": "cardamom",
    "carrot": "carrot",
    "cashew": "cashew",
    "caster sugar": "caster sugar",
    "catsup": "catsup",
    "cauliflower": "cauliflower",
    "cayenne": "cayenne",
    "celery": "celery",
    "champagne": "champagne",
    "cheddar": "cheddar",
    "cheese": "cheese",
    "cheese sauce": "cheese sauce",
    "cheese slice": "cheese slice",
    "cheesecake": "cheesecake",
    "cheesecloth": "cheesecloth",
    "cherry": "cherry",
    "cherry tomato": "cherry tomato",
    "chicken": "chicken",
    "chicken breast": "chicken breast",
    "chicken broth": "chicken broth",
    "chicken stock": "chicken stock",
    "chicken tender": "chicken tender",
    "chicken thigh": "chicken thigh",
    "chicken wing": "chicken wing",
    "chickpea": "chickpea",
    "chile": "chili",
    "chili": "chili",
    "chili sauce": "chili sauce",
    "chilie": "chilie",
    "chip": "chip",
    "chive": "chive",
    "chocolate": "chocolate",
    "chocolate chip": "chocolate chip",
    "chocolate curl": "chocolate curl",
    "chocolate shaving": "chocolate shaving",
    "chocolate syrup": "chocolate syrup",
    "chopped tomato": "chopped tomato",
    "chow mein noodle": "chow mein noodle",
    "chutney": "chutney",
    "cider": "cider",
    "cider vinegar": "cider vinegar",
    "cilantro": "cilantro",
    "cinnamon": "cinnamon",
    "cinnamon stick": "cinnamon stick",
    "cinnamon sugar": "cinnamon sugar",
    "clams": "clams",
    "clove": "clove",
    "club soda": "club soda",
    "coarse salt": "coarse salt",
    "cocoa": "cocoa",
    "coconut": "coconut",
    "coconut milk": "coconut milk",
    "coconut oil": "coconut oil",
    "cod": "cod",
    "coffee": "coffee",
    "cognac": "cognac",
    "cold water": "cold water",
    "coleslaw": "coleslaw",
    "condensed milk": "condensed milk",
    "confectioner sugar": "confectioner sugar",
    "cooked bacon": "cooked bacon",
    "cooked chicken": "cooked chicken",
    "cooked noodle": "cooked noodle",
    "cooked pasta": "cooked pasta",
    "cooked rice": "cooked rice",
    "cookie": "cookie",
    "cookie crumb": "cookie crumb",
    "cooking oil": "cooking oil",
    "cooking spray": "cooking spray",
    "coriander": "coriander",
    "corn": "corn",
    "corn syrup": "corn syrup",
    "corn tortilla": "corn tortilla",
    "cornbread": "cornbread",
    "corned beef": "corned beef",
    "cornflour": "cornflour",
    "cornmeal": "cornmeal",
    "cornstarch": "cornstarch",
    "cottage cheese": "cottage cheese",
    "couscous": "couscous",
    "crab": "crab",
    "crabmeat": "crabmeat",
    "cracked pepper": "cracked pepper",
    "cracker": "cracker",
    "cranberry": "cranberry",
    "cranberry juice": "cranberry juice",
    "cranberry sauce": "cranberry sauce",
    "cream": "cream",
    "cream cheese": "cream cheese",
    "crepe": "crepe",
    "crisco": "crisco",
    "croissant": "croissant",
    "crouton": "crouton",
    "crushed tomato": "crushed tomato",
    "cucumber": "cucumber",
    "cumin": "cumin",
    "curry": "curry",
    "curry powder": "curry powder",
    "custard": "custard",
    "diced onion": "diced onion",
    "diced tomato": "diced tomato",
    "dijon mustard": "dijon mustard",
    "dill": "dill",
    "dill weed": "dill weed",
    "dried cranberry": "dried cranberry",
    "dried fruit": "dried fruit",
    "dry milk": "dry milk",
    "dry mustard": "dry mustard",
    "egg": "egg",
    "egg bread": "egg bread",
    "egg noodle": "egg noodle",
    "egg substitute": "egg substitute",
    "egg white": "egg white",
    "egg yolk": "egg yolk",
    "eggplant": "eggplant",
    "enchilada sauce": "enchilada sauce",
    "english muffin": "english muffin",
    "espresso": "espresso",
    "evaporated milk": "evaporated milk",
    "extract": "extract",
    "fat": "fat",
    "fennel": "fennel",
    "fennel seed": "fennel seed",
    "feta": "feta",
    "feta cheese": "feta cheese",
    "fettuccine": "fettuccine",
    "fig": "fig",
    "filling": "filling",
    "fish": "fish",
    "fish fillet": "fish fillet",
    "fish sauce": "fish sauce",
    "flavor": "flavor",
    "flavored": "flavored",
    "flour": "flour",
    "flour tortilla": "flour tortilla",
    "food coloring": "food coloring",
    "french bread": "french bread",
    "french fried onion": "french fried onion",
    "fresh basil": "fresh basil",
    "fresh cilantro": "fresh cilantro",
    "fresh fruit": "fresh fruit",
    "fresh ground pepper": "fresh ground pepper",
    "fresh herb": "fresh herb",
    "fresh lemon juice": "fresh lemon juice",
    "fresh mint": "fresh mint",
    "fresh parsley": "fresh parsley",
    "fresh tomato": "fresh tomato",
    "fried onion": "fried onion",
    "frosting": "frosting",
    "frozen": "frozen",
    "frozen pea": "frozen pea",
    "frozen yogurt": "frozen yogurt",
    "fruit": "fruit",
    "garam masala": "garam masala",
    "garlic": "garlic",
    "garlic clove": "garlic clove",
    "garlic paste": "garlic paste",
    "garlic powder": "garlic powder",
    "garlic salt": "garlic salt",
    "gelatin": "gelatin",
    "ghee": "ghee",
    "ginger": "ginger",
    "ginger ale": "ginger ale",
    "gluten": "gluten",
    "gnocchi": "gnocchi",
    "goat cheese": "goat cheese",
    "golden syrup": "golden syrup",
    "gorgonzola": "gorgonzola",
    "graham cracker": "graham cracker",
    "graham cracker crumb": "graham cracker crumb",
    "grain": "grain",
    "grand marnier": "grand marnier",
    "granulated sugar": "granulated sugar",
    "grape": "grape",
    "grapefruit": "grapefruit",
    "green": "green",
    "green bean": "green bean",
    "green bell pepper": "green bell pepper",
    "green chili": "green chili",
    "green chilie": "green chilie",
    "green onion": "green onion",
    "green pepper": "green pepper",
    "ground almond": "ground almond",
    "ground beef": "ground beef",
    "ground black pepper": "ground black pepper",
    "ground chuck": "ground chuck",
    "ground cinnamon": "ground cinnamon",
    "ground coriander": "ground coriander",
    "ground cumin": "ground cumin",
    "ground meat": "ground meat",
    "ground pepper": "ground pepper",
    "ground turkey": "ground turkey",
    "guacamole": "guacamole",
    "half": "half",
    "half half": "half half",
    "ham": "ham",
    "hamburger": "hamburger",
    "hamburger bun": "hamburger bun",
    "hard boiled egg": "hard boiled egg",
    "hazelnut": "hazelnut",
    "heavy cream": "heavy cream",
    "herb": "herb",
    "hoisin sauce": "hoisin sauce",
    "honey": "honey",
    "honey mustard": "honey mustard",
    "horseradish": "horseradish",
    "hot dog": "hot dog",
    "hot pepper": "hot pepper",
    "hot pepper sauce": "hot pepper sauce",
    "hot sauce": "hot sauce",
    "hot water": "hot water",
    "ice": "ice",
    "ice cream": "ice cream",
    "ice water": "ice water",
    "icing sugar": "icing sugar",
    "instant": "instant",
    "instant coffee": "instant coffee",
    "italian bread": "italian bread",
    "italian dressing": "italian dressing",
    "italian seasoning": "italian seasoning",
    "jack": "jack",
    "jalapeno": "jalapeno",
    "jalapeno pepper": "jalapeno pepper",
    "jam": "jam",
    "jar": "jar",
    "jell": "jell",
    "juice": "juice",
    "kahlua": "kahlua",
    "kale": "kale",
    "ketchup": "ketchup",
    "kidney bean": "kidney bean",
    "kielbasa": "kielbasa",
    "kirsch": "kirsch",
    "kiwi": "kiwi",
    "kosher salt": "kosher salt",
    "lamb": "lamb",
    "lard": "lard",
    "lasagna noodle": "lasagna noodle",
    "leek": "leek",
    "lemon": "lemon",
    "lemon juice": "lemon juice",
    "lemon peel": "lemon peel",
    "lemon pepper": "lemon pepper",
    "lemon rind": "lemon rind",
    "lemon slice": "lemon slice",
    "lemon wedge": "lemon wedge",
    "lemon zest": "lemon zest",
    "lemonade": "lemonade",
    "lemongrass": "lemongrass",
    "lentil": "lentil",
    "lettuce": "lettuce",
    "lettuce leaf": "lettuce leaf",
    "lettuce leaves": "lettuce leaves",
    "light": "light",
    "lime": "lime",
    "lime juice": "lime juice",
    "lime slice": "lime slice",
    "lime wedge": "lime wedge",
    "lime zest": "lime zest",
    "linguine": "linguine",
    "liquid": "liquid",
    "liquid smoke": "liquid smoke",
    "long": "long",
    "low fat": "low fat",
    "macadamia nut": "macadamia nut",
    "macaroni": "macaroni",
    "mango": "mango",
    "manicotti": "manicotti",
    "maple syrup": "maple syrup",
    "maraschino cherry": "maraschino cherry",
    "margarine": "margarine",
    "marinade": "marinade",
    "marinara sauce": "marinara sauce",
    "marjoram": "marjoram",
    "marmalade": "marmalade",
    "marshmallow": "marshmallow",
    "mascarpone": "mascarpone",
    "mascarpone cheese": "mascarpone cheese",
    "mashed banana": "mashed banana",
    "mashed potato": "mashed potato",
    "mayonnaise": "mayonnaise",
    "meat": "meat",
    "meatball": "meatball",
    "melon": "melon",
    "milk": "milk",
    "mint": "mint",
    "mint leaves": "mint leaves",
    "molasse": "molasse",
    "monterey jack cheese": "monterey jack cheese",
    "mozzarella cheese": "mozzarella cheese",
    "mushroom": "mushroom",
    "mushroom cap": "mushroom cap",
    "mushroom soup": "mushroom soup",
    "mussel": "mussel",
    "mustard": "mustard",
    "mustard seed": "mustard seed",
    "nonstick cooking spray": "nonstick cooking spray",
    "noodle": "noodle",
    "nut": "nut",
    "nutmeg": "nutmeg",
    "oat bran": "oat bran",
    "oatmeal": "oatmeal",
    "oats": "oats",
    "oil": "oil",
    "okra": "okra",
    "olive": "olive",
    "olive oil": "olive oil",
    "onion": "onion",
    "onion powder": "onion powder",
    "onion salt": "onion salt",
    "onion soup": "onion soup",
    "orange": "orange",
    "orange juice": "orange juice",
    "orange peel": "orange peel",
    "orange rind": "orange rind",
    "orange slice": "orange slice",
    "orange zest": "orange zest",
    "oregano": "oregano",
    "oyster sauce": "oyster sauce",
    "pan dripping": "pan dripping",
    "pancake": "pancake",
    "pancetta": "pancetta",
    "paper": "paper",
    "paprika": "paprika",
    "parchment paper": "parchment paper",
    "parmesan": "parmesan",
    "parmesan cheese": "parmesan cheese",
    "parmigiano": "parmigiano",
    "parsley": "parsley",
    "parsnip": "parsnip",
    "pasta": "pasta",
    "pasta sauce": "pasta sauce",
    "pastry shell": "pastry shell",
    "pea": "pea",
    "peach": "peach",
    "peanut": "peanut",
    "peanut butter": "peanut butter",
    "peanut oil": "peanut oil",
    "pear": "pear",
    "pecan": "pecan",
    "pecan half": "pecan half",
    "penne": "penne",
    "pepper": "pepper",
    "peppercorn": "peppercorn",
    "pepperoni": "pepperoni",
    "phyllo dough": "phyllo dough",
    "picante sauce": "picante sauce",
    "pickle": "pickle",
    "pico de gallo": "pico de gallo",
    "pie": "pie",
    "pie crust": "pie crust",
    "pie filling": "pie filling",
    "pie shell": "pie shell",
    "pine nut": "pine nut",
    "pineapple": "pineapple",
    "pineapple juice": "pineapple juice",
    "pistachio": "pistachio",
    "pita bread": "pita bread",
    "pizza crust": "pizza crust",
    "pizza dough": "pizza dough",
    "pizza sauce": "pizza sauce",
    "plantain": "plantain",
    "polenta": "polenta",
    "pomegranate": "pomegranate",
    "popcorn": "popcorn",
    "poppy seed": "poppy seed",
    "pork": "pork",
    "pork chop": "pork chop",
    "pork loin": "pork loin",
    "pork roast": "pork roast",
    "pork tenderloin": "pork tenderloin",
    "potato": "potato",
    "potato chip": "potato chip",
    "poultry seasoning": "poultry seasoning",
    "powdered milk": "powdered milk",
    "powdered sugar": "powdered sugar",
    "prawn": "prawn",
    "prepared": "prepared",
    "preserves": "preserves",
    "pretzel": "pretzel",
    "prosciutto": "prosciutto",
    "prune": "prune",
    "pudding": "pudding",
    "puff pastry": "puff pastry",
    "pumpkin": "pumpkin",
    "purpose flour": "purpose flour",
    "quinoa": "quinoa",
    "radish": "radish",
    "raisin": "raisin",
    "raman noodle": "raman noodle",
    "ranch dressing": "ranch dressing",
    "raspberry": "raspberry",
    "ravioli": "ravioli",
    "red": "red",
    "red bell pepper": "red bell pepper",
    "red onion": "red onion",
    "red pepper": "red pepper",
    "red pepper flake": "red pepper flake",
    "red wine": "red wine",
    "red wine vinegar": "red wine vinegar",
    "refried bean": "refried bean",
    "rhubarb": "rhubarb",
    "rice": "rice",
    "rice noodle": "rice noodle",
    "rice vinegar": "rice vinegar",
    "rice wine": "rice wine",
    "ricotta cheese": "ricotta cheese",
    "ritz cracker": "ritz cracker",
    "roast": "roast",
    "roasted": "roasted",
    "roasted pepper": "roasted pepper",
    "roasted red pepper": "roasted red pepper",
    "roll": "roll",
    "rolled oats": "rolled oats",
    "rolls": "rolls",
    "romaine lettuce": "romaine lettuce",
    "romano cheese": "romano cheese",
    "rosemary": "rosemary",
    "roux": "roux",
    "rum": "rum",
    "rye bread": "rye bread",
    "saffron": "saffron",
    "sage": "sage",
    "salad dressing": "salad dressing",
    "salad green": "salad green",
    "salmon": "salmon",
    "salmon fillet": "salmon fillet",
    "salsa": "salsa",
    "salt": "salt",
    "salt pepper": "salt pepper",
    "sauce": "sauce",
    "sauerkraut": "sauerkraut",
    "sausage": "sausage",
    "savory": "savory",
    "scallion": "scallion",
    "scallop": "scallop",
    "sea salt": "sea salt",
    "seafood": "seafood",
    "seasoned flour": "seasoned flour",
    "seasoning": "seasoning",
    "seasoning salt": "seasoning salt",
    "sesame oil": "sesame oil",
    "sesame seed": "sesame seed",
    "shallot": "shallot",
    "shortening": "shortening",
    "shredded cheddar cheese": "shredded cheddar cheese",
    "shredded coconut": "shredded coconut",
    "shrimp": "shrimp",
    "simple syrup": "simple syrup",
    "skim milk": "skim milk",
    "sliced almond": "sliced almond",
    "sliced mushroom": "sliced mushroom",
    "snap pea": "snap pea",
    "snow pea": "snow pea",
    "soda": "soda",
    "soup": "soup",
    "sour": "sour",
    "sour cream": "sour cream",
    "soy sauce": "soy sauce",
    "spaghetti": "spaghetti",
    "spaghetti sauce": "spaghetti sauce",
    "spice": "spice",
    "spinach": "spinach",
    "spreadable": "spreadable",
    "spring onion": "spring onion",
    "sprite": "sprite",
    "squash": "squash",
    "star anise": "star anise",
    "starch": "starch",
    "steak": "steak",
    "steak sauce": "steak sauce",
    "steak seasoning": "steak seasoning",
    "steamed rice": "steamed rice",
    "stewed tomato": "stewed tomato",
    "stock": "stock",
    "stove": "stove",
    "strawberry": "strawberry",
    "stuffing": "stuffing",
    "style": "style",
    "sugar": "sugar",
    "sugar syrup": "sugar syrup",
    "sun dried tomato": "sun dried tomato",
    "sunflower seed": "sunflower seed",
    "sweet potato": "sweet potato",
    "sweetened condensed milk": "sweetened condensed milk",
    "swiss chard": "swiss chard",
    "swiss cheese": "swiss cheese",
    "syrup": "syrup",
    "tabasco sauce": "tabasco sauce",
    "taco sauce": "taco sauce",
    "taco seasoning": "taco seasoning",
    "tahini": "tahini",
    "tamari": "tamari",
    "tap water": "tap water",
    "tapioca": "tapioca",
    "tarragon": "tarragon",
    "tea": "tea",
    "tea bag": "tea bag",
    "tempeh": "tempeh",
    "tequila": "tequila",
    "teriyaki sauce": "teriyaki sauce",
    "thyme": "thyme",
    "toasted almond": "toasted almond",
    "toasted sesame seed": "toasted sesame seed",
    "tofu": "tofu",
    "tomatillo": "tomatillo",
    "tomato": "tomato",
    "tomato juice": "tomato juice",
    "tomato paste": "tomato paste",
    "tomato puree": "tomato puree",
    "tomato sauce": "tomato sauce",
    "tomato soup": "tomato soup",
    "toothpick": "toothpick",
    "tortilla": "tortilla",
    "tortilla chip": "tortilla chip",
    "tuna": "tuna",
    "turkey": "turkey",
    "turkey breast": "turkey breast",
    "turmeric": "turmeric",
    "turnip": "turnip",
    "unsalted butter": "unsalted butter",
    "vanilla": "vanilla",
    "vanilla bean": "vanilla bean",
    "vanilla essence": "vanilla essence",
    "vanilla extract": "vanilla extract",
    "vanilla ice cream": "vanilla ice cream",
    "vanilla pudding": "vanilla pudding",
    "vanilla sugar": "vanilla sugar",
    "vanilla wafer": "vanilla wafer",
    "vegetable": "vegetable",
    "vegetable broth": "vegetable broth",
    "vegetable oil": "vegetable oil",
    "vegetable stock": "vegetable stock",
    "vermicelli": "vermicelli",
    "vinaigrette": "vinaigrette",
    "vinegar": "vinegar",
    "virgin olive oil": "virgin olive oil",
    "vodka": "vodka",
    "wafer": "wafer",
    "walnuts": "walnuts",
    "warm water": "warm water",
    "water": "water",
    "water chestnut": "water chestnut",
    "watercress": "watercress",
    "wheat": "wheat",
    "wheat germ": "wheat germ",
    "whipped": "whipped",
    "whipped cream": "whipped cream",
    "whipping cream": "whipping cream",
    "white": "white",
    "white bread": "white bread",
    "white chocolate": "white chocolate",
    "white chocolate chip": "white chocolate chip",
    "white flour": "white flour",
    "white pepper": "white pepper",
    "white rice": "white rice",
    "white sugar": "white sugar",
    "white wine": "white wine",
    "whole clove": "whole clove",
    "whole wheat flour": "whole wheat flour",
    "wild rice": "wild rice",
    "wine": "wine",
    "wonton wrapper": "wonton wrapper",
    "worcestershire sauce": "worcestershire sauce",
    "yam": "yam",
    "yeast": "yeast",
    "yellow onion": "yellow onion",
    "yoghurt": "yoghurt",
    "yogurt": "yogurt",
    "zest": "zest",
    "ziploc bag": "ziploc bag",
    "zucchini": "zucchini",
}
