ingredients_mappings = {
    "acorn squash": "acorn squash",
    "adobo sauce": "adobo sauce",
    "adobo seasoning": "adobo seasoning",
    "agave": "agave",
    "agave nectar": "agave nectar",
    "aioli": "aioli",
    "alcohol": "alcohol",
    "ale": "ale",
    "alfalfa sprout": "alfalfa sprout",
    "alfredo sauce": "alfredo sauce",
    "allspice": "allspice",
    "almond": "almond",
    "almond bark": "almond bark",
    "almond butter": "almond butter",
    "almond extract": "almond extract",
    "almond filling": "almond filling",
    "almond flour": "almond flour",
    "almond meal": "almond meal",
    "almond milk": "almond milk",
    "almond paste": "almond paste",
    "aluminum foil": "",
    "amaranth": "amaranth",
    "amaretto": "amaretto",
    "american": "",
    "american cheese": "american cheese",
    "anchovy": "anchovy",
    "anchovy paste": "anchovy paste",
    "angel food cake": "angel food cake",
    "angel hair pasta": "angel hair pasta",
    "anise": "anise",
    "anise seed": "anise seed",
    "apple": "apple",
    "apple butter": "apple butter",
    "apple cider": "apple cider",
    "apple cider vinegar": "apple cider vinegar",
    "apple jelly": "apple jelly",
    "apple juice": "apple juice",
    "apple juice concentrate": "apple juice concentrate",
    "apple peel": "apple peel",
    "apple pie filling": "apple pie filling",
    "apple pie spice": "apple pie spice",
    "apple ring": "apple ring",
    "applesauce": "apple sauce",
    "apricot": "apricot",
    "apricot half": "apricot half",
    "apricot jam": "apricot jam",
    "apricot nectar": "apricot nectar",
    "apricot preserves": "apricot preserves",
    "arrowroot": "arrowroot",
    "artichoke": "artichoke",
    "artichoke heart": "artichoke heart",
    "arugula": "arugula",
    "asiago": "asiago",
    "asiago cheese": "asiago cheese",
    "asparagus": "asparagus",
    "au jus": "au jus",
    "aubergine": "aubergine",
    "avocado": "avocado",
    "baby": "",
    "baby carrot": "baby carrot",
    "baby corn": "baby corn",
    "baby spinach": "baby spinach",
    "baby spinach leaves": "baby spinach leaves",
    "back": "back",
    "bacon": "bacon",
    "bacon bit": "bacon bit",
    "bacon dripping": "bacon dripping",
    "bacon fat": "bacon fat",
    "bacon grease": "bacon grease",
    "bacon piece": "bacon piece",
    "bagel": "bagel",
    "baguette": "baguette",
    "bake": "bake",
    "baked": "baked",
    "baked bean": "baked bean",
    "baking": "baking",
    "baking chocolate": "baking chocolate",
    "baking powder": "baking powder",
    "baking sheet": "baking sheet",
    "baking soda": "baking soda",
    "balloon": "balloon",
    "balsamic": "balsamic",
    "balsamic glaze": "balsamic glaze",
    "balsamic vinaigrette": "balsamic vinaigrette",
    "balsamic vinegar": "balsamic vinegar",
    "bamboo shoot": "bamboo shoot",
    "bamboo skewer": "bamboo skewer",
    "banana": "banana",
    "banana bread": "banana bread",
    "banana leaf": "banana leaf",
    "banana liqueur": "banana liqueur",
    "banana yogurt": "banana yogurt",
    "bar": "bar",
    "barbecue": "barbecue",
    "barbecue sauce": "barbecue sauce",
    "barley": "barley",
    "basil": "basil",
    "basil leaves": "basil leaves",
    "basil oil": "basil oil",
    "basil sprig": "basil sprig",
    "basmati rice": "basmati rice",
    "baste": "baste",
    "batter": "batter",
    "bay leaf": "bay leaf",
    "bay leaves": "bay leaves",
    "bean": "bean",
    "bean liquid": "bean liquid",
    "bean sprout": "bean sprout",
    "bechamel sauce": "bechamel sauce",
    "beef": "beef",
    "beef base": "beef base",
    "beef bouillon": "beef bouillon",
    "beef broth": "beef broth",
    "beef gravy": "beef gravy",
    "beef roast": "beef roast",
    "beef steak": "beef steak",
    "beef stock": "beef stock",
    "beer": "beer",
    "beet": "beet",
    "beetroot": "beetroot",
    "bell": "bell",
    "bell pepper": "bell pepper",
    "berry": "berry",
    "berry sugar": "berry sugar",
    "biscotti": "biscotti",
    "biscuit": "biscuit",
    "biscuit dough": "biscuit dough",
    "bisquick": "bisquick",
    "bitter": "bitter",
    "bittersweet chocolate": "bittersweet chocolate",
    "black": "black",
    "black bean": "black bean",
    "black bean sauce": "black bean sauce",
    "black eyed pea": "black eyed pea",
    "black olive": "black olive",
    "black pepper": "black pepper",
    "black peppercorn": "black peppercorn",
    "blackberry": "blackberry",
    "blanched almond": "blanched almond",
    "blend": "blend",
    "bloody mary": "bloody mary",
    "blue cheese": "blue cheese",
    "blue cheese dressing": "blue cheese dressing",
    "blue curacao": "blue curacao",
    "blueberry": "blueberry",
    "blueberry pie filling": "blueberry pie filling",
    "boiled potato": "boiled potato",
    "boiling water": "boiling water",
    "bok choy": "bok choy",
    "bologna": "bologna",
    "boneless chicken breast": "boneless chicken breast",
    "bouillon": "bouillon",
    "bouquet garni": "bouquet garni",
    "bourbon": "bourbon",
    "bran": "bran",
    "bran cereal": "bran cereal",
    "brandy": "brandy",
    "bratwurst": "bratwurst",
    "bread": "bread",
    "bread bowl": "bread bowl",
    "bread dough": "bread dough",
    "bread flour": "bread flour",
    "bread pudding": "bread pudding",
    "bread round": "bread round",
    "breadcrumb": "breadcrumb",
    "breading": "breading",
    "breadstick": "breadstick",
    "brewed coffee": "brewed coffee",
    "brine": "brine",
    "broccoli": "broccoli",
    "broccoli floret": "broccoli floret",
    "broccoli rabe": "broccoli rabe",
    "broccoli slaw": "broccoli slaw",
    "broccoli stems": "broccoli stems",
    "broccolini": "broccolini",
    "broiler": "broiler",
    "broth": "broth",
    "brown": "brown",
    "brown gravy": "brown gravy",
    "brown onion": "brown onion",
    "brown paper bag": "brown paper bag",
    "brown rice": "brown rice",
    "brown rice flour": "brown rice flour",
    "brown sugar": "brown sugar",
    "brownie": "brownie",
    "brussels sprout": "brussels sprout",
    "buckwheat flour": "buckwheat flour",
    "buffalo": "buffalo",
    "bulgur": "bulgur",
    "bulgur wheat": "bulgur wheat",
    "bun": "bun",
    "burrito": "burrito",
    "butter": "butter",
    "butter bean": "butter bean",
    "buttercream frosting": "buttercream frosting",
    "buttered bread crumb": "buttered bread crumb",
    "buttermilk": "buttermilk",
    "butternut squash": "butternut squash",
    "butterscotch": "butterscotch",
    "butterscotch chip": "butterscotch chip",
    "cabbage": "cabbage",
    "cabbage leaf": "cabbage leaf",
    "cacao": "cacao",
    "cajun seasoning": "cajun seasoning",
    "cajun spice": "cajun spice",
    "cake": "cake",
    "cake flour": "cake flour",
    "calamari": "calamari",
    "canadian bacon": "canadian bacon",
    "candied": "candied",
    "candied cherry": "candied cherry",
    "candied fruit": "candied fruit",
    "candied ginger": "candied ginger",
    "candle": "candle",
    "candy": "candy",
    "candy bar": "candy bar",
    "candy cane": "candy cane",
    "candy coating": "candy coating",
    "candy corn": "candy corn",
    "canola oil": "canola oil",
    "cantaloupe": "cantaloupe",
    "caper": "caper",
    "capsicum": "capsicum",
    "caramel": "caramel",
    "caramel ice cream": "caramel ice cream",
    "caramel sauce": "caramel sauce",
    "caramel syrup": "caramel syrup",
    "caramelized onion": "caramelized onion",
    "caraway seed": "caraway seed",
    "cardamom": "cardamom",
    "cardamom pod": "cardamom pod",
    "cardamom seed": "cardamom seed",
    "carrot": "carrot",
    "carrot cake": "carrot cake",
    "carrot stick": "carrot stick",
    "cashew": "cashew",
    "cashew nut": "cashew nut",
    "casing": "casing",
    "caster sugar": "caster sugar",
    "catfish": "catfish",
    "catfish fillet": "catfish fillet",
    "catsup": "catsup",
    "cauliflower": "cauliflower",
    "cauliflower floret": "cauliflower floret",
    "caviar": "caviar",
    "cayenne": "cayenne",
    "cayenne pepper": "cayenne pepper",
    "cedar plank": "cedar plank",
    "celeriac": "celeriac",
    "celery": "celery",
    "celery leaves": "celery leaves",
    "celery root": "celery root",
    "celery salt": "celery salt",
    "celery seed": "celery seed",
    "celery soup": "celery soup",
    "cereal": "cereal",
    "challah": "challah",
    "champagne": "champagne",
    "charcoal": "charcoal",
    "chayote": "chayote",
    "cheddar": "cheddar",
    "cheddar cheese": "cheddar cheese",
    "cheddar cheese soup": "cheddar cheese soup",
    "cheese": "cheese",
    "cheese sauce": "cheese sauce",
    "cheese slice": "cheese slice",
    "cheese soup": "cheese soup",
    "cheese spread": "cheese spread",
    "cheese whiz": "cheese whiz",
    "cheesecake": "cheesecake",
    "cheesecake filling": "cheesecake filling",
    "cheesecloth": "cheesecloth",
    "cheez whiz": "cheez whiz",
    "cherry": "cherry",
    "cherry juice": "cherry juice",
    "cherry pie filling": "cherry pie filling",
    "cherry tomato": "cherry tomato",
    "chervil": "chervil",
    "chestnut": "chestnut",
    "chick pea": "chick pea",
    "chicken": "chicken",
    "chicken back": "chicken back",
    "chicken bacon": "chicken bacon",
    "chicken base": "chicken base",
    "chicken bone": "chicken bone",
    "chicken bouillon": "chicken bouillon",
    "chicken breast": "chicken breast",
    "chicken breast half": "chicken breast half",
    "chicken breast halves": "chicken breast halves",
    "chicken broth": "chicken broth",
    "chicken chunk": "chicken chunk",
    "chicken cutlet": "chicken cutlet",
    "chicken fat": "chicken fat",
    "chicken fillet": "chicken fillet",
    "chicken half": "chicken half",
    "chicken leg": "chicken leg",
    "chicken liver": "chicken liver",
    "chicken meat": "chicken meat",
    "chicken part": "chicken part",
    "chicken piece": "chicken piece",
    "chicken salad": "chicken salad",
    "chicken seasoning": "chicken seasoning",
    "chicken soup": "chicken soup",
    "chicken stock": "chicken stock",
    "chicken strip": "chicken strip",
    "chicken tender": "chicken tender",
    "chicken thigh": "chicken thigh",
    "chicken wing": "chicken wing",
    "chickpea": "chickpea",
    "chicory": "chicory",
    "chile": "chili",
    "chile powder": "chile powder",
    "chili": "chili",
    "chili bean": "chili bean",
    "chili flake": "chili flake",
    "chili garlic sauce": "chili garlic sauce",
    "chili oil": "chili oil",
    "chili paste": "chili paste",
    "chili pepper": "chili pepper",
    "chili powder": "chili powder",
    "chili sauce": "chili sauce",
    "chili seasoning": "chili seasoning",
    "chilie": "chilie",
    "chimichurri sauce": "chimichurri sauce",
    "chip": "chip",
    "chipotle chile": "chipotle chile",
    "chipotle pepper": "chipotle pepper",
    "chive": "chive",
    "chocolate": "chocolate",
    "chocolate bar": "chocolate bar",
    "chocolate cake": "chocolate cake",
    "chocolate chip": "chocolate chip",
    "chocolate chip cookie": "chocolate chip cookie",
    "chocolate cookie": "chocolate cookie",
    "chocolate cream": "chocolate cream",
    "chocolate curl": "chocolate curl",
    "chocolate frosting": "chocolate frosting",
    "chocolate glaze": "chocolate glaze",
    "chocolate ice cream": "chocolate ice cream",
    "chocolate icing": "chocolate icing",
    "chocolate milk": "chocolate milk",
    "chocolate mousse": "chocolate mousse",
    "chocolate piece": "chocolate piece",
    "chocolate pudding": "chocolate pudding",
    "chocolate sauce": "chocolate sauce",
    "chocolate shaving": "chocolate shaving",
    "chocolate sprinkle": "chocolate sprinkle",
    "chocolate square": "chocolate square",
    "chocolate syrup": "chocolate syrup",
    "chocolate wafer": "chocolate wafer",
    "chopped": "chopped",
    "chopped tomato": "chopped tomato",
    "chow mein noodle": "chow mein noodle",
    "chuck": "chuck",
    "chuck roast": "chuck roast",
    "chutney": "chutney",
    "ciabatta": "ciabatta",
    "cider": "cider",
    "cider vinegar": "cider vinegar",
    "cilantro": "cilantro",
    "cilantro leaves": "cilantro leaves",
    "cinnamon": "cinnamon",
    "cinnamon spread": "cinnamon spread",
    "cinnamon stick": "cinnamon stick",
    "cinnamon sugar": "cinnamon sugar",
    "cinnamon sugar mixture": "cinnamon sugar mixture",
    "citrus juice": "citrus juice",
    "clam": "clam",
    "clam juice": "clam juice",
    "clams": "clams",
    "clarified butter": "clarified butter",
    "clementine": "clementine",
    "clove": "clove",
    "club soda": "club soda",
    "cluster": "cluster",
    "coarse salt": "coarse salt",
    "coarse sugar": "coarse sugar",
    "coating": "coating",
    "coca cola": "coca cola",
    "cocoa": "cocoa",
    "cocoa powder": "cocoa powder",
    "coconut": "coconut",
    "coconut cream": "coconut cream",
    "coconut extract": "coconut extract",
    "coconut flake": "coconut flake",
    "coconut flour": "coconut flour",
    "coconut milk": "coconut milk",
    "coconut oil": "coconut oil",
    "coconut rum": "coconut rum",
    "coconut sugar": "coconut sugar",
    "cod": "cod",
    "coffee": "coffee",
    "coffee bean": "coffee bean",
    "coffee filter": "coffee filter",
    "coffee liqueur": "coffee liqueur",
    "coffeecake": "coffeecake",
    "cognac": "cognac",
    "coke": "coke",
    "cola": "cola",
    "colby": "colby",
    "cold cut": "cold cut",
    "cold water": "cold water",
    "coleslaw": "coleslaw",
    "collard green": "collard green",
    "complete": "",
    "condensed": "condensed",
    "condensed milk": "condensed milk",
    "condiment": "condiment",
    "confectioner sugar": "confectioner sugar",
    "consomme": "consomme",
    "cooked": "cooked",
    "cooked bacon": "cooked bacon",
    "cooked barley": "cooked barley",
    "cooked beef": "cooked beef",
    "cooked broccoli": "cooked broccoli",
    "cooked brown rice": "cooked brown rice",
    "cooked chicken": "cooked chicken",
    "cooked chicken breast": "cooked chicken breast",
    "cooked egg noodle": "cooked egg noodle",
    "cooked ground beef": "cooked ground beef",
    "cooked macaroni": "cooked macaroni",
    "cooked noodle": "cooked noodle",
    "cooked pasta": "cooked pasta",
    "cooked quinoa": "cooked quinoa",
    "cooked rice": "cooked rice",
    "cooked sausage": "cooked sausage",
    "cooked shrimp": "cooked shrimp",
    "cooked spaghetti": "cooked spaghetti",
    "cookie": "cookie",
    "cookie crumb": "cookie crumb",
    "cookie cutter": "cookie cutter",
    "cookie dough": "cookie dough",
    "cooking": "cooking",
    "cooking oil": "cooking oil",
    "cooking spray": "cooking spray",
    "cooking wine": "cooking wine",
    "cool whip": "cool whip",
    "cool whip topping": "cool whip topping",
    "coriander": "coriander",
    "coriander powder": "coriander powder",
    "coriander seed": "coriander seed",
    "corn": "corn",
    "corn cake": "corn cake",
    "corn chip": "corn chip",
    "corn cobs": "corn cobs",
    "corn flake": "corn flake",
    "corn flake crumb": "corn flake crumb",
    "corn husk": "corn husk",
    "corn kernel": "corn kernel",
    "corn muffin": "corn muffin",
    "corn oil": "corn oil",
    "corn syrup": "corn syrup",
    "corn tortilla": "corn tortilla",
    "corn tortilla chip": "corn tortilla chip",
    "cornbread": "cornbread",
    "cornbread batter": "cornbread batter",
    "corned beef": "corned beef",
    "cornflour": "cornflour",
    "cornmeal": "cornmeal",
    "cornstarch": "cornstarch",
    "cottage cheese": "cottage cheese",
    "courgette": "courgette",
    "couscous": "couscous",
    "crab": "crab",
    "crabmeat": "crabmeat",
    "cracked black pepper": "cracked black pepper",
    "cracked ice": "cracked ice",
    "cracked pepper": "cracked pepper",
    "cracker": "cracker",
    "cracker crumb": "cracker crumb",
    "crackling": "crackling",
    "craisin": "craisin",
    "cranberry": "cranberry",
    "cranberry juice": "cranberry juice",
    "cranberry sauce": "cranberry sauce",
    "crawfish": "crawfish",
    "cream": "cream",
    "cream cheese": "cream cheese",
    "cream cheese frosting": "cream cheese frosting",
    "cream cheese spread": "cream cheese spread",
    "cream flour": "cream flour",
    "cream soup": "cream soup",
    "cream style corn": "cream style corn",
    "creamed corn": "creamed corn",
    "crema": "crema",
    "creme": "creme",
    "creme de cacao": "creme de cacao",
    "creme de menthe": "creme de menthe",
    "creme fraiche": "creme fraiche",
    "creole seasoning": "creole seasoning",
    "crepe": "crepe",
    "crescent roll": "crescent roll",
    "crescent roll dough": "crescent roll dough",
    "crescent rolls": "crescent rolls",
    "crisco": "crisco",
    "crisp": "crisp",
    "crisp bacon": "crisp bacon",
    "crispy": "crispy",
    "croissant": "croissant",
    "crostini": "crostini",
    "crouton": "crouton",
    "crumb": "crumb",
    "crumpet": "crumpet",
    "crunch": "crunch",
    "crunchy": "crunchy",
    "crushed pineapple": "crushed pineapple",
    "crushed tomato": "crushed tomato",
    "crusty bread": "crusty bread",
    "crystallized ginger": "crystallized ginger",
    "cucumber": "cucumber",
    "cumin": "cumin",
    "cumin powder": "cumin powder",
    "cumin seed": "cumin seed",
    "cupcake": "cupcake",
    "cupcake liner": "cupcake liner",
    "curd": "curd",
    "currant": "currant",
    "curry": "curry",
    "curry paste": "curry paste",
    "curry powder": "curry powder",
    "curry sauce": "curry sauce",
    "custard": "custard",
    "custard powder": "custard powder",
    "dal": "dal",
    "dark brown sugar": "dark brown sugar",
    "dark chocolate": "dark chocolate",
    "dark rum": "dark rum",
    "dash": "dash",
    "date": "date",
    "date filling": "date filling",
    "deep fat": "deep fat",
    "dessert": "dessert",
    "diced": "diced",
    "diced onion": "diced onion",
    "diced potato": "diced potato",
    "diced tomato": "diced tomato",
    "diet": "diet",
    "dijon mustard": "dijon mustard",
    "dill": "dill",
    "dill pickle": "dill pickle",
    "dill sauce": "dill sauce",
    "dill seed": "dill seed",
    "dill weed": "dill weed",
    "dinner": "dinner",
    "dinner roll": "dinner roll",
    "dip": "dip",
    "dipper": "dipper",
    "dipping chocolate": "dipping chocolate",
    "dipping sauce": "dipping sauce",
    "dorito": "dorito",
    "double cream": "double cream",
    "doughnut": "doughnut",
    "dream whip": "dream whip",
    "dressing": "dressing",
    "dried": "dried",
    "dried apple": "dried apple",
    "dried apricot": "dried apricot",
    "dried basil": "dried basil",
    "dried bean": "dried bean",
    "dried beef": "dried beef",
    "dried cherry": "dried cherry",
    "dried cranberry": "dried cranberry",
    "dried fruit": "dried fruit",
    "dried herb": "dried herb",
    "dried mushroom": "dried mushroom",
    "dried onion": "dried onion",
    "dried oregano": "dried oregano",
    "dried parsley": "dried parsley",
    "dried thyme": "dried thyme",
    "dried tomato": "dried tomato",
    "dripping": "dripping",
    "dry bread": "dry bread",
    "dry milk": "dry milk",
    "dry mustard": "dry mustard",
    "dry onion soup": "dry onion soup",
    "dry sherry": "dry sherry",
    "dry white wine": "dry white wine",
    "dry yeast": "dry yeast",
    "duck": "duck",
    "duck breast": "duck breast",
    "duck fat": "duck fat",
    "dulce de leche": "dulce de leche",
    "dumpling": "dumpling",
    "edamame": "edamame",
    "egg": "egg",
    "egg bread": "egg bread",
    "egg noodle": "egg noodle",
    "egg substitute": "egg substitute",
    "egg wash": "egg wash",
    "egg white": "egg white",
    "egg yolk": "egg yolk",
    "eggnog": "eggnog",
    "eggplant": "eggplant",
    "elbow macaroni": "elbow macaroni",
    "enchilada sauce": "enchilada sauce",
    "endive": "endive",
    "english muffin": "english muffin",
    "escargot": "escargot",
    "escarole": "escarole",
    "espresso": "espresso",
    "espresso powder": "espresso powder",
    "evaporated milk": "evaporated milk",
    "extract": "extract",
    "fajita seasoning": "fajita seasoning",
    "falafel": "falafel",
    "fat": "fat",
    "fat sour cream": "fat sour cream",
    "fava bean": "fava bean",
    "favorite sauce": "favorite sauce",
    "fennel": "fennel",
    "fennel bulb": "fennel bulb",
    "fennel seed": "fennel seed",
    "fenugreek seed": "fenugreek seed",
    "feta": "feta",
    "feta cheese": "feta cheese",
    "fettuccine": "fettuccine",
    "fiber": "fiber",
    "fig": "fig",
    "fillet": "fillet",
    "filling": "filling",
    "fine breadcrumb": "fine breadcrumb",
    "fish": "fish",
    "fish fillet": "fish fillet",
    "fish sauce": "fish sauce",
    "fish steak": "fish steak",
    "fish stock": "fish stock",
    "five spice powder": "five spice powder",
    "flake": "flake",
    "flaked coconut": "flaked coconut",
    "flank steak": "flank steak",
    "flat bread": "flat bread",
    "flavor": "flavor",
    "flavored": "flavored",
    "flavoring": "flavoring",
    "flax": "flax",
    "flax seed": "flax seed",
    "flounder": "flounder",
    "flour": "flour",
    "flour tortilla": "flour tortilla",
    "fondant": "fondant",
    "fontina": "fontina",
    "fontina cheese": "fontina cheese",
    "food coloring": "food coloring",
    "frangelico": "frangelico",
    "frank": "frank",
    "frankfurter": "frankfurter",
    "french": "french",
    "french bread": "french bread",
    "french dressing": "french dressing",
    "french fried onion": "french fried onion",
    "french fry": "french fry",
    "french onion soup": "french onion soup",
    "fresh": "fresh",
    "fresh basil": "fresh basil",
    "fresh basil leaves": "fresh basil leaves",
    "fresh black pepper": "fresh black pepper",
    "fresh blueberry": "fresh blueberry",
    "fresh chive": "fresh chive",
    "fresh cilantro": "fresh cilantro",
    "fresh coriander": "fresh coriander",
    "fresh cranberry": "fresh cranberry",
    "fresh cream": "fresh cream",
    "fresh dill": "fresh dill",
    "fresh fruit": "fresh fruit",
    "fresh garlic": "fresh garlic",
    "fresh ginger": "fresh ginger",
    "fresh ground pepper": "fresh ground pepper",
    "fresh herb": "fresh herb",
    "fresh lemon": "fresh lemon",
    "fresh lemon juice": "fresh lemon juice",
    "fresh lime juice": "fresh lime juice",
    "fresh mint": "fresh mint",
    "fresh mushroom": "fresh mushroom",
    "fresh oregano": "fresh oregano",
    "fresh parsley": "fresh parsley",
    "fresh peach": "fresh peach",
    "fresh pepper": "fresh pepper",
    "fresh raspberry": "fresh raspberry",
    "fresh rosemary": "fresh rosemary",
    "fresh spinach": "fresh spinach",
    "fresh strawberry": "fresh strawberry",
    "fresh thyme": "fresh thyme",
    "fresh tomato": "fresh tomato",
    "fresh water": "fresh water",
    "fried": "fried",
    "fried chicken": "fried chicken",
    "fried onion": "fried onion",
    "fried rice": "fried rice",
    "frosting": "frosting",
    "frozen": "frozen",
    "frozen blueberry": "frozen blueberry",
    "frozen broccoli": "frozen broccoli",
    "frozen corn": "frozen corn",
    "frozen fruit": "frozen fruit",
    "frozen pea": "frozen pea",
    "frozen spinach": "frozen spinach",
    "frozen strawberry": "frozen strawberry",
    "frozen vegetable": "frozen vegetable",
    "frozen yogurt": "frozen yogurt",
    "fruit": "fruit",
    "fruit cocktail": "fruit cocktail",
    "fruit filling": "fruit filling",
    "fruit juice": "fruit juice",
    "fruit salad": "fruit salad",
    "fruit slice": "fruit slice",
    "fruit spread": "fruit spread",
    "fryer": "fryer",
    "frying oil": "frying oil",
    "fudge": "fudge",
    "fudge sauce": "fudge sauce",
    "fusilli": "fusilli",
    "game": "game",
    "ganache": "ganache",
    "garam masala": "garam masala",
    "garbanzo bean": "garbanzo bean",
    "garlic": "garlic",
    "garlic bread": "garlic bread",
    "garlic butter": "garlic butter",
    "garlic clove": "garlic clove",
    "garlic head": "garlic head",
    "garlic mustard": "garlic mustard",
    "garlic oil": "garlic oil",
    "garlic paste": "garlic paste",
    "garlic powder": "garlic powder",
    "garlic salt": "garlic salt",
    "garlic sauce": "garlic sauce",
    "garlic season": "garlic season",
    "garlic seasoning": "garlic seasoning",
    "garlic spread": "garlic spread",
    "garlic toast": "garlic toast",
    "gelatin": "gelatin",
    "ghee": "ghee",
    "gherkin": "gherkin",
    "gin": "gin",
    "ginger": "ginger",
    "ginger ale": "ginger ale",
    "ginger beer": "ginger beer",
    "ginger garlic paste": "ginger garlic paste",
    "ginger juice": "ginger juice",
    "ginger paste": "ginger paste",
    "gingerbread": "gingerbread",
    "gingerroot": "gingerroot",
    "gingersnap": "gingersnap",
    "glaze": "glaze",
    "glue": "glue",
    "gluten": "gluten",
    "gnocchi": "gnocchi",
    "goat cheese": "goat cheese",
    "golden raisin": "golden raisin",
    "golden syrup": "golden syrup",
    "good": "good",
    "goose": "goose",
    "gorgonzola": "gorgonzola",
    "gouda cheese": "gouda cheese",
    "graham cracker": "graham cracker",
    "graham cracker crumb": "graham cracker crumb",
    "graham cracker crust": "graham cracker crust",
    "grain": "grain",
    "grand marnier": "grand marnier",
    "granny smith apple": "granny smith apple",
    "granola": "granola",
    "granulated garlic": "granulated garlic",
    "granulated sugar": "granulated sugar",
    "grape": "grape",
    "grape juice": "grape juice",
    "grape tomato": "grape tomato",
    "grapefruit": "grapefruit",
    "grapefruit juice": "grapefruit juice",
    "grapefruit section": "grapefruit section",
    "grapeseed oil": "grapeseed oil",
    "gravy": "gravy",
    "greek": "greek",
    "greek yogurt": "greek yogurt",
    "green": "green",
    "green apple": "green apple",
    "green bean": "green bean",
    "green bell pepper": "green bell pepper",
    "green chili": "green chili",
    "green chilie": "green chilie",
    "green food coloring": "green food coloring",
    "green olive": "green olive",
    "green onion": "green onion",
    "green pea": "green pea",
    "green pepper": "green pepper",
    "green salad": "green salad",
    "green tomato": "green tomato",
    "grenadine": "grenadine",
    "grilled chicken": "grilled chicken",
    "grit": "grit",
    "ground": "ground",
    "ground almond": "ground almond",
    "ground beef": "ground beef",
    "ground black pepper": "ground black pepper",
    "ground chicken": "ground chicken",
    "ground chuck": "ground chuck",
    "ground cinnamon": "ground cinnamon",
    "ground clove": "ground clove",
    "ground coffee": "ground coffee",
    "ground coriander": "ground coriander",
    "ground cumin": "ground cumin",
    "ground ginger": "ground ginger",
    "ground lamb": "ground lamb",
    "ground meat": "ground meat",
    "ground mustard": "ground mustard",
    "ground nut": "ground nut",
    "ground nutmeg": "ground nutmeg",
    "ground pepper": "ground pepper",
    "ground pork": "ground pork",
    "ground red pepper": "ground red pepper",
    "ground round": "ground round",
    "ground sirloin": "ground sirloin",
    "ground turkey": "ground turkey",
    "gruyere": "gruyere",
    "gruyere cheese": "gruyere cheese",
    "guacamole": "guacamole",
    "guar gum": "guar gum",
    "guava": "guava",
    "gumdrop": "gumdrop",
    "gummy worm": "gummy worm",
    "habanero": "habanero",
    "haddock": "haddock",
    "half": "half",
    "half cream": "half cream",
    "half half": "half half",
    "halibut": "halibut",
    "ham": "ham",
    "ham bone": "ham bone",
    "ham hock": "ham hock",
    "ham slice": "ham slice",
    "ham steak": "ham steak",
    "hamburger": "hamburger",
    "hamburger bun": "hamburger bun",
    "hamburger meat": "hamburger meat",
    "hamburger patty": "hamburger patty",
    "hard boiled egg": "hard boiled egg",
    "hard cooked egg": "hard cooked egg",
    "harissa": "harissa",
    "hash": "hash",
    "hash brown": "hash brown",
    "hazelnut": "hazelnut",
    "heavy cream": "heavy cream",
    "heavy whipping cream": "heavy whipping cream",
    "hen": "hen",
    "herb": "herb",
    "herb seasoning": "herb seasoning",
    "hickory": "hickory",
    "hidden": "hidden",
    "hoagie roll": "hoagie roll",
    "hock": "hock",
    "hoisin sauce": "hoisin sauce",
    "holiday": "holiday",
    "hollandaise sauce": "hollandaise sauce",
    "hominy": "hominy",
    "honey": "honey",
    "honey mustard": "honey mustard",
    "horseradish": "horseradish",
    "horseradish mustard": "horseradish mustard",
    "horseradish sauce": "horseradish sauce",
    "hot cocoa": "hot cocoa",
    "hot coffee": "hot coffee",
    "hot dog": "hot dog",
    "hot dog bun": "hot dog bun",
    "hot fudge": "hot fudge",
    "hot pepper": "hot pepper",
    "hot pepper flake": "hot pepper flake",
    "hot pepper sauce": "hot pepper sauce",
    "hot roll": "hot roll",
    "hot sauce": "hot sauce",
    "hot water": "hot water",
    "house": "house",
    "hummus": "hummus",
    "ice": "ice",
    "ice cream": "ice cream",
    "ice water": "ice water",
    "iceberg lettuce": "iceberg lettuce",
    "iced tea": "iced tea",
    "icing": "icing",
    "icing sugar": "icing sugar",
    "instant": "instant",
    "instant coffee": "instant coffee",
    "instant pudding": "instant pudding",
    "instant rice": "instant rice",
    "irish cream": "irish cream",
    "italian": "italian",
    "italian bread": "italian bread",
    "italian dressing": "italian dressing",
    "italian parsley": "italian parsley",
    "italian sausage": "italian sausage",
    "italian seasoning": "italian seasoning",
    "jack": "jack",
    "jalapeno": "jalapeno",
    "jalapeno pepper": "jalapeno pepper",
    "jalapeno slice": "jalapeno slice",
    "jam": "jam",
    "jar": "jar",
    "jasmine rice": "jasmine rice",
    "jell": "jell",
    "jelly": "jelly",
    "jicama": "jicama",
    "juice": "juice",
    "juniper berry": "juniper berry",
    "kahlua": "kahlua",
    "kalamata olive": "kalamata olive",
    "kale": "kale",
    "karo syrup": "karo syrup",
    "ketchup": "ketchup",
    "kidney bean": "kidney bean",
    "kielbasa": "kielbasa",
    "kirsch": "kirsch",
    "kitchen bouquet": "kitchen bouquet",
    "kitchen twine": "kitchen twine",
    "kiwi": "kiwi",
    "kohlrabi": "kohlrabi",
    "kool aid": "kool aid",
    "kosher salt": "kosher salt",
    "kraft": "kraft",
    "ladyfinger": "ladyfinger",
    "lamb": "lamb",
    "lamb chop": "lamb chop",
    "lamb chops": "lamb chops",
    "lamb shank": "lamb shank",
    "lard": "lard",
    "lardon": "lardon",
    "lasagna noodle": "lasagna noodle",
    "lavender": "lavender",
    "leaf thyme": "leaf thyme",
    "leaves": "leaves",
    "leek": "leek",
    "lemon": "lemon",
    "lemon curd": "lemon curd",
    "lemon extract": "lemon extract",
    "lemon juice": "lemon juice",
    "lemon peel": "lemon peel",
    "lemon pepper": "lemon pepper",
    "lemon pepper seasoning": "lemon pepper seasoning",
    "lemon rind": "lemon rind",
    "lemon slice": "lemon slice",
    "lemon wedge": "lemon wedge",
    "lemon zest": "lemon zest",
    "lemonade": "lemonade",
    "lemonade concentrate": "lemonade concentrate",
    "lemongrass": "lemongrass",
    "lentil": "lentil",
    "lettuce": "lettuce",
    "lettuce leaf": "lettuce leaf",
    "lettuce leaves": "lettuce leaves",
    "light": "light",
    "light brown sugar": "light brown sugar",
    "light cream": "light cream",
    "lime": "lime",
    "lime juice": "lime juice",
    "lime peel": "lime peel",
    "lime rind": "lime rind",
    "lime slice": "lime slice",
    "lime wedge": "lime wedge",
    "lime zest": "lime zest",
    "limeade": "limeade",
    "linguine": "linguine",
    "liqueur": "liqueur",
    "liquid": "liquid",
    "liquid smoke": "liquid smoke",
    "liquor": "liquor",
    "liver": "liver",
    "lobster": "lobster",
    "long": "long",
    "low fat": "low fat",
    "macadamia": "macadamia",
    "macadamia nut": "macadamia nut",
    "macaroni": "macaroni",
    "macaroon": "macaroon",
    "mace": "mace",
    "mandarin orange": "mandarin orange",
    "mango": "mango",
    "mango chutney": "mango chutney",
    "mango salsa": "mango salsa",
    "manicotti": "manicotti",
    "maple": "maple",
    "maple extract": "maple extract",
    "maple syrup": "maple syrup",
    "maraschino cherry": "maraschino cherry",
    "marbled": "marbled",
    "margarine": "margarine",
    "margarita": "margarita",
    "marinade": "marinade",
    "marinara sauce": "marinara sauce",
    "marjoram": "marjoram",
    "marmalade": "marmalade",
    "marsala": "marsala",
    "marsala wine": "marsala wine",
    "marshmallow": "marshmallow",
    "marshmallow cream": "marshmallow cream",
    "marshmallow creme": "marshmallow creme",
    "martini": "martini",
    "marzipan": "marzipan",
    "masa harina": "masa harina",
    "masala": "masala",
    "mascarpone": "mascarpone",
    "mascarpone cheese": "mascarpone cheese",
    "mashed": "mashed",
    "mashed banana": "mashed banana",
    "mashed potato": "mashed potato",
    "mashed sweet potato": "mashed sweet potato",
    "matzo meal": "matzo meal",
    "matzoh": "matzoh",
    "mayonnaise": "mayonnaise",
    "meal": "meal",
    "meat": "meat",
    "meat tenderizer": "meat tenderizer",
    "meatball": "meatball",
    "meatloaf": "meatloaf",
    "melba toast": "melba toast",
    "melon": "melon",
    "melon ball": "melon ball",
    "meringue": "meringue",
    "mexican cheese": "mexican cheese",
    "mexican rice": "mexican rice",
    "milk": "milk",
    "milk chocolate": "milk chocolate",
    "milk chocolate chip": "milk chocolate chip",
    "millet": "millet",
    "minced garlic clove": "minced garlic clove",
    "minced ginger": "minced ginger",
    "mincemeat": "mincemeat",
    "mini chocolate chip": "mini chocolate chip",
    "mini marshmallow": "mini marshmallow",
    "mint": "mint",
    "mint extract": "mint extract",
    "mint leaf": "mint leaf",
    "mint leaves": "mint leaves",
    "mint sprig": "mint sprig",
    "minute rice": "minute rice",
    "miracle whip": "miracle whip",
    "mirin": "mirin",
    "miso": "miso",
    "mixed berry": "mixed berry",
    "mixed green": "mixed green",
    "mixed spice": "mixed spice",
    "mixed vegetable": "mixed vegetable",
    "molasse": "molasse",
    "mole": "mole",
    "monterey": "monterey",
    "monterey jack cheese": "monterey jack cheese",
    "morsel": "morsel",
    "mozzarella": "mozzarella",
    "mozzarella cheese": "mozzarella cheese",
    "mrs": "mrs",
    "msg": "msg",
    "muesli": "muesli",
    "muffin": "muffin",
    "mushroom": "mushroom",
    "mushroom cap": "mushroom cap",
    "mushroom liquid": "mushroom liquid",
    "mushroom piece": "mushroom piece",
    "mushroom slice": "mushroom slice",
    "mushroom soup": "mushroom soup",
    "mushroom stems": "mushroom stems",
    "mussel": "mussel",
    "mustard": "mustard",
    "mustard oil": "mustard oil",
    "mustard powder": "mustard powder",
    "mustard seed": "mustard seed",
    "naan bread": "naan bread",
    "neck": "neck",
    "nectarine": "nectarine",
    "nestle": "nestle",
    "neufchatel cheese": "neufchatel cheese",
    "new potato": "new potato",
    "nonstick cooking spray": "nonstick cooking spray",
    "noodle": "noodle",
    "nori": "nori",
    "nut": "nut",
    "nut butter": "nut butter",
    "nutella": "nutella",
    "nutmeg": "nutmeg",
    "nutritional yeast": "nutritional yeast",
    "oat": "oat",
    "oat bran": "oat bran",
    "oat flour": "oat flour",
    "oatmeal": "oatmeal",
    "oats": "oats",
    "octopus": "octopus",
    "oil": "oil",
    "okra": "okra",
    "old bay seasoning": "old bay seasoning",
    "oleo": "oleo",
    "olive": "olive",
    "olive oil": "olive oil",
    "olive oil spread": "olive oil spread",
    "onion": "onion",
    "onion flake": "onion flake",
    "onion powder": "onion powder",
    "onion ring": "onion ring",
    "onion roll": "onion roll",
    "onion salt": "onion salt",
    "onion soup": "onion soup",
    "orange": "orange",
    "orange extract": "orange extract",
    "orange juice": "orange juice",
    "orange juice concentrate": "orange juice concentrate",
    "orange liqueur": "orange liqueur",
    "orange marmalade": "orange marmalade",
    "orange peel": "orange peel",
    "orange rind": "orange rind",
    "orange section": "orange section",
    "orange slice": "orange slice",
    "orange wedge": "orange wedge",
    "orange zest": "orange zest",
    "oregano": "oregano",
    "oreo cookie": "oreo cookie",
    "original": "original",
    "orzo": "orzo",
    "ouzo": "ouzo",
    "oyster": "oyster",
    "oyster cracker": "oyster cracker",
    "oyster sauce": "oyster sauce",
    "packed": "packed",
    "palm sugar": "palm sugar",
    "pan dripping": "pan dripping",
    "pan juice": "pan juice",
    "pancake": "pancake",
    "pancake batter": "pancake batter",
    "pancetta": "pancetta",
    "panko breadcrumb": "panko breadcrumb",
    "papaya": "papaya",
    "paper": "paper",
    "paper baking": "paper baking",
    "paper towel": "paper towel",
    "paprika": "paprika",
    "parchment paper": "parchment paper",
    "parmesan": "parmesan",
    "parmesan cheese": "parmesan cheese",
    "parmigiano": "parmigiano",
    "parmigiano reggiano cheese": "parmigiano reggiano cheese",
    "parsley": "parsley",
    "parsley flake": "parsley flake",
    "parsley sprig": "parsley sprig",
    "parsnip": "parsnip",
    "pasta": "pasta",
    "pasta sauce": "pasta sauce",
    "pasta shell": "pasta shell",
    "paste": "paste",
    "pastry crust": "pastry crust",
    "pastry dough": "pastry dough",
    "pastry flour": "pastry flour",
    "pastry shell": "pastry shell",
    "pate": "pate",
    "pea": "pea",
    "pea pod": "pea pod",
    "peach": "peach",
    "peach slice": "peach slice",
    "peanut": "peanut",
    "peanut butter": "peanut butter",
    "peanut butter chip": "peanut butter chip",
    "peanut oil": "peanut oil",
    "peanut sauce": "peanut sauce",
    "pear": "pear",
    "pear half": "pear half",
    "pearl": "pearl",
    "pearl barley": "pearl barley",
    "pearl onion": "pearl onion",
    "pecan": "pecan",
    "pecan half": "pecan half",
    "pecan piece": "pecan piece",
    "pectin": "pectin",
    "peel": "peel",
    "penne": "penne",
    "penne pasta": "penne pasta",
    "pepper": "pepper",
    "pepper ring": "pepper ring",
    "pepper sauce": "pepper sauce",
    "peppercorn": "peppercorn",
    "peppermint": "peppermint",
    "peppermint candy": "peppermint candy",
    "peppermint extract": "peppermint extract",
    "pepperoni": "pepperoni",
    "pepperoni slice": "pepperoni slice",
    "pesto sauce": "pesto sauce",
    "pheasant": "pheasant",
    "phyllo dough": "phyllo dough",
    "picante sauce": "picante sauce",
    "pickle": "pickle",
    "pickle juice": "pickle juice",
    "pickle relish": "pickle relish",
    "pickling spice": "pickling spice",
    "pico de gallo": "pico de gallo",
    "pie": "pie",
    "pie crust": "pie crust",
    "pie dough": "pie dough",
    "pie filling": "pie filling",
    "pie plate": "pie plate",
    "pie shell": "pie shell",
    "piece": "piece",
    "pimento": "pimento",
    "pimentos": "pimentos",
    "pimiento": "pimiento",
    "pine nut": "pine nut",
    "pineapple": "pineapple",
    "pineapple chunk": "pineapple chunk",
    "pineapple juice": "pineapple juice",
    "pineapple ring": "pineapple ring",
    "pineapple slice": "pineapple slice",
    "pineapple tidbit": "pineapple tidbit",
    "pinto bean": "pinto bean",
    "pistachio": "pistachio",
    "pistachio nut": "pistachio nut",
    "pita bread": "pita bread",
    "pita chip": "pita chip",
    "pita pocket": "pita pocket",
    "pizza crust": "pizza crust",
    "pizza dough": "pizza dough",
    "pizza sauce": "pizza sauce",
    "pizza topping": "pizza topping",
    "plain flour": "plain flour",
    "plain yogurt": "plain yogurt",
    "plantain": "plantain",
    "plastic": "",
    "plastic wrap": "",
    "plum": "plum",
    "plum sauce": "plum sauce",
    "plum tomato": "plum tomato",
    "poblano pepper": "poblano pepper",
    "polenta": "polenta",
    "pomegranate": "pomegranate",
    "pomegranate juice": "pomegranate juice",
    "pomegranate seed": "pomegranate seed",
    "popcorn": "popcorn",
    "popped corn": "popped corn",
    "popped popcorn": "popped popcorn",
    "poppy seed": "poppy seed",
    "pork": "pork",
    "pork chop": "pork chop",
    "pork fat": "pork fat",
    "pork hock": "pork hock",
    "pork loin": "pork loin",
    "pork rib": "pork rib",
    "pork roast": "pork roast",
    "pork shoulder": "pork shoulder",
    "pork steak": "pork steak",
    "pork tenderloin": "pork tenderloin",
    "port": "port",
    "port wine": "port wine",
    "pot roast": "pot roast",
    "pot sticker": "pot sticker",
    "potato": "potato",
    "potato chip": "potato chip",
    "potato flake": "potato flake",
    "potato flour": "potato flour",
    "potato peel": "potato peel",
    "potato salad": "potato salad",
    "potato starch": "potato starch",
    "potato water": "potato water",
    "poultry": "poultry",
    "poultry seasoning": "poultry seasoning",
    "powder": "powder",
    "powdered": "powdered",
    "powdered milk": "powdered milk",
    "powdered sugar": "powdered sugar",
    "praline": "praline",
    "prawn": "prawn",
    "prepared": "prepared",
    "prepared mustard": "prepared mustard",
    "preserves": "preserves",
    "pretzel": "pretzel",
    "pretzel stick": "pretzel stick",
    "prosciutto": "prosciutto",
    "protein powder": "protein powder",
    "provolone cheese": "provolone cheese",
    "prune": "prune",
    "pudding": "pudding",
    "puff pastry": "puff pastry",
    "puff pastry sheet": "puff pastry sheet",
    "pulp": "pulp",
    "pumpkin": "pumpkin",
    "pumpkin pie": "pumpkin pie",
    "pumpkin pie spice": "pumpkin pie spice",
    "pumpkin puree": "pumpkin puree",
    "pumpkin seed": "pumpkin seed",
    "puree": "puree",
    "purpose flour": "purpose flour",
    "quail": "quail",
    "quark": "quark",
    "queso fresco": "queso fresco",
    "quick": "quick",
    "quick oats": "quick oats",
    "quinoa": "quinoa",
    "rabbit": "rabbit",
    "radicchio": "radicchio",
    "radish": "radish",
    "ragu": "ragu",
    "raisin": "raisin",
    "raman noodle": "raman noodle",
    "ranch": "ranch",
    "ranch dip": "ranch dip",
    "ranch dressing": "ranch dressing",
    "raspberry": "raspberry",
    "raspberry jam": "raspberry jam",
    "raspberry sauce": "raspberry sauce",
    "ravioli": "ravioli",
    "raw chicken": "raw chicken",
    "raw sugar": "raw sugar",
    "red": "red",
    "red bean": "red bean",
    "red bell pepper": "red bell pepper",
    "red cabbage": "red cabbage",
    "red chile": "red chile",
    "red chili powder": "red chili powder",
    "red food coloring": "red food coloring",
    "red onion": "red onion",
    "red pepper": "red pepper",
    "red pepper flake": "red pepper flake",
    "red pepper sauce": "red pepper sauce",
    "red potato": "red potato",
    "red wine": "red wine",
    "red wine vinegar": "red wine vinegar",
    "refried bean": "refried bean",
    "relish": "relish",
    "remoulade sauce": "remoulade sauce",
    "reserved juice": "reserved juice",
    "rhubarb": "rhubarb",
    "rib": "rib",
    "ribbon": "ribbon",
    "rice": "rice",
    "rice flour": "rice flour",
    "rice krispie": "rice krispie",
    "rice milk": "rice milk",
    "rice noodle": "rice noodle",
    "rice paper": "rice paper",
    "rice pilaf": "rice pilaf",
    "rice vinegar": "rice vinegar",
    "rice wine": "rice wine",
    "rice wine vinegar": "rice wine vinegar",
    "ricotta": "ricotta",
    "ricotta cheese": "ricotta cheese",
    "rind": "rind",
    "ritz cracker": "ritz cracker",
    "roast": "roast",
    "roast beef": "roast beef",
    "roast pork": "roast pork",
    "roasted": "roasted",
    "roasted garlic": "roasted garlic",
    "roasted pepper": "roasted pepper",
    "roasted potato": "roasted potato",
    "roasted red pepper": "roasted red pepper",
    "rock salt": "rock salt",
    "rocket": "rocket",
    "roll": "roll",
    "rolled oats": "rolled oats",
    "rolls": "rolls",
    "roma tomato": "roma tomato",
    "romaine lettuce": "romaine lettuce",
    "romano": "romano",
    "romano cheese": "romano cheese",
    "roni": "roni",
    "rose": "rose",
    "rose water": "rose water",
    "rosemary": "rosemary",
    "rosemary sprig": "rosemary sprig",
    "rotel": "rotel",
    "rotel tomato": "rotel tomato",
    "rotini": "rotini",
    "rotis": "rotis",
    "round steak": "round steak",
    "roux": "roux",
    "rum": "rum",
    "rum extract": "rum extract",
    "rutabaga": "rutabaga",
    "rye bread": "rye bread",
    "rye flour": "rye flour",
    "saffron": "saffron",
    "saffron thread": "saffron thread",
    "sage": "sage",
    "sage leaves": "sage leaves",
    "sake": "sake",
    "salad": "salad",
    "salad dressing": "salad dressing",
    "salad green": "salad green",
    "salad leave": "salad leave",
    "salad oil": "salad oil",
    "salami": "salami",
    "salmon": "salmon",
    "salmon fillet": "salmon fillet",
    "salmon fillets": "salmon fillet",
    "salmon steak": "salmon steak",
    "salsa": "salsa",
    "salsa verde": "salsa verde",
    "salt": "salt",
    "salt pepper": "salt pepper",
    "salt pork": "salt pork",
    "salt water": "salt water",
    "saltine": "saltine",
    "saltine cracker": "saltine cracker",
    "salty": "salty",
    "sambal oelek": "sambal oelek",
    "sandwich": "sandwich",
    "satay sauce": "satay sauce",
    "sauce": "sauce",
    "sauerkraut": "sauerkraut",
    "sausage": "sausage",
    "sausage link": "sausage link",
    "sausage meat": "sausage meat",
    "savory": "savory",
    "sazon": "sazon",
    "scallion": "scallion",
    "scallop": "scallop",
    "scotch": "scotch",
    "sea salt": "sea salt",
    "seafood": "seafood",
    "seafood seasoning": "seafood seasoning",
    "season": "season",
    "season salt": "season salt",
    "seasoned bread crumb": "seasoned bread crumb",
    "seasoned flour": "seasoned flour",
    "seasoning": "seasoning",
    "seasoning salt": "seasoning salt",
    "seed": "seed",
    "seitan": "seitan",
    "self rising flour": "self rising flour",
    "semi sweet": "semi sweet",
    "semi sweet chocolate": "semi sweet chocolate",
    "semisweet chocolate": "semisweet chocolate",
    "semisweet chocolate chip": "semisweet chocolate chip",
    "semolina": "semolina",
    "serrano": "serrano",
    "serrano pepper": "serrano pepper",
    "serve": "serve",
    "sesame": "sesame",
    "sesame oil": "sesame oil",
    "sesame seed": "sesame seed",
    "shallot": "shallot",
    "shallot salt": "shallot salt",
    "shape": "shape",
    "sharp cheddar cheese": "sharp cheddar cheese",
    "shell": "shell",
    "sherbet": "sherbet",
    "sherry vinegar": "sherry vinegar",
    "shortbread": "shortbread",
    "shortening": "shortening",
    "shredded": "shredded",
    "shredded cheddar cheese": "shredded cheddar cheese",
    "shredded coconut": "shredded coconut",
    "shrimp": "shrimp",
    "sifted flour": "sifted flour",
    "simple syrup": "simple syrup",
    "simply": "simply",
    "sirloin": "sirloin",
    "skewer": "skewer",
    "skim milk": "skim milk",
    "skin": "skin",
    "skinless chicken breast": "skinless chicken breast",
    "sliced almond": "sliced almond",
    "sliced apple": "sliced apple",
    "sliced mushroom": "sliced mushroom",
    "sliced potato": "sliced potato",
    "slivered almond": "slivered almond",
    "small onion": "small onion",
    "smoked paprika": "smoked paprika",
    "smoked salmon": "smoked salmon",
    "smoked sausage": "smoked sausage",
    "snack": "snack",
    "snail": "snail",
    "snap pea": "snap pea",
    "snow pea": "snow pea",
    "soda": "soda",
    "soda water": "soda water",
    "soft": "soft",
    "sorbet": "sorbet",
    "soup": "soup",
    "sour": "sour",
    "sour cream": "sour cream",
    "sour milk": "sour milk",
    "sourdough bread": "sourdough bread",
    "sourdough starter": "sourdough starter",
    "soy sauce": "soy sauce",
    "soya sauce": "soya sauce",
    "soymilk": "soymilk",
    "spaghetti": "spaghetti",
    "spaghetti noodle": "spaghetti noodle",
    "spaghetti sauce": "spaghetti sauce",
    "spaghetti squash": "spaghetti squash",
    "spam": "spam",
    "spanish rice": "spanish rice",
    "spareribs": "spareribs",
    "sparkling water": "sparkling water",
    "spice": "spice",
    "spinach": "spinach",
    "spinach leaves": "spinach leaves",
    "split pea": "split pea",
    "sponge cake": "sponge cake",
    "spray bottle": "spray bottle",
    "spread": "spread",
    "spreadable": "spreadable",
    "spring": "spring",
    "spring onion": "spring onion",
    "spring roll": "spring roll",
    "spring roll wrapper": "spring roll wrapper",
    "sprite": "sprite",
    "squash": "squash",
    "squid": "squid",
    "star anise": "star anise",
    "starch": "starch",
    "starter": "starter",
    "steak": "steak",
    "steak sauce": "steak sauce",
    "steak seasoning": "steak seasoning",
    "steamed rice": "steamed rice",
    "stems": "stems",
    "stevia": "stevia",
    "stew meat": "stew meat",
    "stewed": "stewed",
    "stewed tomato": "stewed tomato",
    "stick": "stick",
    "stir fry": "stir fry",
    "stir fry beef": "stir fry beef",
    "stir fry sauce": "stir fry sauce",
    "stock": "stock",
    "stove": "stove",
    "strawberry": "strawberry",
    "strawberry jam": "strawberry jam",
    "strawberry puree": "strawberry puree",
    "strawberry sauce": "strawberry sauce",
    "strawberry slice": "strawberry slice",
    "string": "string",
    "string bean": "string bean",
    "stuffing": "stuffing",
    "style": "style",
    "suet": "suet",
    "sugar": "sugar",
    "sugar applesauce": "sugar applesauce",
    "sugar crystal": "sugar crystal",
    "sugar honey": "sugar honey",
    "sugar pumpkin": "sugar pumpkin",
    "sugar snap pea": "sugar snap pea",
    "sugar substitute": "sugar substitute",
    "sugar syrup": "sugar syrup",
    "sultanas": "sultanas",
    "sumac": "sumac",
    "sun dried tomato": "sun dried tomato",
    "sunflower oil": "sunflower oil",
    "sunflower seed": "sunflower seed",
    "superfine sugar": "superfine sugar",
    "sweet": "sweet",
    "sweet bread": "sweet bread",
    "sweet chili sauce": "sweet chili sauce",
    "sweet onion": "sweet onion",
    "sweet pepper": "sweet pepper",
    "sweet potato": "sweet potato",
    "sweet red pepper": "sweet red pepper",
    "sweetcorn": "sweetcorn",
    "sweetened": "sweetened",
    "sweetened condensed milk": "sweetened condensed milk",
    "sweetened whipped cream": "sweetened whipped cream",
    "swirl": "swirl",
    "swiss": "swiss",
    "swiss chard": "swiss chard",
    "swiss cheese": "swiss cheese",
    "swiss roll": "swiss roll",
    "swordfish": "swordfish",
    "syrup": "syrup",
    "tabasco sauce": "tabasco sauce",
    "taco sauce": "taco sauce",
    "taco seasoning": "taco seasoning",
    "taco shell": "taco shell",
    "tahini": "tahini",
    "tamale": "tamale",
    "tamari": "tamari",
    "tamarind paste": "tamarind paste",
    "tangerine": "tangerine",
    "tap water": "tap water",
    "tapenade": "tapenade",
    "tapioca": "tapioca",
    "tapioca flour": "tapioca flour",
    "tapioca starch": "tapioca starch",
    "taquito": "taquito",
    "tarragon": "tarragon",
    "tart shell": "tart shell",
    "tartar": "tartar",
    "tartar sauce": "tartar sauce",
    "tater tot": "tater tot",
    "tea": "tea",
    "tea bag": "tea bag",
    "tea leave": "tea leave",
    "tempeh": "tempeh",
    "tenderloin": "tenderloin",
    "tequila": "tequila",
    "teriyaki": "teriyaki",
    "teriyaki sauce": "teriyaki sauce",
    "thin": "thin",
    "thousand island dressing": "thousand island dressing",
    "thyme": "thyme",
    "thyme leaves": "thyme leaves",
    "tilapia fillet": "tilapia fillet",
    "toast": "toast",
    "toast point": "toast point",
    "toasted almond": "toasted almond",
    "toasted sesame seed": "toasted sesame seed",
    "toffee": "toffee",
    "tofu": "tofu",
    "tomatillo": "tomatillo",
    "tomatillos": "tomatillos",
    "tomato": "tomato",
    "tomato basil": "tomato basil",
    "tomato garlic": "tomato garlic",
    "tomato juice": "tomato juice",
    "tomato ketchup": "tomato ketchup",
    "tomato paste": "tomato paste",
    "tomato puree": "tomato puree",
    "tomato sauce": "tomato sauce",
    "tomato soup": "tomato soup",
    "toothpick": "",
    "tortellini": "tortellini",
    "tortilla": "tortilla",
    "tortilla chip": "tortilla chip",
    "tostada": "tostada",
    "trail": "trail",
    "triple sec": "triple sec",
    "trout": "trout",
    "truffle": "truffle",
    "truffle oil": "truffle oil",
    "tuna": "tuna",
    "tuna steak": "tuna steak",
    "turbinado sugar": "turbinado sugar",
    "turkey": "turkey",
    "turkey bacon": "turkey bacon",
    "turkey breast": "turkey breast",
    "turkey leg": "turkey leg",
    "turmeric": "turmeric",
    "turmeric powder": "turmeric powder",
    "turnip": "turnip",
    "tzatziki": "tzatziki",
    "unbaked pie crust": "unbaked pie crust",
    "unbaked pie shell": "unbaked pie shell",
    "unbuttered": "unbuttered",
    "uncooked rice": "uncooked rice",
    "unsalted": "unsalted",
    "unsalted butter": "unsalted butter",
    "unsweetened chocolate": "unsweetened chocolate",
    "valley": "",
    "vanilla": "vanilla",
    "vanilla bean": "vanilla bean",
    "vanilla chip": "vanilla chip",
    "vanilla essence": "vanilla essence",
    "vanilla extract": "vanilla extract",
    "vanilla frosting": "vanilla frosting",
    "vanilla ice cream": "vanilla ice cream",
    "vanilla pod": "vanilla pod",
    "vanilla pudding": "vanilla pudding",
    "vanilla sugar": "vanilla sugar",
    "vanilla wafer": "vanilla wafer",
    "vanilla yogurt": "vanilla yogurt",
    "veal": "veal",
    "veg": "",
    "vegemite": "vegemite",
    "vegetable": "vegetable",
    "vegetable broth": "vegetable broth",
    "vegetable juice": "vegetable juice",
    "vegetable oil": "vegetable oil",
    "vegetable shortening": "vegetable shortening",
    "vegetable soup": "vegetable soup",
    "vegetable stock": "vegetable stock",
    "velveeta": "velveeta",
    "velveeta cheese": "velveeta cheese",
    "venison": "venison",
    "vermicelli": "vermicelli",
    "vermouth": "vermouth",
    "vinaigrette": "vinaigrette",
    "vinaigrette dressing": "vinaigrette dressing",
    "vinegar": "vinegar",
    "virgin olive oil": "virgin olive oil",
    "vodka": "vodka",
    "wafer": "wafer",
    "waffle": "waffle",
    "walnut half": "walnut half",
    "walnut oil": "walnut oil",
    "walnut piece": "walnut piece",
    "walnuts": "walnuts",
    "warm water": "warm water",
    "wasabi": "wasabi",
    "water": "water",
    "water chestnut": "water chestnut",
    "watercress": "watercress",
    "watermelon": "watermelon",
    "wax paper": "wax paper",
    "wheat": "wheat",
    "wheat berry": "wheat berry",
    "wheat bran": "wheat bran",
    "wheat flour": "wheat flour",
    "wheat germ": "wheat germ",
    "whey": "whey",
    "whipped": "whipped",
    "whipped cream": "whipped cream",
    "whipping cream": "whipping cream",
    "whiskey": "whiskey",
    "white": "white",
    "white bean": "white bean",
    "white bread": "white bread",
    "white cake": "white cake",
    "white chocolate": "white chocolate",
    "white chocolate chip": "white chocolate chip",
    "white flour": "white flour",
    "white frosting": "white frosting",
    "white onion": "white onion",
    "white pepper": "white pepper",
    "white rice": "white rice",
    "white sauce": "white sauce",
    "white sugar": "white sugar",
    "white vinegar": "white vinegar",
    "white wine": "white wine",
    "white wine vinegar": "white wine vinegar",
    "whole": "whole",
    "whole almond": "whole almond",
    "whole chicken": "whole chicken",
    "whole clove": "whole clove",
    "whole milk": "whole milk",
    "whole tomato": "whole tomato",
    "whole wheat bread": "whole wheat bread",
    "whole wheat flour": "whole wheat flour",
    "wild": "wild",
    "wild rice": "wild rice",
    "wine": "wine",
    "wine vinegar": "wine vinegar",
    "wire rack": "",
    "wonton": "wonton",
    "wonton skin": "wonton skin",
    "wonton wrapper": "wonton wrapper",
    "wood chip": "",
    "wooden skewer": "",
    "wooden stick": "",
    "worcestershire sauce": "worcestershire sauce",
    "worchestershire sauce": "worchestershire sauce",
    "wrap": "wrap",
    "xanthan gum": "xanthan gum",
    "yam": "yam",
    "yeast": "yeast",
    "yellow": "yellow",
    "yellow bell pepper": "yellow bell pepper",
    "yellow cake": "yellow cake",
    "yellow mustard": "yellow mustard",
    "yellow onion": "yellow onion",
    "yellow pepper": "yellow pepper",
    "yellow rice": "yellow rice",
    "yellow squash": "yellow squash",
    "yoghurt": "yoghurt",
    "yogurt": "yogurt",
    "zest": "zest",
    "ziploc bag": "",
    "zucchini": "zucchini",
}
