ingredients_mappings = {
    "albacore tuna water": "albacore tuna water",
    "american cheese": "american cheese",
    "angel hair pasta": "pasta",
    "apple": "apple",
    "apple cider vinegar": "apple cider",
    "apple juice": "apple juice",
    "apple pie filling": "apple pie",
    "avocado": "avocado",
    "bacon": "bacon",
    "baking cocoa": "baking cocoa",
    "baking potato": "baking potato",
    "baking powder": "baking powder",
    "baking soda": "baking soda",
    "banana": "banana",
    "basil": "basil",
    "bay leaf": "bay leaf",
    "bean dip": "bean dip",
    "bean sprout": "bean sprout",
    "beef": "beef",
    "beef bouillon": "beef bouillon",
    "beef broth": "beef broth",
    "beef consomme": "beef broth",
    "beef rib": "beef rib",
    "beef steak": "beef steak",
    "beef stew meat": "beef stew",
    "beer": "beer",
    "bibb lettuce": "lettuce",
    "black bean": "black bean",
    "black cumin": "black cumin",
    "black olive": "black olive",
    "black pepper": "black pepper",
    "boiling potato": "boiling potato",
    "boiling water": "boiling water",
    "boneless chicken breast": "chicken breast",
    "bread": "bread",
    "breadcrumb": "breadcrumb",
    "brine": "brine",
    "broccoli stem": "broccoli",
    "broccoli": "broccoli",
    "broccoli floret": "broccoli",
    "broth": "broth",
    "brown sugar": "brown sugar",
    "buckwheat flour": "buckwheat flour",
    "burnet root": "burnet root",
    "butter": "butter",
    "butterscotch chip": "butterscotch chip",
    "button mushroom": "mushroom",
    "cabbage": "cabbage",
    "cake flour": "cake flour",
    "canola oil": "canola oil",
    "caper": "caper",
    "carrot": "carrot",
    "cauliflower": "cauliflower",
    "cayenne": "cayenne pepper",
    "cayenne pepper": "cayenne pepper",
    "celery": "celery",
    "celery seed": "celery seed",
    "cheddar cheese": "cheddar cheese",
    "cheddar cheese soup": "cheddar cheese soup",
    "cheese": "cheese",
    "chicken bouillon": "chicken broth",
    "chicken breast": "chicken breast",
    "chicken rice soup": "chicken rice soup",
    "chicken stock": "chicken broth",
    "chili garlic sauce": "chili garlic sauce",
    "chili powder": "chili powder",
    "chinese noodle": "noodle",
    "chives": "chives",
    "chocolate chip": "chocolate chip",
    "chocolate syrup": "chocolate syrup",
    "chunky salsa": "chunky salsa",
    "ciabatta": "ciabatta",
    "cider vinegar": "cider vinegar",
    "cilantro": "cilantro",
    "cinnamon": "cinnamon",
    "cinnamon oil": "cinnamon oil",
    "cinnamon stick": "cinnamon stick",
    "clove oil": "clove oil",
    "cloves": "cloves",
    "coarse salt": "coarse salt",
    "cocoa": "cocoa",
    "coconut": "coconut",
    "collard green": "collard green",
    "cooked chicken": "cooked chicken",
    "cookie": "cookie",
    "cooking oil": "oil",
    "corn": "corn",
    "cornbread mix": "cornbread mix",
    "cornmeal": "cornmeal",
    "cornstarch": "cornstarch",
    "cottage cheese": "cottage cheese",
    "cracked black pepper": "black pepper",
    "cracker": "cracker",
    "cream": "cream",
    "cream cheese": "cream cheese",
    "cream mushroom soup": "mushroom soup",
    "crouton": "crouton",
    "crushed pineapple": "crushed pineapple",
    "crushed tomato": "crushed tomato",
    "cucumber": "cucumber",
    "cumin": "cumin",
    "dark brown sugar": "brown sugar",
    "deli turkey": "slicked turkey",
    "desiccated coconut": "desiccated coconut",
    "diced pimento": "red bell pepper",
    "diced tomato": "diced tomato",
    "dill pickle": "pickle",
    "dill weed": "dill",
    "dried basil": "basil",
    "dried breadcrumb": "breadcrumb",
    "dried dill weed": "dill",
    "dried oregano": "oregano",
    "dried parsley": "parsley",
    "dried thyme": "thyme",
    "dry mustard": "mustard",
    "dry white wine": "white wine",
    "dry yeast": "yeast",
    "egg": "egg",
    "egg roll wrap": "egg roll wrap",
    "egg substitute": "egg substitute",
    "egg white": "egg white",
    "egg yolk": "egg yolk",
    "elbow macaroni": "elbow macaroni",
    "escarole": "escarole",
    "fat": "fat",
    "fat free mayonnaise": "fat free mayonnaise",
    "fennel seed": "fennel seed",
    "fettuccine pasta": "fettuccine pasta",
    "flat leaf parsley": "flat leaf parsley",
    "flour": "flour",
    "french bread": "french bread",
    "fresh basil": "fresh basil",
    "fresh breadcrumb": "breadcrumb",
    "fresh cilantro": "fresh cilantro",
    "fresh cilantro leave": "fresh cilantro",
    "fresh corn": "fresh corn",
    "fresh garlic": "fresh garlic",
    "fresh ginger": "fresh ginger",
    "fresh ground pepper": "ground pepper",
    "fresh herb": "fresh herb",
    "fresh lemon juice": "fresh lemon juice",
    "fresh parsley": "fresh parsley",
    "fresh spinach leave": "fresh spinach",
    "fresh tomato": "fresh tomato",
    "frozen chopped spinach": "frozen spinach",
    "frozen french fry": "frozen french fry",
    "frozen juice concentrate": "frozen juice concentrate",
    "frozen pea": "frozen pea",
    "frozen vegetable": "vegetable",
    "garbanzo bean": "garbanzo",
    "garlic": "garlic",
    "garlic powder": "garlic powder",
    "gelatin": "gelatin",
    "genoa salami": "salami",
    "gentian root": "gentian root",
    "ginger": "ginger",
    "granulated sugar": "granulated sugar",
    "great northern bean": "bean",
    "green apple": "green apple",
    "green bean": "green bean",
    "green grape": "green grape",
    "green olive": "green olive",
    "green onion": "green onion",
    "green pea": "green pea",
    "green pepper": "green pepper",
    "ground beef": "ground beef",
    "ground black pepper": "ground black pepper",
    "ground cayenne pepper": "ground cayenne pepper",
    "ground cinnamon": "ground cinnamon",
    "ground clove": "ground clove",
    "ground coriander": "ground coriander",
    "ground cumin": "ground cumin",
    "ground ginger": "ground ginger",
    "ground pepper": "ground pepper",
    "ground pork": "ground pork",
    "ground sirloin": "ground sirloin",
    "ground thyme": "ground thyme",
    "ground turmeric": "ground turmeric",
    "ground venison": "ground venison",
    "half half": "",
    "ham": "ham",
    "ham hock": "ham",
    "hamburger bun": "hamburger bun",
    "hass avocado": "avocado",
    "heavy cream": "heavy cream",
    "herb": "herb",
    "honey": "honey",
    "hot chili pepper": "hot chili pepper",
    "hot sauce": "hot sauce",
    "hot water": "hot water",
    "iceberg lettuce": "lettuce",
    "icing sugar": "icing sugar",
    "instant vanilla pudding": "instant vanilla",
    "italian sausage": "italian sausage",
    "italian seasoning": "italian seasoning",
    "jalapenos": "jalapeno",
    "jalapeno": "jalapeno",
    "kalamata olive": "olive",
    "ketchup": "ketchup",
    "kidney bean": "bean",
    "lasagna noodle": "lasagna",
    "lean ground beef": "ground beef",
    "lean pork chop": "pork chop",
    "lemon": "lemon",
    "lemon juice": "lemon juice",
    "lettuce": "lettuce",
    "light olive oil": "olive oil",
    "lime juice": "lime juice",
    "liquid smoke": "liquid smoke",
    "low fat buttermilk": "low fat buttermilk",
    "low fat milk": "low fat milk",
    "margarine": "margarine",
    "mayonnaise": "mayonnaise",
    "mexican seasoning": "mexican seasoning",
    "milk": "milk",
    "miniature peppermint patty": "peppermint patty",
    "mirin": "mirin",
    "mix": "",
    "mixed spice": "mixed spice",
    "molasses": "molasses",
    "monterey jack cheese": "jack cheese",
    "mozzarella cheese": "mozzarella cheese",
    "mushroom piece": "mushroom",
    "mustard": "mustard",
    "mustard powder": "mustard",
    "new potato": "potato",
    "nut": "nut",
    "nutmeg": "nutmeg",
    "oil": "oil",
    "olive oil": "olive oil",
    "onion": "onion",
    "onion powder": "onion powder",
    "orange": "orange",
    "orange juice": "orange juice",
    "orange rind": "orange rind",
    "oregano": "oregano",
    "oregano leave": "oregano",
    "oreo cookie crumbs": "cookie crumbs",
    "original sauce": "sauce",
    "paprika": "paprika",
    "parmesan cheese": "parmesan cheese",
    "parsley": "parsley",
    "parsley flake": "parsley",
    "parsley sprig": "parsley",
    "pasta": "pasta",
    "peanut": "peanut",
    "peanut oil": "peanut oil",
    "pear": "pear",
    "pecan": "pecan",
    "penne pasta": "penne pasta",
    "pepper": "pepper",
    "peppercorn": "pepper",
    "pepperoni": "pepperoni",
    "philadelphia cream cheese": "cream cheese",
    "picante sauce": "chili sauce",
    "plain yogurt": "yogurt",
    "pork sparerib": "pork rib",
    "potato": "potato",
    "poultry seasoning": "poultry seasoning",
    "powdered sugar": "powdered sugar",
    "prego spaghetti sauce": "prego sauce",
    "prepared horseradish": "horseradish",
    "prepared mustard": "mustard",
    "prepared pizza crust": "pizza crust",
    "prepared yellow mustard": "mustard",
    "provolone cheese": "provolone cheese",
    "purpose flour": "flour",
    "raisin": "raisin",
    "red bell pepper": "red bell pepper",
    "red chile": "red chili",
    "red chili pepper": "red chili",
    "red cinnamon candy": "cinnamon candy",
    "red pepper flake": "red pepper",
    "red potato": "red potato",
    "red wine vinegar": "red wine",
    "rice vinegar": "rice vinegar",
    "ricotta cheese": "ricotta cheese",
    "ripe olive": "ripe olive",
    "roll": "roll",
    "rolled oat": "rolled oat",
    "rosemary": "rosemary",
    "rotel tomato": "rotel tomato",
    "rubbed sage": "rubbed sage",
    "sage": "sage",
    "salmon": "salmon",
    "salsa": "salsa",
    "salt": "salt",
    "salt added ketchup": "ketchup",
    "salt pepper": "pepper",
    "salted peanut": "salted peanut",
    "sambal oelek": "sambal oelek",
    "sandwich bun": "bun",
    "sausage patty": "sausage patty",
    "scallion": "scallion",
    "scullcap herb": "scullcap herb",
    "seasoning": "seasoning",
    "seasoning salt": "seasoning",
    "sesame oil": "sesame oil",
    "sesame seed": "sesame seed",
    "shallot": "shallot",
    "sharp cheddar cheese": "cheddar cheese",
    "shortening": "shortening",
    "sliced mushroom": "sliced mushroom",
    "sliced ripe olive": "sliced ripe olive",
    "smoked chicken": "smoked chicken",
    "soft breadcrumb": "breadcrumb",
    "soft silken tofu": "soft tofu",
    "sorghum": "sorghum",
    "sour cream": "sour cream",
    "soy sauce": "soy sauce",
    "spearmint": "spearmint",
    "spice": "spice",
    "spicy mustard": "spicy mustard",
    "spinach": "spinach",
    "spreadable": "",
    "stewed tomato": "stewed tomato",
    "stir fry vegetable": "stir fry vegetable",
    "strawberry": "strawberry",
    "strawberry ice cream": "strawberry ice cream",
    "sugar": "sugar",
    "sugar substitute": "sugar substitute",
    "sweet butter": "sweet butter",
    "sweet corn": "sweet corn",
    "sweet onion": "sweet onion",
    "sweet pepper": "sweet pepper",
    "sweetened condensed milk": "condensed milk",
    "swiss cheese": "swiss cheese",
    "tabasco sauce": "tabasco sauce",
    "taco sauce": "taco sauce",
    "taco seasoning": "taco seasoning",
    "tarragon": "tarragon",
    "tempeh": "tempeh",
    "thyme": "thyme",
    "toasted almond": "toasted almond",
    "toasted sesame oil": "toasted sesame oil",
    "toasted sesame seed": "toasted sesame seed",
    "toasted wheat germ": "toasted wheat germ",
    "tomato juice": "tomato juice",
    "tomato paste": "tomato paste",
    "tomato puree": "tomato puree",
    "tomato sauce": "tomato sauce",
    "tomato soup": "tomato soup",
    "tomato": "tomato",
    "unflavored gelatin": "gelatin",
    "unsalted butter": "unsalted butter",
    "unsweetened chocolate square": "unsweetened chocolate",
    "unsweetened cocoa": "unsweetened cocoa",
    "vanilla": "vanilla",
    "vanilla extract": "vanilla extract",
    "vanilla ice cream": "vanilla ice cream",
    "vanilla wafer": "vanilla wafer",
    "veal roast": "veal roast",
    "vegetable bouillon": "vegetable broth",
    "vegetable oil": "vegetable oil",
    "vegetable shortening": "vegetable oil",
    "vegetable stock": "vegetable broth",
    "vegetarian ground beef": "vegetarian ground beef",
    "vermicelli": "vermicelli pasta",
    "walnut": "walnut",
    "water": "water",
    "water chestnut": "water chestnut",
    "wax bean": "wax bean",
    "whipped cream": "whipped cream",
    "whipping cream": "whipped cream",
    "whiskey": "whiskey",
    "white bread": "white bread",
    "white kidney bean": "white bean",
    "white onion": "white onion",
    "white pepper": "white pepper",
    "white sugar": "white sugar",
    "white vinegar": "white vinegar",
    "white wine": "white wine",
    "white wine vinegar": "white wine",
    "whole green chilie": "whole green chili",
    "whole kernel corn": "whole kernel corn",
    "whole tomato": "tomato",
    "winter squash": "winter squash",
    "wood bethony": "wood bethony",
    "worcestershire sauce": "worcestershire sauce",
    "yam": "yam",
    "yellow bell pepper": "yellow bell pepper",
    "yellow cake mix": "cake mix",
    "yellow onion": "yellow onion",
    "yogurt": "yogurt",
    "zucchini": "zucchini",
}
