wine_terms_mappings = {
    "abrasive": ("abrasive", "nonaroma", "bitter"),
    "acacia": ("acacia", "aroma", "aroma"),
    "acid driven": ("acid driven", "nonaroma", "acid"),
    "acid": ("acid", "nonaroma", "acid"),
    "aggressive": ("aggressive", "nonaroma", "acid"),
    "airy": ("airy", "nonaroma", "weight"),
    "allspice": ("allspice", "aroma", "aroma"),
    "almond": ("almond", "aroma", "aroma"),
    "alpine herbs": ("alpine herbs", "aroma", "aroma"),
    "american oak": ("american oak", "aroma", "aroma"),
    "angular": ("angular", "nonaroma", "bitter"),
    "anise": ("anise", "aroma", "aroma"),
    "apple": ("apple", "aroma", "aroma"),
    "apple blossom": ("apple blossom", "aroma", "aroma"),
    "apple pie": ("apple pie", "aroma", "aroma"),
    "apple sauce": ("apple sauce", "aroma", "aroma"),
    "apricot": ("apricot", "aroma", "aroma"),
    "ash": ("ash", "aroma", "aroma"),
    "asian spice": ("asian spice", "aroma", "aroma"),
    "asparagus": ("asparagus", "aroma", "aroma"),
    "asphalt": ("asphalt", "aroma", "aroma"),
    "assertive": ("assertive", "nonaroma", "acid"),
    "astringent": ("astringent", "nonaroma", "bitter"),
    "austere": ("austere", "nonaroma", "bitter"),
    "bacon": ("bacon", "aroma", "aroma"),
    "baked": ("baked", "nonaroma", "coolness"),
    "baked apple": ("baked apple", "aroma", "aroma"),
    "baked bread": ("baked bread", "aroma", "aroma"),
    "bread": ("bread", "nonaroma", "weight"),
    "baking spices": ("baking spices", "aroma", "aroma"),
    "balsamic": ("balsamic", "nonaroma", "aroma"),
    "banana": ("banana", "aroma", "aroma"),
    "band-aid": ("band-aid", "aroma", "aroma"),
    "barbecue": ("barbecue", "aroma", "aroma"),
    "bark": ("bark", "aroma", "aroma"),
    "barnyard": ("barnyard", "aroma", "aroma"),
    "basil": ("basil", "aroma", "aroma"),
    "bay leaf": ("bay leaf", "aroma", "aroma"),
    "beef": ("beef", "aroma", "aroma"),
    "beef jerky": ("beef jerky", "aroma", "aroma"),
    "beefy": ("beefy", "nonaroma", "bitter"),
    "beeswax": ("beeswax", "aroma", "aroma"),
    "beet": ("beet", "aroma", "aroma"),
    "beetroot": ("beetroot", "aroma", "aroma"),
    "bell pepper": ("bell pepper", "aroma", "aroma"),
    "bergamot": ("bergamot", "aroma", "aroma"),
    "berry": ("berry", "aroma", "aroma"),
    "big-boned": ("big-boned", "nonaroma", "bitter"),
    "bite": ("bite", "nonaroma", "acid"),
    "bitter": ("bitter", "nonaroma", "bitter"),
    "bitter almond": ("bitter almond", "aroma", "aroma"),
    "bittersweet": ("bittersweet", "nonaroma", "bitter"),
    "black cherry": ("black cherry", "aroma", "aroma"),
    "black currant": ("black currant", "aroma", "aroma"),
    "black fruit": ("black fruit", "aroma", "aroma"),
    "black pepper": ("black pepper", "aroma", "piquant"),
    "black tea": ("black tea", "aroma", "aroma"),
    "blackberry": ("blackberry", "aroma", "aroma"),
    "blackberry jam": ("blackberry jam", "aroma", "aroma"),
    "blackberry-cassis": ("blackberry-cassis", "aroma", "aroma"),
    "blackcurrant": ("blackcurrant", "aroma", "aroma"),
    "bland": ("bland", "nonaroma", "aroma"),
    "blood orange": ("blood orange", "aroma", "aroma"),
    "blossom": ("blossom", "aroma", "aroma"),
    "blue": ("blue", "nonaroma", "aroma"),
    "blue black": ("blue black", "nonaroma", "aroma"),
    "blue flower": ("blue flower", "aroma", "aroma"),
    "blue fruit": ("blue fruit", "aroma", "aroma"),
    "blueberry": ("blueberry", "aroma", "aroma"),
    "blueberry pie": ("blueberry pie", "aroma", "aroma"),
    "bold": ("bold", "nonaroma", "weight"),
    "bone dry": ("bone dry", "nonaroma", "sweet"),
    "botrytis": ("botrytis", "aroma", "aroma"),
    "boysenberry": ("boysenberry", "aroma", "aroma"),
    "bramble": ("bramble", "aroma", "aroma"),
    "brawny": ("brawny", "nonaroma", "bitter"),
    "bread": ("bread", "aroma", "aroma"),
    "bread crust": ("bread crust", "aroma", "aroma"),
    "brick": ("brick", "nonaroma", "aroma"),
    "bright": ("bright", "nonaroma", "acid"),
    "brilliant": ("brilliant", "nonaroma", "aroma"),
    "brine": ("brine", "aroma", "salt"),
    "brioche": ("brioche", "aroma", "aroma"),
    "brisk": ("brisk", "nonaroma", "acid"),
    "brown": ("brown", "nonaroma", "aroma"),
    "brown butter": ("brown butter", "aroma", "aroma"),
    "brown spice": ("brown spice", "aroma", "aroma"),
    "brown sugar": ("brown sugar", "aroma", "aroma"),
    "bubble gum": ("bubble gum", "aroma", "aroma"),
    "bubble gum": ("bubble gum", "aroma", "aroma"),
    "bulky": ("bulky", "nonaroma", "bitter"),
    "bullish": ("bullish", "nonaroma", "weight"),
    "buoyant": ("buoyant", "nonaroma", "acid"),
    "burnt": ("burnt", "aroma", "aroma"),
    "burnt toast": ("burnt toast", "aroma", "aroma"),
    "butter": ("butter", "aroma", "fat"),
    "butter nut": ("butter nut", "aroma", "aroma"),
    "butter popcorn": ("butter popcorn", "aroma", "aroma"),
    "buttercream": ("buttercream", "aroma", "aroma"),
    "butterscotch": ("butterscotch", "aroma", "aroma"),
    "buttery toast": ("buttery toast", "aroma", "aroma"),
    "cake": ("cake", "aroma", "fat"),
    "cake spice": ("cake spice", "aroma", "aroma"),
    "campfire": ("campfire", "aroma", "aroma"),
    "camphor": ("camphor", "aroma", "aroma"),
    "candle wax": ("candle wax", "aroma", "aroma"),
    "candy": ("candy", "aroma", "aroma"),
    "caramel": ("caramel", "aroma", "aroma"),
    "cardamom": ("cardamom", "aroma", "aroma"),
    "carob": ("carob", "aroma", "aroma"),
    "cashew": ("cashew", "aroma", "aroma"),
    "cassis": ("cassis", "aroma", "aroma"),
    "cataloupe": ("cataloupe", "aroma", "aroma"),
    "cedar": ("cedar", "aroma", "aroma"),
    "celery": ("celery", "aroma", "aroma"),
    "cement": ("cement", "aroma", "aroma"),
    "chalk": ("chalk", "aroma", "aroma"),
    "chamomile": ("chamomile", "aroma", "aroma"),
    "charcoal": ("charcoal", "aroma", "aroma"),
    "charred wood": ("charred wood", "aroma", "aroma"),
    "cheese": ("cheese", "aroma", "aroma"),
    "chemical": ("chemical", "aroma", "aroma"),
    "cherry": ("cherry", "aroma", "aroma"),
    "cherry liqueur": ("cherry liqueur", "aroma", "aroma"),
    "cherry pie": ("cherry pie", "aroma", "aroma"),
    "chocolate": ("chocolate", "aroma", "aroma"),
    "choppy": ("choppy", "nonaroma", "bitter"),
    "chunky": ("chunky", "nonaroma", "weight"),
    "cider": ("cider", "aroma", "aroma"),
    "cigar": ("cigar", "aroma", "aroma"),
    "cigar box": ("cigar box", "aroma", "aroma"),
    "cinnamon": ("cinnamon", "aroma", "aroma"),
    "citrus": ("citrus", "aroma", "aroma"),
    "citrus acid": ("citrus acid", "nonaroma", "acid"),
    "citrus peel": ("citrus peel", "aroma", "aroma"),
    "citrus pith": ("citrus pith", "aroma", "aroma"),
    "clampy": ("clampy", "nonaroma", "weight"),
    "classy": ("classy", "nonaroma", "bitter"),
    "clay": ("clay", "aroma", "aroma"),
    "clean": ("clean", "nonaroma", "acid"),
    "close-grained tannin": ("close-grained tannin", "nonaroma", "bitter"),
    "closed": ("closed", "nonaroma", "bitter"),
    "clove": ("clove", "aroma", "aroma"),
    "clove cinnamon": ("clove cinnamon", "aroma", "aroma"),
    "cloying": ("cloying", "nonaroma", "sweet"),
    "coarse": ("coarse", "nonaroma", "bitter"),
    "cocoa": ("cocoa", "aroma", "aroma"),
    "coconut": ("coconut", "aroma", "aroma"),
    "coffee": ("coffee", "aroma", "aroma"),
    "cola": ("cola", "aroma", "aroma"),
    "complex": ("complex", "nonaroma", "aroma"),
    "complicated": ("complicated", "nonaroma", "aroma"),
    "compost": ("compost", "aroma", "aroma"),
    "compote": ("compote", "aroma", "aroma"),
    "concentrated": ("concentrated", "nonaroma", "aroma"),
    "concrete": ("concrete", "aroma", "aroma"),
    "cooked": ("cooked", "aroma", "aroma"),
    "cooked spice": ("cooked spice", "aroma", "aroma"),
    "cookie": ("cookie", "aroma", "aroma"),
    "corn": ("corn", "aroma", "aroma"),
    "cotton candy": ("cotton candy", "aroma", "aroma"),
    "cracker": ("cracker", "aroma", "aroma"),
    "cranberry": ("cranberry", "aroma", "aroma"),
    "cranberry pomegranate": ("cranberry pomegranate", "aroma", "aroma"),
    "cream": ("cream", "aroma", "fat"),
    "creamy": ("creamy", "aroma", "fat"),
    "crisp": ("crisp", "nonaroma", "acid"),
    "crunchy": ("crunchy", "nonaroma", "acid"),
    "crème brulee": ("crème brulee", "aroma", "aroma"),
    "cucumber": ("cucumber", "aroma", "aroma"),
    "cured meat": ("cured meat", "aroma", "aroma"),
    "currant": ("currant", "aroma", "aroma"),
    "custard": ("custard", "aroma", "aroma"),
    "cut grass": ("cut grass", "aroma", "aroma"),
    "dainty": ("dainty", "nonaroma", "weight"),
    "dark": ("dark", "nonaroma", "aroma"),
    "dark berry": ("dark berry", "aroma", "aroma"),
    "dark chocolate": ("dark chocolate", "aroma", "aroma"),
    "dark fruit": ("dark fruit", "aroma", "aroma"),
    "deep color": ("deep color", "nonaroma", "aroma"),
    "dense": ("dense", "nonaroma", "aroma"),
    "depth": ("depth", "nonaroma", "aroma"),
    "diesel": ("diesel", "aroma", "aroma"),
    "dill": ("dill", "aroma", "bitter"),
    "diluted": ("diluted", "nonaroma", "aroma"),
    "dr pepper": ("dr pepper", "aroma", "aroma"),
    "dried herb": ("dried herb", "aroma", "aroma"),
    "dry": ("dry", "nonaroma", "sweet"),
    "dull": ("dull", "nonaroma", "aroma"),
    "dust": ("dust", "aroma", "aroma"),
    "earth": ("earth", "aroma", "aroma"),
    "earthy": ("earthy", "aroma", "aroma"),
    "easy": ("easy", "nonaroma", "aroma"),
    "edgy": ("edgy", "nonaroma", "acid"),
    "effervescent": ("effervescent", "nonaroma", "aroma"),
    "elderberry": ("elderberry", "aroma", "aroma"),
    "elderflower": ("elderflower", "aroma", "aroma"),
    "elegant": ("elegant", "nonaroma", "weight"),
    "espresso": ("espresso", "aroma", "aroma"),
    "eucalyptus": ("eucalyptus", "aroma", "aroma"),
    "expansive": ("expansive", "nonaroma", "aroma"),
    "extracted": ("extracted", "nonaroma", "weight"),
    "exuberant": ("exuberant", "nonaroma", "acid"),
    "fat": ("fat", "nonaroma", "aroma"),
    "feminine": ("feminine", "nonaroma", "sweet"),
    "fennel": ("fennel", "aroma", "aroma"),
    "feral": ("feral", "aroma", "aroma"),
    "fig": ("fig", "aroma", "aroma"),
    "finegrained tannin": ("finegrained tannin", "nonaroma", "bitter"),
    "finessed": ("finessed", "nonaroma", "aroma"),
    "firm": ("firm", "nonaroma", "bitter"),
    "fizz": ("fizz", "nonaroma", "aroma"),
    "flabby": ("flabby", "nonaroma", "acid"),
    "flashy": ("flashy", "nonaroma", "acid"),
    "flat": ("flat", "nonaroma", "acid"),
    "fleeting tannin": ("fleeting tannin", "nonaroma", "bitter"),
    "fleshy": ("fleshy", "nonaroma", "bitter"),
    "flint": ("flint", "aroma", "aroma"),
    "flower": ("flower", "aroma", "aroma"),
    "foamy": ("foamy", "nonaroma", "aroma"),
    "forest floor": ("forest floor", "aroma", "aroma"),
    "foxy": ("foxy", "aroma", "aroma"),
    "french oak": ("french oak", "aroma", "aroma"),
    "fresh": ("fresh", "nonaroma", "acid"),
    "frothy": ("frothy", "nonaroma", "aroma"),
    "fruit": ("fruit", "aroma", "aroma"),
    "fruit-forward": ("fruit-forward", "aroma", "aroma"),
    "fruity": ("fruity", "aroma", "aroma"),
    "fudge": ("fudge", "aroma", "aroma"),
    "full bodied": ("full bodied", "nonaroma", "weight"),
    "funky": ("funky", "aroma", "aroma"),
    "game": ("game", "aroma", "aroma"),
    "ginger": ("ginger", "aroma", "bitter"),
    "gingerbread": ("gingerbread", "aroma", "aroma"),
    "gold": ("gold", "nonaroma", "aroma"),
    "gooseberry": ("gooseberry", "aroma", "aroma"),
    "grabby": ("grabby", "nonaroma", "bitter"),
    "graham cracker": ("graham cracker", "aroma", "aroma"),
    "grain": ("grain", "aroma", "aroma"),
    "grainy": ("grainy", "nonaroma", "bitter"),
    "granite": ("granite", "aroma", "aroma"),
    "grapefruit": ("grapefruit", "aroma", "aroma"),
    "grapefruit peel": ("grapefruit peel", "aroma", "aroma"),
    "grapefruit pith": ("grapefruit pith", "aroma", "aroma"),
    "grapey": ("grapey", "aroma", "aroma"),
    "graphite": ("graphite", "aroma", "aroma"),
    "grass": ("grass", "aroma", "aroma"),
    "gravel": ("gravel", "aroma", "aroma"),
    "green": ("green", "nonaroma", "aroma"),
    "green banana": ("green banana", "aroma", "aroma"),
    "green bean": ("green bean", "aroma", "aroma"),
    "green fruit": ("green fruit", "aroma", "aroma"),
    "green pepper": ("green pepper", "aroma", "piquant"),
    "grilled herbs": ("grilled herbs", "aroma", "aroma"),
    "grilled meat": ("grilled meat", "aroma", "aroma"),
    "grilled peach": ("grilled peach", "aroma", "aroma"),
    "gripping": ("gripping", "nonaroma", "bitter"),
    "gripping tannin": ("gripping tannin", "nonaroma", "bitter"),
    "grippy": ("grippy", "nonaroma", "bitter"),
    "gritty": ("gritty", "nonaroma", "bitter"),
    "guava": ("guava", "aroma", "aroma"),
    "gummy": ("gummy", "aroma", "aroma"),
    "ham": ("ham", "aroma", "aroma"),
    "hard": ("hard", "nonaroma", "bitter"),
    "hay": ("hay", "aroma", "aroma"),
    "hazelnut": ("hazelnut", "aroma", "aroma"),
    "heady": ("heady", "nonaroma", "coolness"),
    "hearty": ("hearty", "nonaroma", "weight"),
    "heavy": ("heavy", "nonaroma", "weight"),
    "herb": ("herb", "aroma", "aroma"),
    "herbacious": ("herbacious", "aroma", "aroma"),
    "herbs": ("herbs", "aroma", "aroma"),
    "hibiscus": ("hibiscus", "aroma", "aroma"),
    "hickory": ("hickory", "aroma", "aroma"),
    "hickory smoke": ("hickory smoke", "aroma", "aroma"),
    "high acid": ("high acid", "nonaroma", "acid"),
    "high alcohol": ("high alcohol", "nonaroma", "coolness"),
    "high tannin": ("high tannin", "nonaroma", "bitter"),
    "hollow": ("hollow", "nonaroma", "aroma"),
    "honey": ("honey", "aroma", "sweet"),
    "honeycomb": ("honeycomb", "aroma", "aroma"),
    "honeydew": ("honeydew", "aroma", "aroma"),
    "honeysuckle": ("honeysuckle", "aroma", "aroma"),
    "horsey": ("horsey", "aroma", "aroma"),
    "hot": ("hot", "nonaroma", "coolness"),
    "huckleberry": ("huckleberry", "aroma", "aroma"),
    "incense": ("incense", "aroma", "aroma"),
    "indian spice": ("indian spice", "aroma", "aroma"),
    "inky": ("inky", "aroma", "aroma"),
    "iodine": ("iodine", "aroma", "salt"),
    "iron": ("iron", "aroma", "aroma"),
    "jagged": ("jagged", "nonaroma", "bitter"),
    "jalapeno": ("jalapeno", "aroma", "aroma"),
    "jam": ("jam", "aroma", "aroma"),
    "jasmine": ("jasmine", "aroma", "aroma"),
    "jelly": ("jelly", "aroma", "aroma"),
    "juicy": ("juicy", "aroma", "aroma"),
    "juniper": ("juniper", "aroma", "aroma"),
    "kirsch": ("kirsch", "aroma", "aroma"),
    "kiwi": ("kiwi", "aroma", "aroma"),
    "kumquat": ("kumquat", "aroma", "aroma"),
    "lactic": ("lactic", "aroma", "aroma"),
    "lanolin": ("lanolin", "aroma", "aroma"),
    "latex": ("latex", "aroma", "aroma"),
    "lavender": ("lavender", "aroma", "aroma"),
    "lavish": ("lavish", "nonaroma", "aroma"),
    "leafy": ("leafy", "aroma", "aroma"),
    "lean": ("lean", "nonaroma", "weight"),
    "leather": ("leather", "aroma", "aroma"),
    "lees": ("lees", "aroma", "aroma"),
    "lemon": ("lemon", "aroma", "aroma"),
    "lemon juice": ("lemon juice", "aroma", "aroma"),
    "lemon blossom": ("lemon blossom", "aroma", "aroma"),
    "lemon curd": ("lemon curd", "aroma", "aroma"),
    "lemon custard": ("lemon custard", "aroma", "aroma"),
    "lemon drop": ("lemon drop", "aroma", "aroma"),
    "lemon meringue": ("lemon meringue", "aroma", "aroma"),
    "lemon peel": ("lemon peel", "aroma", "aroma"),
    "lemon pith": ("lemon pith", "aroma", "aroma"),
    "lemon verbena": ("lemon verbena", "aroma", "aroma"),
    "lemongrass": ("lemongrass", "aroma", "aroma"),
    "length": ("length", "nonaroma", "aroma"),
    "lengthy": ("lengthy", "nonaroma", "aroma"),
    "lettuce": ("lettuce", "aroma", "aroma"),
    "licorice": ("licorice", "aroma", "aroma"),
    "light": ("light", "nonaroma", "weight"),
    "light bodied": ("light bodied", "nonaroma", "weight"),
    "light color": ("light color", "nonaroma", "aroma"),
    "lilac": ("lilac", "aroma", "aroma"),
    "lime": ("lime", "aroma", "aroma"),
    "lime peel": ("lime peel", "aroma", "aroma"),
    "lime pith": ("lime pith", "aroma", "aroma"),
    "limestone": ("limestone", "aroma", "aroma"),
    "linear": ("linear", "nonaroma", "aroma"),
    "loamy": ("loamy", "aroma", "aroma"),
    "low acid": ("low acid", "nonaroma", "acid"),
    "low alcohol": ("low alcohol", "nonaroma", "coolness"),
    "low complexity": ("low complexity", "nonaroma", "aroma"),
    "luminous": ("luminous", "nonaroma", "aroma"),
    "lush": ("lush", "nonaroma", "weight"),
    "luxurious": ("luxurious", "nonaroma", "weight"),
    "lychee": ("lychee", "aroma", "aroma"),
    "mace": ("mace", "aroma", "aroma"),
    "mandarin": ("mandarin", "aroma", "aroma"),
    "mango": ("mango", "nonaroma", "sweet"),
    "maple": ("maple", "aroma", "aroma"),
    "maple syrup": ("maple syrup", "aroma", "aroma"),
    "marjoram": ("marjoram", "aroma", "aroma"),
    "marmalade": ("marmalade", "aroma", "aroma"),
    "marshmallow": ("marshmallow", "aroma", "aroma"),
    "masculine": ("masculine", "nonaroma", "bitter"),
    "mass": ("mass", "nonaroma", "weight"),
    "matchstick": ("matchstick", "aroma", "aroma"),
    "mealy": ("mealy", "nonaroma", "acid"),
    "meat": ("meat", "aroma", "aroma"),
    "meaty": ("meaty", "nonaroma", "fat"),
    "medicinal": ("medicinal", "aroma", "aroma"),
    "meditteranean herbs": ("meditteranean herbs", "aroma", "aroma"),
    "medium bodied": ("medium bodied", "nonaroma", "weight"),
    "medium length finish": ("medium length finish", "nonaroma", "aroma"),
    "medium sweet": ("medium sweet", "nonaroma", "sweet"),
    "medium tannin": ("medium tannin", "nonaroma", "bitter"),
    "mellow": ("mellow", "nonaroma", "aroma"),
    "melon": ("melon", "aroma", "aroma"),
    "melon rind": ("melon rind", "aroma", "aroma"),
    "melted butter": ("melted butter", "aroma", "aroma"),
    "menthol": ("menthol", "aroma", "aroma"),
    "metal": ("metal", "aroma", "aroma"),
    "mild bitterness": ("mild bitterness", "nonaroma", "bitter"),
    "milk chocolate": ("milk chocolate", "aroma", "aroma"),
    "milk": ("milk", "nonaroma", "weight"),
    "mineral": ("mineral", "aroma", "aroma"),
    "minerality": ("minerality", "aroma", "aroma"),
    "mint": ("mint", "aroma", "aroma"),
    "modest": ("modest", "nonaroma", "aroma"),
    "moist earth": ("moist earth", "aroma", "aroma"),
    "molasses": ("molasses", "aroma", "aroma"),
    "moss": ("moss", "aroma", "aroma"),
    "mousse": ("mousse", "nonaroma", "aroma"),
    "mulberry": ("mulberry", "aroma", "aroma"),
    "mulch": ("mulch", "aroma", "aroma"),
    "murky": ("murky", "nonaroma", "aroma"),
    "muscular": ("muscular", "nonaroma", "bitter"),
    "mushroom": ("mushroom", "aroma", "aroma"),
    "musky": ("musky", "aroma", "aroma"),
    "mustard": ("mustard", "aroma", "aroma"),
    "nectar": ("nectar", "aroma", "aroma"),
    "nectarine": ("nectarine", "aroma", "aroma"),
    "nervy": ("nervy", "nonaroma", "acid"),
    "nettle": ("nettle", "aroma", "aroma"),
    "neutral oak": ("neutral oak", "aroma", "aroma"),
    "new oak": ("new oak", "aroma", "aroma"),
    "new wood": ("new wood", "aroma", "aroma"),
    "nut": ("nut", "aroma", "weight"),
    "nutmeg": ("nutmeg", "aroma", "aroma"),
    "oak": ("oak", "aroma", "aroma"),
    "oak-driven": ("oak-driven", "aroma", "aroma"),
    "ocean": ("ocean", "aroma", "salt"),
    "off-dry": ("off-dry", "nonaroma", "sweet"),
    "oil": ("oil", "aroma", "fat"),
    "oily": ("oily", "aroma", "aroma"),
    "olallieberry": ("olallieberry", "aroma", "aroma"),
    "olive": ("olive", "aroma", "aroma"),
    "one dimensional": ("one dimensional", "nonaroma", "weight"),
    "opulent": ("opulent", "nonaroma", "weight"),
    "orange": ("orange", "aroma", "aroma"),
    "orange blossom": ("orange blossom", "aroma", "aroma"),
    "orange marmalade": ("orange marmalade", "aroma", "aroma"),
    "orange peel": ("orange peel", "aroma", "aroma"),
    "oregano": ("oregano", "aroma", "aroma"),
    "over-oaked": ("over-oaked", "aroma", "aroma"),
    "overripe": ("overripe", "aroma", "aroma"),
    "oxidized": ("oxidized", "nonaroma", "aroma"),
    "pale": ("pale", "nonaroma", "aroma"),
    "pale color": ("pale color", "nonaroma", "aroma"),
    "papaya": ("papaya", "aroma", "aroma"),
    "passion fruit": ("passion fruit", "aroma", "aroma"),
    "pastry": ("pastry", "aroma", "aroma"),
    "pea": ("pea", "aroma", "aroma"),
    "peach": ("peach", "aroma", "aroma"),
    "peach pit": ("peach pit", "aroma", "aroma"),
    "peanut": ("peanut", "aroma", "aroma"),
    "pear": ("pear", "aroma", "aroma"),
    "pencil lead": ("pencil lead", "aroma", "aroma"),
    "pencil shaving": ("pencil shaving", "aroma", "aroma"),
    "pepper": ("pepper", "aroma", "piquant"),
    "peppery": ("peppery", "aroma", "piquant"),
    "perfumed": ("perfumed", "aroma", "aroma"),
    "persimmon": ("persimmon", "aroma", "aroma"),
    "petal": ("petal", "aroma", "aroma"),
    "petrol": ("petrol", "aroma", "aroma"),
    "phenolic": ("phenolic", "nonaroma", "bitter"),
    "pickled": ("pickled", "nonaroma", "acid"),
    "pie": ("pie", "aroma", "aroma"),
    "piercing": ("piercing", "nonaroma", "acid"),
    "pillowy": ("pillowy", "nonaroma", "bitter"),
    "pine": ("pine", "aroma", "aroma"),
    "pineapple": ("pineapple", "aroma", "aroma"),
    "pink": ("pink", "nonaroma", "aroma"),
    "pink color": ("pink color", "nonaroma", "aroma"),
    "pith": ("pith", "aroma", "aroma"),
    "plastic": ("plastic", "aroma", "aroma"),
    "pleasant bitter": ("pleasant bitter", "nonaroma", "bitter"),
    "plum": ("plum", "aroma", "aroma"),
    "plump": ("plump", "nonaroma", "weight"),
    "plush": ("plush", "nonaroma", "bitter"),
    "polished": ("polished", "nonaroma", "bitter"),
    "pollen": ("pollen", "aroma", "aroma"),
    "pomegranate": ("pomegranate", "aroma", "aroma"),
    "pop": ("pop", "nonaroma", "acid"),
    "popcorn": ("popcorn", "aroma", "aroma"),
    "potpourri": ("potpourri", "aroma", "aroma"),
    "powdery": ("powdery", "nonaroma", "bitter"),
    "powerful": ("powerful", "nonaroma", "aroma"),
    "preserved lemon": ("preserved lemon", "aroma", "aroma"),
    "prickly": ("prickly", "nonaroma", "aroma"),
    "prune": ("prune", "aroma", "aroma"),
    "prune raisin": ("prune raisin", "aroma", "aroma"),
    "puckery": ("puckery", "nonaroma", "acid"),
    "pulpy": ("pulpy", "aroma", "aroma"),
    "punchy": ("punchy", "nonaroma", "aroma"),
    "pungent": ("pungent", "nonaroma", "coolness"),
    "purple": ("purple", "nonaroma", "aroma"),
    "purple flower": ("purple flower", "aroma", "aroma"),
    "pyrazines": ("pyrazines", "aroma", "aroma"),
    "quaffer": ("quaffer", "nonaroma", "aroma"),
    "quince": ("quince", "aroma", "aroma"),
    "racy": ("racy", "nonaroma", "acid"),
    "raisin": ("raisin", "aroma", "aroma"),
    "raisin prune": ("raisin prune", "aroma", "aroma"),
    "raspberry": ("raspberry", "aroma", "aroma"),
    "raspy": ("raspy", "nonaroma", "bitter"),
    "red berry": ("red berry", "aroma", "aroma"),
    "red currant": ("red currant", "aroma", "aroma"),
    "red fruit": ("red fruit", "aroma", "aroma"),
    "red plum": ("red plum", "aroma", "aroma"),
    "reductive": ("reductive", "aroma", "aroma"),
    "reedy": ("reedy", "aroma", "aroma"),
    "refined": ("refined", "nonaroma", "weight"),
    "refreshing": ("refreshing", "nonaroma", "acid"),
    "residual sugar": ("residual sugar", "nonaroma", "sweet"),
    "residual sweetness": ("residual sweetness", "nonaroma", "sweet"),
    "resin": ("resin", "aroma", "aroma"),
    "restrained": ("restrained", "nonaroma", "aroma"),
    "rhubarb": ("rhubarb", "aroma", "aroma"),
    "rich": ("rich", "nonaroma", "weight"),
    "rind": ("rind", "aroma", "aroma"),
    "ripe": ("ripe", "aroma", "aroma"),
    "roast beef": ("roast beef", "aroma", "aroma"),
    "roasted almond": ("roasted almond", "aroma", "aroma"),
    "roasted meat": ("roasted meat", "aroma", "aroma"),
    "robust": ("robust", "nonaroma", "weight"),
    "rocks": ("rocks", "aroma", "aroma"),
    "rocky": ("rocky", "aroma", "aroma"),
    "root": ("root", "aroma", "aroma"),
    "rose": ("rose", "aroma", "aroma"),
    "rose violet": ("rose violet", "aroma", "aroma"),
    "rosemary": ("rosemary", "aroma", "aroma"),
    "rosewater": ("rosewater", "aroma", "aroma"),
    "rough": ("rough", "nonaroma", "bitter"),
    "round": ("round", "nonaroma", "aroma"),
    "rubber": ("rubber", "aroma", "aroma"),
    "ruby color": ("ruby color", "nonaroma", "aroma"),
    "rum cake": ("rum cake", "aroma", "aroma"),
    "rustic": ("rustic", "nonaroma", "bitter"),
    "rusty": ("rusty", "nonaroma", "aroma"),
    "saddle leather": ("saddle leather", "aroma", "aroma"),
    "saffron": ("saffron", "aroma", "aroma"),
    "sage": ("sage", "aroma", "aroma"),
    "sagebrush": ("sagebrush", "aroma", "aroma"),
    "saline": ("salt", "aroma", "salt"),
    "salt": ("salt", "aroma", "salt"),
    "sandalwood": ("sandalwood", "aroma", "aroma"),
    "sanguine": ("sanguine", "aroma", "aroma"),
    "sappy": ("sappy", "aroma", "aroma"),
    "sassafras": ("sassafras", "aroma", "aroma"),
    "satiny": ("satiny", "nonaroma", "bitter"),
    "savory": ("savory", "aroma", "aroma"),
    "sawdust": ("sawdust", "aroma", "aroma"),
    "scorched earth": ("scorched earth", "aroma", "aroma"),
    "scratchy": ("scratchy", "nonaroma", "bitter"),
    "semisweet": ("semisweet", "nonaroma", "sweet"),
    "sharp": ("sharp", "nonaroma", "acid"),
    "shimmer": ("shimmer", "nonaroma", "aroma"),
    "shine": ("shine", "nonaroma", "aroma"),
    "shoe polish": ("shoe polish", "aroma", "aroma"),
    "silky": ("silky", "nonaroma", "bitter"),
    "simple": ("simple", "nonaroma", "aroma"),
    "sinewy": ("sinewy", "nonaroma", "bitter"),
    "sizzling": ("sizzling", "nonaroma", "acid"),
    "slate": ("slate", "aroma", "aroma"),
    "sleek": ("sleek", "nonaroma", "bitter"),
    "slick": ("slick", "aroma", "aroma"),
    "slightly sour": ("slightly sour", "nonaroma", "acid"),
    "smoke": ("smoke", "aroma", "aroma"),
    "smoked bacon": ("smoked bacon", "aroma", "aroma"),
    "smoked meat": ("smoked meat", "aroma", "aroma"),
    "smoked nut": ("smoked nut", "aroma", "aroma"),
    "smoky": ("smoky", "aroma", "aroma"),
    "smooth": ("smooth", "nonaroma", "bitter"),
    "snappy": ("snappy", "nonaroma", "acid"),
    "soapy": ("soapy", "aroma", "aroma"),
    "soft": ("soft", "nonaroma", "acid"),
    "soil": ("soil", "aroma", "aroma"),
    "sorbet": ("sorbet", "aroma", "aroma"),
    "sour": ("sour", "nonaroma", "acid"),
    "soy": ("soy", "aroma", "aroma"),
    "soy sauce": ("soy sauce", "aroma", "aroma"),
    "sparkling": ("sparkling", "nonaroma", "aroma"),
    "spearmint": ("spearmint", "aroma", "aroma"),
    "spice": ("spice", "aroma", "aroma"),
    "spice cake": ("spice cake", "aroma", "aroma"),
    "spiky": ("spiky", "nonaroma", "acid"),
    "spring flower": ("spring flower", "aroma", "aroma"),
    "spritzy": ("spritzy", "nonaroma", "acid"),
    "stalky": ("stalky", "aroma", "aroma"),
    "star anise": ("star anise", "aroma", "aroma"),
    "steak": ("steak", "aroma", "aroma"),
    "steel": ("steel", "aroma", "aroma"),
    "stemmy": ("stemmy", "aroma", "aroma"),
    "stewed plum": ("stewed plum", "aroma", "aroma"),
    "stewed prune": ("stewed prune", "aroma", "aroma"),
    "sticky": ("sticky", "nonaroma", "sweet"),
    "stone": ("stone", "aroma", "aroma"),
    "stone fruit": ("stone fruit", "aroma", "aroma"),
    "stout": ("stout", "nonaroma", "weight"),
    "straw": ("straw", "nonaroma", "aroma"),
    "strawberry": ("strawberry", "aroma", "aroma"),
    "struck flint": ("struck flint", "aroma", "aroma"),
    "sturdy": ("sturdy", "nonaroma", "weight"),
    "succulent": ("succulent", "nonaroma", "weight"),
    "sugar": ("sugar", "nonaroma", "sweet"),
    "sulfur": ("sulfur", "aroma", "aroma"),
    "super rich": ("super rich", "nonaroma", "weight"),
    "super ripe": ("super ripe", "aroma", "aroma"),
    "supple": ("supple", "nonaroma", "bitter"),
    "sweat": ("sweat", "aroma", "aroma"),
    "sweet": ("sweet", "nonaroma", "sweet"),
    "syrupy": ("syrupy", "nonaroma", "weight"),
    "tangerine": ("tangerine", "aroma", "aroma"),
    "tangerine peel": ("tangerine peel", "aroma", "aroma"),
    "tangy": ("tangy", "nonaroma", "acid"),
    "tannin": ("tannin", "nonaroma", "bitter"),
    "tar": ("tar", "aroma", "aroma"),
    "tarragon": ("tarragon", "aroma", "aroma"),
    "tart": ("tart", "nonaroma", "acid"),
    "tea": ("tea", "aroma", "aroma"),
    "thick": ("thick", "nonaroma", "weight"),
    "thyme": ("thyme", "aroma", "aroma"),
    "tight": ("tight", "nonaroma", "bitter"),
    "tingling": ("tingling", "nonaroma", "acid"),
    "tingly": ("tingly", "nonaroma", "aroma"),
    "tire rubber": ("tire rubber", "aroma", "aroma"),
    "toast": ("toast", "aroma", "aroma"),
    "toasted almond": ("toasted almond", "aroma", "aroma"),
    "toasted coconut": ("toasted coconut", "aroma", "aroma"),
    "toasted hazelnut": ("toasted hazelnut", "aroma", "aroma"),
    "toasted nut": ("toasted nut", "aroma", "aroma"),
    "toasty oak": ("toasty oak", "aroma", "aroma"),
    "tobacco": ("tobacco", "aroma", "aroma"),
    "toffee": ("toffee", "aroma", "aroma"),
    "tomato": ("tomato", "aroma", "aroma"),
    "tree bark": ("tree bark", "aroma", "aroma"),
    "tree fruit": ("tree fruit", "aroma", "aroma"),
    "tropical fruit": ("tropical fruit", "aroma", "aroma"),
    "truffle": ("truffle", "aroma", "aroma"),
    "umami": ("umami", "aroma", "aroma"),
    "undergrowth": ("undergrowth", "aroma", "aroma"),
    "underripe": ("underripe", "aroma", "aroma"),
    "unoaked": ("unoaked", "nonaroma", "weight"),
    "unripe": ("unripe", "aroma", "aroma"),
    "vanilla": ("vanilla", "aroma", "aroma"),
    "vanilla coconut": ("vanilla coconut", "aroma", "aroma"),
    "vanilla cream": ("vanilla cream", "aroma", "aroma"),
    "vanilla dill": ("vanilla dill", "aroma", "aroma"),
    "vegetal": ("vegetal", "aroma", "aroma"),
    "velvety": ("velvety", "nonaroma", "bitter"),
    "velvety tannin": ("velvety tannin", "nonaroma", "bitter"),
    "vibrant": ("vibrant", "nonaroma", "acid"),
    "vinegar": ("vinegar", "nonaroma", "acid"),
    "violet": ("violet", "aroma", "aroma"),
    "violet rose": ("violet rose", "aroma", "aroma"),
    "viscous": ("viscous", "nonaroma", "aroma"),
    "voluptuous": ("voluptuous", "nonaroma", "weight"),
    "walnut": ("walnut", "aroma", "aroma"),
    "warm": ("warm", "nonaroma", "coolness"),
    "watermelon": ("watermelon", "aroma", "aroma"),
    "watery": ("watery", "nonaroma", "aroma"),
    "wax": ("wax", "aroma", "aroma"),
    "weed": ("weed", "aroma", "aroma"),
    "weight": ("weight", "nonaroma", "weight"),
    "wet clay": ("wet clay", "aroma", "aroma"),
    "wet earth": ("wet earth", "aroma", "aroma"),
    "wet rocks": ("wet rocks", "aroma", "aroma"),
    "white": ("white", "nonaroma", "aroma"),
    "white almond": ("white almond", "aroma", "aroma"),
    "white blossom": ("white blossom", "aroma", "aroma"),
    "white currant": ("white currant", "aroma", "aroma"),
    "white flower": ("white flower", "aroma", "aroma"),
    "white fruit": ("white fruit", "aroma", "aroma"),
    "white pepper": ("white pepper", "aroma", "piquant"),
    "wild berry": ("wild berry", "aroma", "aroma"),
    "wild flower": ("wild flower", "aroma", "aroma"),
    "wildflower": ("wildflower", "aroma", "aroma"),
    "wood": ("wood", "aroma", "aroma"),
    "wood age": ("wood age", "aroma", "aroma"),
    "wood resin": ("wood resin", "aroma", "aroma"),
    "wood spice": ("wood spice", "aroma", "aroma"),
    "woody berry": ("woody berry", "aroma", "aroma"),
    "yeast": ("yeast", "aroma", "aroma"),
    "yellow": ("yellow", "nonaroma", "aroma"),
    "yellow flower": ("yellow flower", "aroma", "aroma"),
    "yellow fruit": ("yellow fruit", "aroma", "aroma"),
    "zest": ("zest", "aroma", "aroma"),
    "zesty": ("zesty", "nonaroma", "acid"),
    "zingy": ("zingy", "nonaroma", "acid"),
    "zippy": ("zippy", "nonaroma", "acid"),
}


food_taste_mappings = {
    "aroma": ["blossom"],
    "flavor": ["yeast"],
    "weight": [
        "heavy",
        "full bodied",
        "thick",
        "milk",
        "fat",
        "steak",
        "bold",
        "pizza",
        "pasta",
        "creamy",
        "cream",
        "bread",
        "butter",
        "muffin",
        "mincemeat",
        "potato",
        "pancake",
    ],
    "sweet": [
        "sweet",
        "sugar",
        "cake",
        "chocolate",
        "baking",
        "cookie",
        "vanilla",
        "brown sugar",
        "muffin",
        "marmalade",
        "honey",
        "caramel",
        "glaze",
        "chocolate chip",
        "powdered sugar",
        "frosting",
        "cinnamon sugar",
    ],
    "acid": [
        "acid",
        "sour",
        "vinegar",
        "yoghurt",
        "cevich",
        "lemon",
        "lime",
        "orange",
        "pickle",
        "soy sauce",
        "lemon juice",
        "radish",
    ],
    "salt": [
        "salty",
        "salt",
        "parmesan",
        "oyster",
        "pizza",
        "bacon",
        "meat",
        "sausage",
        "potato chip",
        "olive",
        "sea salt",
        "ham",
        "tuna",
        "soy sauce",
        "salt pepper",
        "worcestershire sauce",
        "feta",
        "mussel",
    ],
    "piquant": [
        "spicy",
        "pepper",
        "jalapeno",
        "chili",
        "ground_black_pepper",
        "mustard",
        "curry",
        "chili",
        "chili powder",
        "curry powder",
        "paprika",
        "salsa",
    ],
    "fat": [
        "fat",
        "fried",
        "creamy",
        "cream",
        "mayonnaise",
        "butter",
        "cake",
        "sausage",
        "brie",
        "carbonara",
        "pepperoni",
        "avocado",
        "bacon fat",
    ],
    "bitter": [
        "bitter",
        "kale",
        "carrot",
        "eggplant",
        "zucchini",
        "asparagus",
        "coffee",
        "broccoli",
        "cabbage",
    ],
}


food_terms_mappings = {
    "cassoulet": ("cassoulet", "nonaroma", "weight"),
    "sausage": ("sausage", "nonaroma", "fat"),
    "fried": ("fried", "nonaroma", "fat"),
    "brie": ("brie", "nonaroma", "fat"),
    "carbonara": ("carbonara", "nonaroma", "weight"),
    "kale": ("kale", "nonaroma", "bitter"),
    "cabbage": ("cabbage", "nonaroma", "bitter"),
    "chili": ("chili", "nonaroma", "piquant"),
    "buffalo sauce": ("buffalo sauce", "nonaroma", "piquant"),
    "curry": ("curry", "nonaroma", "piquant"),
    "chipotle": ("chipotle", "nonaroma", "piquant"),
    "jam": ("yam", "nonaroma", "sweet"),
    "pretzel": ("pretzel", "nonaroma", "salt"),
    "spicy": ("spicy", "nonaroma", "piquant"),
    "oyster": ("oyster", "nonaroma", "salt"),
    "parmesan": ("parmesan", "nonaroma", "salt"),
    "potato chip": ("potato chip", "nonaroma", "salt"),
    "pizza": ("pizza", "nonaroma", "weight"),
    "sardine": ("sardine", "nonaroma", "salt"),
    "pickle": ("pickle", "nonaroma", "acid"),
    "pepperoni": ("pepperoni", "nonaroma", "fat"),
    "anchovie": ("anchovie", "nonaroma", "salt"),
    "apple": ("apple", "aroma", "acid"),
    "apple pie": ("apple pie", "aroma", "sweet"),
    "apple sauce": ("apple sauce", "aroma", "sweet"),
    "ash": ("ash", "aroma", "bitter"),
    "asian spice": ("asian spice", "aroma", "piquant"),
    "asparagus": ("asparagus", "aroma", "bitter"),
    "bacon": ("bacon", "aroma", "fat"),
    "baked": ("baked", "nonaroma", "sweet"),
    "baked bread": ("baked bread", "aroma", "weight"),
    "bread": ("bread", "nonaroma", "weight"),
    "balsamic": ("balsamic", "nonaroma", "acid"),
    "banana": ("banana", "aroma", "sweet"),
    "barbecue": ("barbecue", "aroma", "sweet"),
    "bark": ("bark", "aroma", "aroma"),
    "basil": ("basil", "aroma", "bitter"),
    "beef": ("beef", "aroma", "weight"),
    "beef jerky": ("beef jerky", "aroma", "weight"),
    "beefy": ("beefy", "nonaroma", "weight"),
    "beet": ("beet", "aroma", "bitter"),
    "beetroot": ("beetroot", "aroma", "bitter"),
    "bell pepper": ("bell pepper", "aroma", "piquant"),
    "bergamot": ("bergamot", "aroma", "acid"),
    "berry": ("berry", "aroma", "sweet"),
    "bite": ("bite", "nonaroma", "acid"),
    "bitter": ("bitter", "nonaroma", "bitter"),
    "bitter almond": ("bitter almond", "aroma", "bitter"),
    "bittersweet": ("bittersweet", "nonaroma", "bitter"),
    "black cherry": ("black cherry", "aroma", "sweet"),
    "black pepper": ("black pepper", "aroma", "piquant"),
    "blackcurrant": ("blackcurrant", "aroma", "acid"),
    "blood orange": ("blood orange", "aroma", "acid"),
    "blossom": ("blossom", "aroma", "aroma"),
    "blueberry": ("blueberry", "aroma", "acid"),
    "blueberry pie": ("blueberry pie", "aroma", "sweet"),
    "bold": ("bold", "nonaroma", "weight"),
    "bone dry": ("bone dry", "nonaroma", "sweet"),
    "boysenberry": ("boysenberry", "aroma", "acid"),
    "bramble": ("bramble", "aroma", "aroma"),
    "brawny": ("brawny", "nonaroma", "bitter"),
    "bread crust": ("bread crust", "aroma", "weight"),
    "bright": ("bright", "nonaroma", "acid"),
    "brine": ("brine", "aroma", "salt"),
    "brioche": ("brioche", "aroma", "weight"),
    "brisk": ("brisk", "nonaroma", "acid"),
    "brown butter": ("brown butter", "aroma", "fat"),
    "brown sugar": ("brown sugar", "aroma", "sweet"),
    "bulky": ("bulky", "nonaroma", "bitter"),
    "bullish": ("bullish", "nonaroma", "weight"),
    "buoyant": ("buoyant", "nonaroma", "acid"),
    "burnt": ("burnt", "aroma", "bitter"),
    "burnt toast": ("burnt toast", "aroma", "bitter"),
    "butter": ("butter", "aroma", "fat"),
    "butter nut": ("butter nut", "aroma", "fat"),
    "popcorn": ("butter popcorn", "aroma", "weight"),
    "buttercream": ("buttercream", "aroma", "weight"),
    "butterscotch": ("butterscotch", "aroma", "sweet"),
    "cake": ("cake", "aroma", "fat"),
    "candle wax": ("candle wax", "aroma", "bitter"),
    "candy": ("candy", "aroma", "sweet"),
    "caramel": ("caramel", "aroma", "sweet"),
    "cardamom": ("cardamom", "aroma", "piquant"),
    "carob": ("carob", "aroma", "aroma"),
    "cashew": ("cashew", "aroma", "fat"),
    "celery": ("celery", "aroma", "weight"),
    "chamomile": ("chamomile", "aroma", "weight"),
    "cheese": ("cheese", "aroma", "fat"),
    "cherry": ("cherry", "aroma", "sweet"),
    "cherry pie": ("cherry pie", "aroma", "fat"),
    "chocolate": ("chocolate", "aroma", "fat"),
    "choppy": ("choppy", "nonaroma", "bitter"),
    "chunky": ("chunky", "nonaroma", "weight"),
    "cider": ("cider", "aroma", "acid"),
    "cigar": ("cigar", "aroma", "bitter"),
    "cinnamon": ("cinnamon", "aroma", "sweet"),
    "citrus": ("citrus", "aroma", "acid"),
    "citrus acid": ("citrus acid", "nonaroma", "acid"),
    "clampy": ("clampy", "nonaroma", "weight"),
    "classy": ("classy", "nonaroma", "bitter"),
    "close-grained tannin": ("close-grained tannin", "nonaroma", "bitter"),
    "closed": ("closed", "nonaroma", "bitter"),
    "clove": ("clove", "aroma", "bitter"),
    "cloying": ("cloying", "nonaroma", "sweet"),
    "coarse": ("coarse", "nonaroma", "bitter"),
    "cocoa": ("cocoa", "aroma", "bitter"),
    "coconut": ("coconut", "aroma", "sweet"),
    "coffee": ("coffee", "aroma", "bitter"),
    "cookie": ("cookie", "aroma", "sweet"),
    "medium bodied": ("medium bodied", "nonaroma", "weight"),
    "sweet": ("medium sweet", "nonaroma", "sweet"),
    "tannin": ("medium tannin", "nonaroma", "bitter"),
    "melted butter": ("melted butter", "aroma", "salt"),
    "metal": ("metal", "aroma", "bitter"),
    "mild bitterness": ("mild bitterness", "nonaroma", "bitter"),
    "milk chocolate": ("milk chocolate", "aroma", "sweet"),
    "milk": ("milk", "nonaroma", "weight"),
    "mineral": ("mineral", "aroma", "salt"),
    "mint": ("mint", "aroma", "bitter"),
    "molasses": ("molasses", "aroma", "aroma"),
    "moss": ("moss", "aroma", "aroma"),
    "mousse": ("mousse", "nonaroma", "sweet"),
    "muscular": ("muscular", "nonaroma", "bitter"),
    "mushroom": ("mushroom", "aroma", "bitter"),
    "musky": ("musky", "aroma", "aroma"),
    "nectar": ("nectar", "aroma", "sweet"),
    "nectarine": ("nectarine", "aroma", "sweet"),
    "nervy": ("nervy", "nonaroma", "acid"),
    "nettle": ("nettle", "aroma", "aroma"),
    "new wood": ("new wood", "aroma", "bitter"),
    "nut": ("nut", "aroma", "weight"),
    "nutmeg": ("nutmeg", "aroma", "weight"),
    "oak": ("oak", "aroma", "bitter"),
    "ocean": ("ocean", "aroma", "salt"),
    "oil": ("oil", "aroma", "fat"),
    "oily": ("oily", "aroma", "fat"),
    "olive": ("olive", "aroma", "salt"),
    "opulent": ("opulent", "nonaroma", "weight"),
    "orange": ("orange", "aroma", "acid"),
    "orange marmalade": ("orange marmalade", "aroma", "sweet"),
    "orange peel": ("orange peel", "aroma", "bitter"),
    "oregano": ("oregano", "aroma", "piquant"),
    "over-oaked": ("over-oaked", "aroma", "bitter"),
    "papaya": ("papaya", "aroma", "sweet"),
    "pasta": ("pasta", "aroma", "weight"),
    "passion fruit": ("passion fruit", "aroma", "acid"),
    "pastry": ("pastry", "aroma", "sweet"),
    "pea": ("pea", "aroma", "aroma"),
    "peach": ("peach", "aroma", "sweet"),
    "peach pit": ("peach pit", "aroma", "aroma"),
    "peanut": ("peanut", "aroma", "salt"),
    "pear": ("pear", "aroma", "sweet"),
    "pepper": ("pepper", "aroma", "piquant"),
    "peppery": ("peppery", "aroma", "piquant"),
    "pickled": ("pickled", "nonaroma", "acid"),
    "pie": ("pie", "aroma", "fat"),
    "piercing": ("piercing", "nonaroma", "acid"),
    "pillowy": ("pillowy", "nonaroma", "bitter"),
    "pineapple": ("pineapple", "aroma", "acid"),
    "pleasant bitter": ("pleasant bitter", "nonaroma", "bitter"),
    "mustard": ("mustard", "nonaroma", "piquant"),
    "popcorn": ("popcorn", "aroma", "weight"),
    "powdery": ("powdery", "nonaroma", "bitter"),
    "preserved lemon": ("preserved lemon", "aroma", "acid"),
    "prune": ("prune", "aroma", "sweet"),
    "raisin": ("raisin", "aroma", "sweet"),
    "lemon": ("lemon custard", "aroma", "acid"),
    "lemon drop": ("lemon drop", "aroma", "acid"),
    "lemon meringue": ("lemon meringue", "aroma", "acid"),
    "lemon peel": ("lemon peel", "aroma", "acid"),
    "lettuce": ("lettuce", "aroma", "weight"),
    "licorice": ("licorice", "aroma", "bitter"),
    "light": ("light", "nonaroma", "weight"),
    "light bodied": ("light bodied", "nonaroma", "weight"),
    "lime": ("lime", "aroma", "acid"),
    "lime peel": ("lime peel", "aroma", "bitter"),
    "lime pith": ("lime pith", "aroma", "aroma"),
    "limestone": ("limestone", "aroma", "bitter"),
    "low acid": ("low acid", "nonaroma", "acid"),
    "low alcohol": ("low alcohol", "nonaroma", "bitter"),
    "luxurious": ("luxurious", "nonaroma", "weight"),
    "lychee": ("lychee", "aroma", "acid"),
    "mandarin": ("mandarin", "aroma", "acid"),
    "mango": ("mango", "nonaroma", "sweet"),
    "maple": ("maple", "aroma", "sweet"),
    "maple syrup": ("maple syrup", "aroma", "sweet"),
    "marjoram": ("marjoram", "aroma", "bitter"),
    "marmalade": ("marmalade", "aroma", "sweet"),
    "coriander": ("coriander", "nonaroma", "bitter"),
    "broccoli": ("broccoli", "nonaroma", "bitter"),
    "dark chocolate": ("dark chocolate", "nonaroma", "bitter"),
    "dill": ("dill", "nonaroma", "bitter"),
    "ginger": ("ginger", "aroma", "bitter"),
    "sour cream": ("sour cream", "nonaroma", "acid"),
    "smoked salmon": ("smoked salmon", "nonaroma", "salt"),
    "tomato": ("tomato", "nonaroma", "acid"),
    "avocado": ("avocado", "nonaroma", "fat"),
    "pesto": ("pesto", "nonaroma", "salt"),
    "onion": ("onion", "nonaroma", "piquant"),
    "garlic": ("garlic", "nonaroma", "piquant"),
    "corn": ("corn", "nonaroma", "sweet"),
    "shrimp": ("shrimp", "nonaroma", "salt"),
    "mayonnaise": ("mayonnaise", "nonaroma", "fat"),
    "jalapeno": ("jalapeno", "nonaroma", "piquant"),
    "carrot": ("carrot", "nonaroma", "bitter"),
    "eggplant": ("eggplant", "nonaroma", "bitter"),
    "zucchini": ("zucchini", "nonaroma", "bitter"),
    "meat": ("meat", "nonaroma", "weight"),
}
