wine_descriptors_mapping = {
    "acid": "acid",
    "american oak": "american oak",
    "anise": "anise",
    "apple": "apple",
    "assertive": "assertive",
    "austere": "austere",
    "baked": "baked",
    "baking spice": "baking spice",
    "bite": "bite",
    "bitter": "bitter",
    "bland": "bland",
    "blossom": "blossom",
    "bold": "bold",
    "bread": "bread",
    "bright": "bright",
    "brisk": "brisk",
    "burnt": "burnt",
    "butter": "butter",
    "butterscotch": "butterscotch",
    "cake": "cake",
    "candy": "candy",
    "caramel": "caramel",
    "cardamom": "cardamom",
    "cement": "cement",
    "chalk": "chalk",
    "cheese": "cheese",
    "chunky": "chunky",
    "cinnamon": "cinnamon",
    "citrus": "citrus",
    "clean": "clean",
    "clove": "clove",
    "cloying": "cloying",
    "coconut": "coconut",
    "complex": "complex",
    "concentrated": "concentrated",
    "cooked": "cooked",
    "cream": "cream",
    "creamy": "creamy",
    "crisp": "crisp",
    "crunchy": "crunchy",
    "dark": "dark",
    "dense": "dense",
    "depth": "depth",
    "dill": "dill",
    "dried herb": "dried herb",
    "dry": "dry",
    "dull": "dull",
    "dust": "dust",
    "earth": "earth",
    "earthy": "earthy",
    "easy": "easy",
    "edgy": "edgy",
    "elegant": "elegant",
    "expansive": "expansive",
    "fat": "fat",
    "fennel": "fennel",
    "fig": "fig",
    "firm": "firm",
    "flabby": "flabby",
    "flat": "flat",
    "fleshy": "fleshy",
    "flower": "flower",
    "french oak": "french oak",
    "fresh": "fresh",
    "fruit": "fruit",
    "fruit forward": "fruit forward",
    "fruity": "fruity",
    "full bodied": "full bodied",
    "funky": "funky",
    "ginger": "ginger",
    "graham cracker": "graham cracker",
    "grain": "grain",
    "grainy": "grainy",
    "graphite": "graphite",
    "grass": "grass",
    "gravel": "gravel",
    "green": "green",
    "grippy": "grippy",
    "gritty": "gritty",
    "hard": "hard",
    "hay": "hay",
    "heady": "heady",
    "hearty": "hearty",
    "heavy": "heavy",
    "herb": "herb",
    "high acid": "high acid",
    "hollow": "hollow",
    "hot": "hot",
    "iodine": "iodine",
    "juicy": "juicy",
    "lean": "lean",
    "lee": "lee",
    "lemon": "lemon",
    "lemon peel": "lemon peel",
    "length": "length",
    "lengthy": "lengthy",
    "licorice": "licorice",
    "light": "light",
    "light bodied": "light bodied",
    "linear": "linear",
    "lush": "lush",
    "luxurious": "luxurious",
    "marshmallow": "marshmallow",
    "meaty": "meaty",
    "medium bodied": "medium bodied",
    "mellow": "mellow",
    "mineral": "mineral",
    "minerality": "minerality",
    "mint": "mint",
    "modest": "modest",
    "new oak": "new oak",
    "nut": "nut",
    "nutmeg": "nutmeg",
    "oak": "oak",
    "oak driven": "oak driven",
    "oaked": "oaked",
    "oil": "oil",
    "one dimensional": "one dimensional",
    "opulent": "opulent",
    "orange": "orange",
    "orange peel": "orange peel",
    "overripe": "overripe",
    "pastry": "pastry",
    "peppery": "peppery",
    "perfumed": "perfumed",
    "pie": "pie",
    "pine": "pine",
    "pink": "pink",
    "plum": "plum",
    "plump": "plump",
    "plush": "plush",
    "polished": "polished",
    "pop": "pop",
    "powerful": "powerful",
    "prickly": "prickly",
    "punchy": "punchy",
    "pungent": "pungent",
    "quaffer": "quaffer",
    "racy": "racy",
    "reductive": "reductive",
    "refined": "refined",
    "refreshing": "refreshing",
    "resin": "resin",
    "restrained": "restrained",
    "rich": "rich",
    "ripe": "ripe",
    "robust": "robust",
    "rock": "rock",
    "rocky": "rocky",
    "rough": "rough",
    "round": "round",
    "rustic": "rustic",
    "salt": "salt",
    "sandalwood": "sandalwood",
    "savory": "savory",
    "sharp": "sharp",
    "shine": "shine",
    "silky": "silky",
    "simple": "simple",
    "slate": "slate",
    "sleek": "sleek",
    "smoke": "smoke",
    "smoky": "smoky",
    "smooth": "smooth",
    "soft": "soft",
    "soil": "soil",
    "sour": "sour",
    "spice": "spice",
    "spicy": "spicy",
    "stalky": "stalky",
    "steel": "steel",
    "stone": "stone",
    "sturdy": "sturdy",
    "succulent": "succulent",
    "sugar": "sugar",
    "supple": "supple",
    "sweet": "sweet",
    "syrupy": "syrupy",
    "tangy": "tangy",
    "tannin": "tannin",
    "tart": "tart",
    "tea": "tea",
    "thick": "thick",
    "tight": "tight",
    "toast": "toast",
    "toasty oak": "toasty oak",
    "toffee": "toffee",
    "underripe": "underripe",
    "vanilla": "vanilla",
    "vegetal": "vegetal",
    "velvety": "velvety",
    "vibrant": "vibrant",
    "voluptuous": "voluptuous",
    "warm": "warm",
    "weight": "weight",
    "white": "white",
    "white pepper": "white pepper",
    "wood": "wood",
    "wood spice": "wood spice",
    "yellow": "yellow",
    "zest": "zest",
    "zesty": "zesty",
}
