wine_descriptors_mapping = {
    "brã": "",
    "abound": "abound",
    "abrasive": "abrasive",
    "abundance": "abundance",
    "abundant": "abundant",
    "acacia": "acacia",
    "accent": "accent",
    "accented": "accented",
    "accessible": "accessible",
    "acid": "acid",
    "acid driven": "acid driven",
    "acidic": "acidic",
    "acidity cut": "acidity cut",
    "acidity keeps": "acidity keeps",
    "acidity lift": "acidity lift",
    "acidity supports": "acidity supports",
    "acre": "acre",
    "across": "across",
    "add": "add",
    "add complexity": "add complexity",
    "added": "added",
    "adding": "adding",
    "addition": "addition",
    "additional": "additional",
    "adds": "adds",
    "adds complexity": "adds complexity",
    "affordable": "affordable",
    "aftertaste": "aftertaste",
    "age": "age",
    "age well": "age well",
    "age year": "age year",
    "aged": "aged",
    "aged french oak": "aged french oak",
    "aged month": "aged month",
    "aged new": "aged new",
    "aggressive": "aggressive",
    "aging": "aging",
    "aging new french": "aging new french",
    "aging potential": "aging potential",
    "air": "air",
    "airy": "airy",
    "alcohol": "alcohol",
    "alive": "alive",
    "allied": "allied",
    "allow": "allow",
    "allow age": "allow age",
    "allowing": "allowing",
    "allows": "allows",
    "allspice": "allspice",
    "alluring": "alluring",
    "almond": "almond",
    "almost": "almost",
    "almost sweet": "almost sweet",
    "along": "along",
    "alongside": "alongside",
    "alpine herb": "alpine herb",
    "already": "already",
    "already delicious": "already delicious",
    "also": "also",
    "although": "although",
    "always": "always",
    "american oak": "american oak",
    "amid": "amid",
    "amidst": "amidst",
    "among": "among",
    "amount": "amount",
    "amounts": "amounts",
    "ample": "ample",
    "ample acidity": "ample acidity",
    "angular": "angular",
    "anise": "anise",
    "anjou pear": "anjou pear",
    "another": "another",
    "another year": "another year",
    "apparent": "apparent",
    "appeal": "appeal",
    "appealing": "appealing",
    "appear": "appear",
    "appears": "appears",
    "appellation": "appellation",
    "appellation blend": "appellation blend",
    "appetizing": "appetizing",
    "apple": "apple",
    "apple blossom": "apple blossom",
    "apple cider": "apple cider",
    "apple flesh": "apple flesh",
    "apple pears": "apple pears",
    "apple pie": "apple pie",
    "apple sauce": "apple sauce",
    "apple skin": "apple skin",
    "appley": "appley",
    "approach": "approach",
    "approachable": "approachable",
    "apricot": "apricot",
    "area": "area",
    "arise": "arise",
    "aroma": "aroma",
    "aroma flavor": "aroma flavor",
    "aromas lead": "aromas lead",
    "aromas meet": "aromas meet",
    "aromatic": "aromatic",
    "aromatically": "aromatically",
    "around": "around",
    "around core": "around core",
    "ash": "ash",
    "asian pear": "asian pear",
    "asian spice": "asian spice",
    "asparagus": "asparagus",
    "aspect": "aspect",
    "asphalt": "asphalt",
    "assertive": "assertive",
    "astringency": "astringency",
    "astringent": "astringent",
    "atop": "atop",
    "attention": "attention",
    "attractive": "attractive",
    "attractively": "attractively",
    "austere": "austere",
    "awash": "awash",
    "away": "away",
    "back": "back",
    "backbone": "backbone",
    "backdrop": "backdrop",
    "backed": "backed",
    "background": "background",
    "bacon": "bacon",
    "baked": "baked",
    "baked apple": "baked apple",
    "baked bread": "baked bread",
    "baked pear": "baked pear",
    "baked pineapple": "baked pineapple",
    "baking spice": "baking spice",
    "balance": "balance",
    "balancing": "balancing",
    "balsamic": "balsamic",
    "banana": "banana",
    "band aid": "band aid",
    "barbecue": "barbecue",
    "barely": "barely",
    "bark": "bark",
    "barnyard": "barnyard",
    "barrel": "barrel",
    "barrel aging": "barrel aging",
    "barrel fermentation": "barrel fermentation",
    "barrel fermented": "barrel fermented",
    "barrel influence": "barrel influence",
    "barrel toast": "barrel toast",
    "bartlett pear": "bartlett pear",
    "base": "base",
    "based": "based",
    "basic": "basic",
    "basil": "basil",
    "bay leaf": "bay leaf",
    "beaujolais": "beaujolais",
    "beautiful": "beautiful",
    "beautifully": "beautifully",
    "beauty": "beauty",
    "become": "become",
    "becomes": "becomes",
    "beef": "beef",
    "beef jerky": "beef jerky",
    "beefy": "beefy",
    "beeswax": "beeswax",
    "beet": "beet",
    "beetroot": "beetroot",
    "beginning": "beginning",
    "begins": "begins",
    "behind": "behind",
    "bell pepper": "bell pepper",
    "beneath": "beneath",
    "benefit": "benefit",
    "bergamot": "bergamot",
    "berry": "berry",
    "better": "better",
    "big": "big",
    "big boned": "big boned",
    "biodynamic": "biodynamic",
    "biscuit": "biscuit",
    "bit": "bit",
    "bite": "bite",
    "bitter": "bitter",
    "bitter almond": "bitter almond",
    "bitterness": "bitterness",
    "bittersweet": "bittersweet",
    "black cherry": "black cherry",
    "black currant": "black currant",
    "black fruit": "black fruit",
    "black pepper": "black pepper",
    "black tea": "black tea",
    "blackberry": "blackberry",
    "blackberry cassis": "blackberry cassis",
    "blackberry jam": "blackberry jam",
    "blackcurrant": "blackcurrant",
    "blanc de blancs": "blanc de blancs",
    "bland": "bland",
    "blend": "blend",
    "blended": "blended",
    "blending": "blending",
    "block": "block",
    "blood orange": "blood orange",
    "blossom": "blossom",
    "blue": "blue",
    "blue black": "blue black",
    "blue flower": "blue flower",
    "blue fruit": "blue fruit",
    "blueberry": "blueberry",
    "blueberry pie": "blueberry pie",
    "boasting": "boasting",
    "boasts": "boasts",
    "body": "body",
    "body weight": "body weight",
    "bold": "bold",
    "boldly": "boldly",
    "bolstered": "bolstered",
    "bone dry": "bone dry",
    "bosc pear": "bosc pear",
    "botanical": "botanical",
    "botrytis": "botrytis",
    "bottle": "bottle",
    "bottle age": "bottle age",
    "bottled": "bottled",
    "bottling": "bottling",
    "bottling show": "bottling show",
    "bouquet": "bouquet",
    "boysenberry": "boysenberry",
    "bracing": "bracing",
    "bramble": "bramble",
    "brand": "brand",
    "brawny": "brawny",
    "bread": "bread",
    "bread crust": "bread crust",
    "breadth": "breadth",
    "brick": "brick",
    "bright": "bright",
    "brightened": "brightened",
    "brightly": "brightly",
    "brightness": "brightness",
    "brilliant": "brilliant",
    "brine": "brine",
    "bring": "bring",
    "bringing": "bringing",
    "brings": "brings",
    "briny": "briny",
    "brioche": "brioche",
    "brisk": "brisk",
    "broad": "broad",
    "brown": "brown",
    "brown butter": "brown butter",
    "brown spice": "brown spice",
    "brown sugar": "brown sugar",
    "browned butter": "browned butter",
    "bubble gum": "bubble gum",
    "bubblegum": "bubblegum",
    "bubbles": "bubbles",
    "bubbly": "bubbly",
    "build": "build",
    "builds": "builds",
    "built": "built",
    "bulky": "bulky",
    "bullish": "bullish",
    "buoyant": "buoyant",
    "buoyed": "buoyed",
    "burgundian": "burgundian",
    "burgundy": "burgundy",
    "burnt": "burnt",
    "burnt toast": "burnt toast",
    "burst": "burst",
    "bursting": "bursting",
    "butter": "butter",
    "butter nut": "butter nut",
    "butter popcorn": "butter popcorn",
    "buttercream": "buttercream",
    "buttered": "buttered",
    "buttered nut": "buttered nut",
    "buttered popcorn": "buttered popcorn",
    "buttered toast": "buttered toast",
    "butterscotch": "butterscotch",
    "buttery": "buttery",
    "buttery toast": "buttery toast",
    "cake": "cake",
    "cake spice": "cake spice",
    "california": "california",
    "california chardonnay": "california chardonnay",
    "campfire": "campfire",
    "camphor": "camphor",
    "candied": "candied",
    "candle wax": "candle wax",
    "candy": "candy",
    "candy corn": "candy corn",
    "cantaloupe": "cantaloupe",
    "caramel": "caramel",
    "caramelized": "caramelized",
    "caramelized oak": "caramelized oak",
    "cardamom": "cardamom",
    "carnero": "carnero",
    "carob": "carob",
    "carries": "carries",
    "carry": "carry",
    "carrying": "carrying",
    "case": "case",
    "cashew": "cashew",
    "cassis": "cassis",
    "cataloupe": "cataloupe",
    "cedar": "cedar",
    "celebration": "celebration",
    "celery": "celery",
    "cellar": "cellar",
    "cellaring": "cellaring",
    "cement": "cement",
    "center": "center",
    "certainly": "certainly",
    "chablis": "chablis",
    "chalk": "chalk",
    "chalk soil": "chalk soil",
    "chalkiness": "chalkiness",
    "chalky": "chalky",
    "chalky grip": "chalky grip",
    "chalky minerality": "chalky minerality",
    "chalky texture": "chalky texture",
    "chamomile": "chamomile",
    "champagne": "champagne",
    "character": "character",
    "characteristic": "characteristic",
    "charcoal": "charcoal",
    "chard": "chard",
    "chardonnay": "chardonnay",
    "charred": "charred",
    "charred wood": "charred wood",
    "check": "check",
    "cheese": "cheese",
    "chemical": "chemical",
    "cherimoya": "cherimoya",
    "cherry": "cherry",
    "cherry liqueur": "cherry liqueur",
    "cherry pie": "cherry pie",
    "chewi": "chewi",
    "chewy": "chewy",
    "chicken": "chicken",
    "chilled": "chilled",
    "chive": "chive",
    "chocolate": "chocolate",
    "choice": "choice",
    "choppy": "choppy",
    "chunky": "chunky",
    "cider": "cider",
    "cidery": "cidery",
    "cigar": "cigar",
    "cigar box": "cigar box",
    "cinnamon": "cinnamon",
    "citric": "citric",
    "citru": "citru",
    "citrus acid": "citrus acid",
    "citrus peel": "citrus peel",
    "citrus pith": "citrus pith",
    "citrus rind": "citrus rind",
    "citrus zest": "citrus zest",
    "citrusy": "citrusy",
    "clampy": "clampy",
    "clarified butter": "clarified butter",
    "classic": "classic",
    "classically": "classically",
    "classy": "classy",
    "clay": "clay",
    "clean": "clean",
    "clean refreshing": "clean refreshing",
    "clear": "clear",
    "clone": "clone",
    "close": "close",
    "close grained tannin": "close grained tannin",
    "closed": "closed",
    "clove": "clove",
    "clove cinnamon": "clove cinnamon",
    "cloying": "cloying",
    "coarse": "coarse",
    "coastal": "coastal",
    "coat": "coat",
    "cocoa": "cocoa",
    "coconut": "coconut",
    "coffee": "coffee",
    "cola": "cola",
    "color": "color",
    "colored": "colored",
    "combination": "combination",
    "combine": "combine",
    "combines": "combines",
    "combining": "combining",
    "come": "come",
    "come together": "come together",
    "comes": "comes",
    "comes one": "comes one",
    "comes vine": "comes vine",
    "coming": "coming",
    "compelling": "compelling",
    "complement": "complement",
    "complemented": "complemented",
    "complete": "complete",
    "completely": "completely",
    "complex": "complex",
    "complexity": "complexity",
    "complicated": "complicated",
    "component": "component",
    "compost": "compost",
    "compote": "compote",
    "concentrated": "concentrated",
    "concentration": "concentration",
    "concrete": "concrete",
    "considerable": "considerable",
    "consistent": "consistent",
    "continue": "continue",
    "continues": "continues",
    "contrast": "contrast",
    "contrasts": "contrasts",
    "contribute": "contribute",
    "converge": "converge",
    "conveys": "conveys",
    "cooked": "cooked",
    "cooked spice": "cooked spice",
    "cookie": "cookie",
    "cool": "cool",
    "cool vintage": "cool vintage",
    "cooler": "cooler",
    "core": "core",
    "corn": "corn",
    "corn cob": "corn cob",
    "corn silk": "corn silk",
    "cotton candy": "cotton candy",
    "could": "could",
    "could age": "could age",
    "county": "county",
    "cracker": "cracker",
    "crafted": "crafted",
    "cramant": "cramant",
    "cranberry": "cranberry",
    "cranberry pomegranate": "cranberry pomegranate",
    "cream": "cream",
    "creamed apple": "creamed apple",
    "creamed corn": "creamed corn",
    "creaminess": "creaminess",
    "creamy": "creamy",
    "creamy feel": "creamy feel",
    "creamy texture": "creamy texture",
    "create": "create",
    "crisp": "crisp",
    "crisper": "crisper",
    "crisply": "crisply",
    "crispness": "crispness",
    "crunchy": "crunchy",
    "crushed": "crushed",
    "crushed chalk": "crushed chalk",
    "crushed rock": "crushed rock",
    "crème brulee": "crème brulee",
    "cucumber": "cucumber",
    "cured meat": "cured meat",
    "currant": "currant",
    "currently": "currently",
    "custard": "custard",
    "cut": "cut",
    "cut grass": "cut grass",
    "cutting": "cutting",
    "dainty": "dainty",
    "dance": "dance",
    "dark": "dark",
    "dark berry": "dark berry",
    "dark chocolate": "dark chocolate",
    "dark color": "dark color",
    "dark fruit": "dark fruit",
    "dark gold color": "dark gold color",
    "dash": "dash",
    "day": "day",
    "de": "de",
    "de beaune": "de beaune",
    "deal": "deal",
    "decade": "decade",
    "decadence": "decadence",
    "decadent": "decadent",
    "decent": "decent",
    "deep": "deep",
    "deep color": "deep color",
    "deep gold color": "deep gold color",
    "deeply": "deeply",
    "defined": "defined",
    "definitely": "definitely",
    "definition": "definition",
    "deftly": "deftly",
    "delicacy": "delicacy",
    "delicate": "delicate",
    "delicately": "delicately",
    "delicious": "delicious",
    "deliciously": "deliciously",
    "delightful": "delightful",
    "delightfully": "delightfully",
    "deliver": "deliver",
    "delivering": "delivering",
    "delivers": "delivers",
    "dense": "dense",
    "density": "density",
    "depth": "depth",
    "depth flavor": "depth flavor",
    "des blancs": "des blancs",
    "despite": "despite",
    "dessert": "dessert",
    "detail": "detail",
    "detailed": "detailed",
    "develop": "develop",
    "developed": "developed",
    "developing": "developing",
    "developing well": "developing well",
    "development": "development",
    "develops": "develops",
    "diesel": "diesel",
    "different": "different",
    "dijon clone": "dijon clone",
    "dill": "dill",
    "dilute": "dilute",
    "diluted": "diluted",
    "direct": "direct",
    "dish": "dish",
    "disjointed": "disjointed",
    "display": "display",
    "displaying": "displaying",
    "distinct": "distinct",
    "distinctive": "distinctive",
    "dollop": "dollop",
    "domaine": "domaine",
    "dominant": "dominant",
    "dominate": "dominate",
    "dominated": "dominated",
    "dosage": "dosage",
    "dough": "dough",
    "dr pepper": "dr pepper",
    "dried": "dried",
    "dried apricot": "dried apricot",
    "dried herb": "dried herb",
    "drink": "drink",
    "drink late": "drink late",
    "drinkable": "drinkable",
    "drinking": "drinking",
    "drive": "drive",
    "driven": "driven",
    "drunk": "drunk",
    "dry": "dry",
    "due": "due",
    "dull": "dull",
    "dust": "dust",
    "dusted": "dusted",
    "dusting": "dusting",
    "dusty": "dusty",
    "dynamic": "dynamic",
    "early": "early",
    "earth": "earth",
    "earthy": "earthy",
    "easily": "easily",
    "easy": "easy",
    "easy drinking": "easy drinking",
    "easygoing": "easygoing",
    "edge": "edge",
    "edgy": "edgy",
    "effervescent": "effervescent",
    "effort": "effort",
    "elderberry": "elderberry",
    "elderflower": "elderflower",
    "elegance": "elegance",
    "elegant": "elegant",
    "elegantly": "elegantly",
    "element": "element",
    "embrace": "embrace",
    "emerge": "emerge",
    "emerges": "emerges",
    "emerging": "emerging",
    "emphasizes": "emphasizes",
    "end": "end",
    "ending": "ending",
    "ends": "ends",
    "energetic": "energetic",
    "energy": "energy",
    "enhanced": "enhanced",
    "enjoy": "enjoy",
    "enjoyable": "enjoyable",
    "enjoyed": "enjoyed",
    "enjoyment": "enjoyment",
    "enough": "enough",
    "enticing": "enticing",
    "entirely": "entirely",
    "entry": "entry",
    "equally": "equally",
    "especially": "especially",
    "espresso": "espresso",
    "estate": "estate",
    "estate vineyard": "estate vineyard",
    "eucalyptus": "eucalyptus",
    "even": "even",
    "even better": "even better",
    "every": "every",
    "everything": "everything",
    "evolve": "evolve",
    "evolving": "evolving",
    "example": "example",
    "example variety": "example variety",
    "excellent": "excellent",
    "exceptional": "exceptional",
    "exhibit": "exhibit",
    "exotic": "exotic",
    "expansive": "expansive",
    "expect": "expect",
    "expected": "expected",
    "experience": "experience",
    "expertly": "expertly",
    "expression": "expression",
    "expression variety": "expression variety",
    "expressive": "expressive",
    "extended": "extended",
    "extra": "extra",
    "extra richness": "extra richness",
    "extracted": "extracted",
    "extreme": "extreme",
    "extremely": "extremely",
    "exuberant": "exuberant",
    "exude": "exude",
    "fade": "fade",
    "faint": "faint",
    "fairly": "fairly",
    "falls": "falls",
    "familiar": "familiar",
    "family": "family",
    "famous": "famous",
    "fan": "fan",
    "far": "far",
    "farmed": "farmed",
    "fascinating": "fascinating",
    "fat": "fat",
    "feature": "feature",
    "feel": "feel",
    "feeling": "feeling",
    "feels": "feels",
    "feels plump": "feels plump",
    "feels round": "feels round",
    "feminine": "feminine",
    "fennel": "fennel",
    "feral": "feral",
    "fermentation": "fermentation",
    "fermented": "fermented",
    "fermented aged": "fermented aged",
    "fermented stainless steel": "fermented stainless steel",
    "fig": "fig",
    "fill": "fill",
    "filled": "filled",
    "filling": "filling",
    "final": "final",
    "find": "find",
    "finding": "finding",
    "finds": "finds",
    "finds balance": "finds balance",
    "fine": "fine",
    "finegrained tannin": "finegrained tannin",
    "finely": "finely",
    "finesse": "finesse",
    "finessed": "finessed",
    "finish linger": "finish linger",
    "finished": "finished",
    "finishes": "finishes",
    "finishing": "finishing",
    "firm": "firm",
    "firm structure": "firm structure",
    "firmly": "firmly",
    "first": "first",
    "fizz": "fizz",
    "flabby": "flabby",
    "flash": "flash",
    "flashy": "flashy",
    "flat": "flat",
    "flavor": "flavor",
    "flavor profile": "flavor profile",
    "flavored": "flavored",
    "flavorful": "flavorful",
    "fleeting tannin": "fleeting tannin",
    "flesh": "flesh",
    "fleshy": "fleshy",
    "flint": "flint",
    "flinty": "flinty",
    "floral": "floral",
    "flower": "flower",
    "flowery": "flowery",
    "foamy": "foamy",
    "focus": "focus",
    "focused": "focused",
    "follow": "follow",
    "followed": "followed",
    "follows": "follows",
    "food": "food",
    "foot": "foot",
    "fore": "fore",
    "forest floor": "forest floor",
    "form": "form",
    "forward": "forward",
    "foundation": "foundation",
    "four": "four",
    "foxy": "foxy",
    "fragrance": "fragrance",
    "fragrant": "fragrant",
    "frame": "frame",
    "framed": "framed",
    "french": "french",
    "french oak": "french oak",
    "french oak new": "french oak new",
    "fresh": "fresh",
    "fresher": "fresher",
    "freshly": "freshly",
    "freshly cut": "freshly cut",
    "freshness": "freshness",
    "friendly": "friendly",
    "front": "front",
    "frothy": "frothy",
    "fruit": "fruit",
    "fruit forward": "fruit forward",
    "fruitiness": "fruitiness",
    "fruity": "fruity",
    "fudge": "fudge",
    "full": "full",
    "full bodied": "full bodied",
    "full body": "full body",
    "full mouth": "full mouth",
    "fully": "fully",
    "fulsome": "fulsome",
    "funky": "funky",
    "future": "future",
    "gala apple": "gala apple",
    "game": "game",
    "gardenia": "gardenia",
    "generic": "generic",
    "generosity": "generosity",
    "generous": "generous",
    "generously": "generously",
    "gentle": "gentle",
    "gently": "gently",
    "get": "get",
    "gets": "gets",
    "ginger": "ginger",
    "gingerbread": "gingerbread",
    "give": "give",
    "give way": "give way",
    "given": "given",
    "gives": "gives",
    "gives way": "gives way",
    "giving": "giving",
    "glass": "glass",
    "go": "go",
    "goes": "goes",
    "going": "going",
    "gold": "gold",
    "gold color": "gold color",
    "golden": "golden",
    "golden apple": "golden apple",
    "golden color": "golden color",
    "golden delicious apple": "golden delicious apple",
    "golden honey": "golden honey",
    "good": "good",
    "good balance": "good balance",
    "gooseberry": "gooseberry",
    "gorgeous": "gorgeous",
    "grabby": "grabby",
    "grace": "grace",
    "graceful": "graceful",
    "graham cracker": "graham cracker",
    "grain": "grain",
    "grainy": "grainy",
    "grand": "grand",
    "grand cru": "grand cru",
    "grand cru vineyard": "grand cru vineyard",
    "grand crus": "grand crus",
    "granite": "granite",
    "grape": "grape",
    "grapefruit": "grapefruit",
    "grapefruit peel": "grapefruit peel",
    "grapefruit pith": "grapefruit pith",
    "grapey": "grapey",
    "graphite": "graphite",
    "grass": "grass",
    "grassy": "grassy",
    "gravel": "gravel",
    "gravelly texture": "gravelly texture",
    "gravenstein apple": "gravenstein apple",
    "great": "great",
    "great fruitiness": "great fruitiness",
    "green": "green",
    "green apple": "green apple",
    "green banana": "green banana",
    "green bean": "green bean",
    "green fruit": "green fruit",
    "green olive": "green olive",
    "green pepper": "green pepper",
    "green plum": "green plum",
    "greet nose": "greet nose",
    "grilled": "grilled",
    "grilled herb": "grilled herb",
    "grilled meat": "grilled meat",
    "grilled peach": "grilled peach",
    "grilled pineapple": "grilled pineapple",
    "grip": "grip",
    "gripping": "gripping",
    "gripping tannin": "gripping tannin",
    "grippy": "grippy",
    "grippy texture": "grippy texture",
    "gritty": "gritty",
    "growing": "growing",
    "grown": "grown",
    "guava": "guava",
    "guava mango": "guava mango",
    "gummy": "gummy",
    "half": "half",
    "ham": "ham",
    "hard": "hard",
    "harmonious": "harmonious",
    "harmony": "harmony",
    "hay": "hay",
    "hazelnut": "hazelnut",
    "heady": "heady",
    "healthy": "healthy",
    "heart": "heart",
    "hearty": "hearty",
    "heat": "heat",
    "heavy": "heavy",
    "heft": "heft",
    "help": "help",
    "helps": "helps",
    "herb": "herb",
    "herbacious": "herbacious",
    "herbal": "herbal",
    "hibiscus": "hibiscus",
    "hickory": "hickory",
    "hickory smoke": "hickory smoke",
    "high": "high",
    "high acid": "high acid",
    "high alcohol": "high alcohol",
    "high tannin": "high tannin",
    "highlight": "highlight",
    "highlights": "highlights",
    "highly": "highly",
    "hill": "hill",
    "hint": "hint",
    "hinting": "hinting",
    "historic": "historic",
    "historic vineyard": "historic vineyard",
    "hit": "hit",
    "hits": "hits",
    "hold": "hold",
    "holds": "holds",
    "hollow": "hollow",
    "honey": "honey",
    "honeycomb": "honeycomb",
    "honeydew": "honeydew",
    "honeydew melon": "honeydew melon",
    "honeyed": "honeyed",
    "honeysuckle": "honeysuckle",
    "horsey": "horsey",
    "hot": "hot",
    "however": "however",
    "huckleberry": "huckleberry",
    "iconic": "iconic",
    "ideal": "ideal",
    "immediate": "immediate",
    "immediately": "immediately",
    "immediately attractive": "immediately attractive",
    "impact": "impact",
    "impart": "impart",
    "imported": "imported",
    "impress": "impress",
    "impression": "impression",
    "impressive": "impressive",
    "impressively": "impressively",
    "imprint": "imprint",
    "improve": "improve",
    "incense": "incense",
    "includes": "includes",
    "including": "including",
    "indian spice": "indian spice",
    "influence": "influence",
    "initial": "initial",
    "initially": "initially",
    "inky": "inky",
    "instead": "instead",
    "integrate": "integrate",
    "integrated": "integrated",
    "integrated oak": "integrated oak",
    "intense": "intense",
    "intensely": "intensely",
    "intensity": "intensity",
    "interest": "interest",
    "interesting": "interesting",
    "intrigue": "intrigue",
    "intriguing": "intriguing",
    "introduce": "introduce",
    "invites": "invites",
    "inviting": "inviting",
    "iodine": "iodine",
    "iron": "iron",
    "jagged": "jagged",
    "jalapeno": "jalapeno",
    "jam": "jam",
    "jasmine": "jasmine",
    "jelly": "jelly",
    "jicama": "jicama",
    "judicious": "judicious",
    "juice": "juice",
    "juiciness": "juiciness",
    "juicy": "juicy",
    "juniper": "juniper",
    "keep": "keep",
    "keeping": "keeping",
    "keeps": "keeps",
    "kept": "kept",
    "key lime": "key lime",
    "kick": "kick",
    "kirsch": "kirsch",
    "kiss": "kiss",
    "kiwi": "kiwi",
    "known": "known",
    "kumquat": "kumquat",
    "la": "la",
    "label": "label",
    "labeled": "labeled",
    "laced": "laced",
    "lack": "lack",
    "lacking": "lacking",
    "lacks": "lacks",
    "lactic": "lactic",
    "lanolin": "lanolin",
    "large": "large",
    "largely": "largely",
    "last": "last",
    "lasting": "lasting",
    "late": "late",
    "latex": "latex",
    "lavender": "lavender",
    "lavish": "lavish",
    "layer": "layer",
    "layered": "layered",
    "layering": "layering",
    "le": "le",
    "lead": "lead",
    "lead way": "lead way",
    "leading": "leading",
    "leads": "leads",
    "leafy": "leafy",
    "lean": "lean",
    "least": "least",
    "leather": "leather",
    "leaves": "leaves",
    "leaving": "leaving",
    "lee": "lee",
    "leesy": "leesy",
    "left": "left",
    "lemon": "lemon",
    "lemon balm": "lemon balm",
    "lemon blossom": "lemon blossom",
    "lemon candy": "lemon candy",
    "lemon chiffon": "lemon chiffon",
    "lemon curd": "lemon curd",
    "lemon custard": "lemon custard",
    "lemon drop": "lemon drop",
    "lemon juice": "lemon juice",
    "lemon lime": "lemon lime",
    "lemon meringue": "lemon meringue",
    "lemon oil": "lemon oil",
    "lemon peel": "lemon peel",
    "lemon pith": "lemon pith",
    "lemon rind": "lemon rind",
    "lemon verbena": "lemon verbena",
    "lemon zest": "lemon zest",
    "lemonade": "lemonade",
    "lemongrass": "lemongrass",
    "lemony": "lemony",
    "lend": "lend",
    "lending": "lending",
    "length": "length",
    "lengthy": "lengthy",
    "lengthy finish": "lengthy finish",
    "less": "less",
    "let": "let",
    "lettuce": "lettuce",
    "level": "level",
    "lick": "lick",
    "licorice": "licorice",
    "lie": "lie",
    "life": "life",
    "lift": "lift",
    "lifted": "lifted",
    "light": "light",
    "light bodied": "light bodied",
    "light color": "light color",
    "light style": "light style",
    "lightly": "lightly",
    "lightly creamy feel": "lightly creamy feel",
    "lightly oaked": "lightly oaked",
    "lightly spicy": "lightly spicy",
    "lightly toasty": "lightly toasty",
    "lightness": "lightness",
    "likable": "likable",
    "like": "like",
    "likely": "likely",
    "lilac": "lilac",
    "lily": "lily",
    "lime": "lime",
    "lime blossom": "lime blossom",
    "lime juice": "lime juice",
    "lime peel": "lime peel",
    "lime pith": "lime pith",
    "lime rind": "lime rind",
    "lime sorbet": "lime sorbet",
    "lime zest": "lime zest",
    "limestone": "limestone",
    "limited": "limited",
    "line": "line",
    "linear": "linear",
    "linger": "linger",
    "linger finish": "linger finish",
    "lingering": "lingering",
    "lingering finish": "lingering finish",
    "lingers": "lingers",
    "lingers finish": "lingers finish",
    "lithe": "lithe",
    "little": "little",
    "lively": "lively",
    "loaded": "loaded",
    "loamy": "loamy",
    "located": "located",
    "long": "long",
    "long finish": "long finish",
    "longer": "longer",
    "longtime": "longtime",
    "los": "los",
    "lot": "lot",
    "love": "love",
    "lovely": "lovely",
    "lover": "lover",
    "low": "low",
    "low acid": "low acid",
    "low alcohol": "low alcohol",
    "low complexity": "low complexity",
    "low oak": "low oak",
    "luminous": "luminous",
    "lurking": "lurking",
    "luscious": "luscious",
    "lush": "lush",
    "lushly": "lushly",
    "lushness": "lushness",
    "luxurious": "luxurious",
    "lychee": "lychee",
    "macadamia nut": "macadamia nut",
    "mace": "mace",
    "made": "made",
    "made entirely chardonnay": "made entirely chardonnay",
    "main": "main",
    "mainly": "mainly",
    "maintains": "maintains",
    "majority": "majority",
    "make": "make",
    "makes": "makes",
    "making": "making",
    "malolactic": "malolactic",
    "malolactic fermentation": "malolactic fermentation",
    "manages": "manages",
    "mandarin": "mandarin",
    "mandarin orange": "mandarin orange",
    "mango": "mango",
    "mango pineapple": "mango pineapple",
    "many": "many",
    "many year": "many year",
    "maple": "maple",
    "maple syrup": "maple syrup",
    "marcona almond": "marcona almond",
    "margaret river": "margaret river",
    "marjoram": "marjoram",
    "mark": "mark",
    "marked": "marked",
    "marks": "marks",
    "marmalade": "marmalade",
    "marshmallow": "marshmallow",
    "marzipan": "marzipan",
    "masculine": "masculine",
    "mass": "mass",
    "match": "match",
    "matched": "matched",
    "matchstick": "matchstick",
    "mature": "mature",
    "maturity": "maturity",
    "may": "may",
    "mealy": "mealy",
    "means": "means",
    "measured": "measured",
    "meat": "meat",
    "meaty": "meaty",
    "medicinal": "medicinal",
    "meditteranean herb": "meditteranean herb",
    "medium": "medium",
    "medium bodied": "medium bodied",
    "medium body": "medium body",
    "medium length finish": "medium length finish",
    "medium sweet": "medium sweet",
    "medium tannin": "medium tannin",
    "medium weight": "medium weight",
    "meet": "meet",
    "meets": "meets",
    "meld": "meld",
    "mellow": "mellow",
    "melon": "melon",
    "melon papaya": "melon papaya",
    "melon rind": "melon rind",
    "melony": "melony",
    "melted butter": "melted butter",
    "memorable": "memorable",
    "menthol": "menthol",
    "meringue": "meringue",
    "met": "met",
    "metal": "metal",
    "meursault": "meursault",
    "meyer lemon": "meyer lemon",
    "meyer lemon pith": "meyer lemon pith",
    "middle": "middle",
    "midpalate": "midpalate",
    "might": "might",
    "mild": "mild",
    "mild bitterness": "mild bitterness",
    "mildly": "mildly",
    "milk chocolate": "milk chocolate",
    "mind": "mind",
    "mineral": "mineral",
    "mineral character": "mineral character",
    "mineral edge": "mineral edge",
    "mineral note": "mineral note",
    "mineral texture": "mineral texture",
    "minerality": "minerality",
    "minerally": "minerally",
    "mingle": "mingle",
    "mint": "mint",
    "missing": "missing",
    "mix": "mix",
    "mixed": "mixed",
    "moderate": "moderate",
    "moderate acidity": "moderate acidity",
    "moderately": "moderately",
    "modest": "modest",
    "moist earth": "moist earth",
    "molasses": "molasses",
    "moment": "moment",
    "montagne de reim": "montagne de reim",
    "month": "month",
    "moss": "moss",
    "mostly": "mostly",
    "mountain": "mountain",
    "mousse": "mousse",
    "mouth": "mouth",
    "mouthfeel": "mouthfeel",
    "mouthfilling": "mouthfilling",
    "mouthwatering": "mouthwatering",
    "much": "much",
    "mulberry": "mulberry",
    "mulch": "mulch",
    "murky": "murky",
    "muscular": "muscular",
    "mushroom": "mushroom",
    "musky": "musky",
    "mustard": "mustard",
    "muted": "muted",
    "name": "name",
    "named": "named",
    "napa valley": "napa valley",
    "natural": "natural",
    "nature": "nature",
    "near": "near",
    "nearly": "nearly",
    "nectar": "nectar",
    "nectarine": "nectarine",
    "nectarine flesh": "nectarine flesh",
    "need": "need",
    "need time": "need time",
    "needing": "needing",
    "needs": "needs",
    "needs age": "needs age",
    "needs age drink": "needs age drink",
    "needs time": "needs time",
    "nervy": "nervy",
    "nettle": "nettle",
    "neutral": "neutral",
    "neutral french oak": "neutral french oak",
    "neutral oak": "neutral oak",
    "never": "never",
    "new": "new",
    "new french": "new french",
    "new french oak": "new french oak",
    "new oak": "new oak",
    "new wood": "new wood",
    "next": "next",
    "nice": "nice",
    "nice balance": "nice balance",
    "nicely": "nicely",
    "nicely balanced": "nicely balanced",
    "nine": "nine",
    "north": "north",
    "northern": "northern",
    "nose appellation blend": "nose appellation blend",
    "nose bottling": "nose bottling",
    "note": "note",
    "nothing": "nothing",
    "noticeable": "noticeable",
    "notion": "notion",
    "nuance": "nuance",
    "nuanced": "nuanced",
    "number": "number",
    "nut": "nut",
    "nutmeg": "nutmeg",
    "nuttiness": "nuttiness",
    "nutty": "nutty",
    "oak": "oak",
    "oak barrel": "oak barrel",
    "oak driven": "oak driven",
    "oak influence": "oak influence",
    "oaked": "oaked",
    "oaky": "oaky",
    "obvious": "obvious",
    "ocean": "ocean",
    "offer": "offer",
    "offering": "offering",
    "offset": "offset",
    "often": "often",
    "oil": "oil",
    "oily": "oily",
    "olallieberry": "olallieberry",
    "old": "old",
    "old vine": "old vine",
    "olive": "olive",
    "one": "one",
    "one dimensional": "one dimensional",
    "onto": "onto",
    "open": "open",
    "opening": "opening",
    "opens": "opens",
    "opulence": "opulence",
    "opulent": "opulent",
    "orange": "orange",
    "orange blossom": "orange blossom",
    "orange marmalade": "orange marmalade",
    "orange oil": "orange oil",
    "orange peel": "orange peel",
    "orange rind": "orange rind",
    "orange zest": "orange zest",
    "orchard fruit": "orchard fruit",
    "oregano": "oregano",
    "oregon": "oregon",
    "otherwise": "otherwise",
    "outstanding": "outstanding",
    "overall": "overall",
    "overdone": "overdone",
    "overly": "overly",
    "overpowering": "overpowering",
    "overripe": "overripe",
    "overt": "overt",
    "oxidation": "oxidation",
    "oxidative": "oxidative",
    "oxidized": "oxidized",
    "oyster shell": "oyster shell",
    "pack": "pack",
    "package": "package",
    "packed": "packed",
    "pair": "pair",
    "pair well": "pair well",
    "pairing": "pairing",
    "palate delivers": "palate delivers",
    "pale": "pale",
    "pale color": "pale color",
    "papaya": "papaya",
    "parcel": "parcel",
    "part": "part",
    "particularly": "particularly",
    "passion fruit": "passion fruit",
    "past": "past",
    "pastry": "pastry",
    "pea": "pea",
    "peach": "peach",
    "peach apricot": "peach apricot",
    "peach pit": "peach pit",
    "peachy": "peachy",
    "peak": "peak",
    "peanut": "peanut",
    "pear": "pear",
    "pears": "pears",
    "pecan": "pecan",
    "peel": "peel",
    "peels": "peels",
    "pencil lead": "pencil lead",
    "pencil shaving": "pencil shaving",
    "penetrating": "penetrating",
    "people": "people",
    "pepper": "pepper",
    "peppery": "peppery",
    "perfect": "perfect",
    "perfectly": "perfectly",
    "perfume": "perfume",
    "perfumed": "perfumed",
    "perhaps": "perhaps",
    "perlage": "perlage",
    "persimmon": "persimmon",
    "persist": "persist",
    "persistent": "persistent",
    "personality": "personality",
    "petal": "petal",
    "petrol": "petrol",
    "phenolic": "phenolic",
    "pickled": "pickled",
    "picks": "picks",
    "pie": "pie",
    "piercing": "piercing",
    "pillowy": "pillowy",
    "pinch": "pinch",
    "pine": "pine",
    "pineapple": "pineapple",
    "pineapple guava": "pineapple guava",
    "pineapple mango": "pineapple mango",
    "pink": "pink",
    "pink color": "pink color",
    "pink grapefruit": "pink grapefruit",
    "pink lady apple": "pink lady apple",
    "pinot noir": "pinot noir",
    "pioneering": "pioneering",
    "pith": "pith",
    "pithy": "pithy",
    "place": "place",
    "planted": "planted",
    "plastic": "plastic",
    "play": "play",
    "playing": "playing",
    "plays": "plays",
    "pleasant": "pleasant",
    "pleasant bitter": "pleasant bitter",
    "pleasantly": "pleasantly",
    "please": "please",
    "pleasing": "pleasing",
    "pleasure": "pleasure",
    "plenty": "plenty",
    "plum": "plum",
    "plumeria": "plumeria",
    "plump": "plump",
    "plus": "plus",
    "plush": "plush",
    "poached apple": "poached apple",
    "poached pear": "poached pear",
    "point": "point",
    "poised": "poised",
    "polished": "polished",
    "pollen": "pollen",
    "pomegranate": "pomegranate",
    "pop": "pop",
    "popcorn": "popcorn",
    "potential": "potential",
    "potpourri": "potpourri",
    "powdery": "powdery",
    "power": "power",
    "powerful": "powerful",
    "powerfully": "powerfully",
    "precise": "precise",
    "precision": "precision",
    "premier cru": "premier cru",
    "premier crus": "premier crus",
    "presence": "presence",
    "present": "present",
    "preserved lemon": "preserved lemon",
    "pressed": "pressed",
    "pretty": "pretty",
    "pretty floral": "pretty floral",
    "price": "price",
    "priced": "priced",
    "prickly": "prickly",
    "prime": "prime",
    "pristine": "pristine",
    "produce": "produce",
    "produced": "produced",
    "producer": "producer",
    "produces": "produces",
    "production": "production",
    "profile": "profile",
    "project": "project",
    "prominent": "prominent",
    "prominently": "prominently",
    "promise": "promise",
    "promises": "promises",
    "promising": "promising",
    "pronounced": "pronounced",
    "property": "property",
    "prove": "prove",
    "provide": "provide",
    "provides": "provides",
    "providing": "providing",
    "proving": "proving",
    "prune": "prune",
    "prune raisin": "prune raisin",
    "puckery": "puckery",
    "pulling": "pulling",
    "pulls": "pulls",
    "pulpy": "pulpy",
    "pumpkin": "pumpkin",
    "punch": "punch",
    "punchy": "punchy",
    "pungent": "pungent",
    "pure": "pure",
    "purity": "purity",
    "purple": "purple",
    "purple flower": "purple flower",
    "push": "push",
    "put": "put",
    "pyrazine": "pyrazine",
    "quaffable": "quaffable",
    "quaffer": "quaffer",
    "quality": "quality",
    "quickly": "quickly",
    "quiet": "quiet",
    "quince": "quince",
    "quinine": "quinine",
    "quite": "quite",
    "racy": "racy",
    "raisin": "raisin",
    "raisin prune": "raisin prune",
    "ranch": "ranch",
    "range": "range",
    "rare": "rare",
    "raspberry": "raspberry",
    "raspy": "raspy",
    "rather": "rather",
    "raw": "raw",
    "ready": "ready",
    "ready drink": "ready drink",
    "really": "really",
    "reasonably": "reasonably",
    "red": "red",
    "red apple": "red apple",
    "red berry": "red berry",
    "red currant": "red currant",
    "red fruit": "red fruit",
    "red plum": "red plum",
    "reduced": "reduced",
    "reduction": "reduction",
    "reductive": "reductive",
    "reedy": "reedy",
    "refined": "refined",
    "reflects": "reflects",
    "refreshe": "refreshe",
    "refreshing": "refreshing",
    "refreshingly": "refreshingly",
    "refreshment": "refreshment",
    "region": "region",
    "regular": "regular",
    "relatively": "relatively",
    "release": "release",
    "remain": "remain",
    "remaining": "remaining",
    "remains": "remains",
    "remarkable": "remarkable",
    "reminiscent": "reminiscent",
    "reserve": "reserve",
    "reserved": "reserved",
    "residual sugar": "residual sugar",
    "residual sweetness": "residual sweetness",
    "resin": "resin",
    "resiny": "resiny",
    "resiny oak": "resiny oak",
    "rest": "rest",
    "restrained": "restrained",
    "restraint": "restraint",
    "result": "result",
    "retaining": "retaining",
    "retains": "retains",
    "reveal": "reveal",
    "revealing": "revealing",
    "reveals": "reveals",
    "rewarding": "rewarding",
    "rhubarb": "rhubarb",
    "rich": "rich",
    "richly": "richly",
    "richly layered": "richly layered",
    "richly textured": "richly textured",
    "richness concentration": "richness concentration",
    "ride": "ride",
    "right": "right",
    "right amount": "right amount",
    "right front": "right front",
    "rind": "rind",
    "rinds": "rinds",
    "ripe": "ripe",
    "ripe yellow fruit": "ripe yellow fruit",
    "ripeness": "ripeness",
    "riper": "riper",
    "rise": "rise",
    "rises": "rises",
    "rita hill": "rita hill",
    "river": "river",
    "road": "road",
    "roast beef": "roast beef",
    "roasted": "roasted",
    "roasted almond": "roasted almond",
    "roasted meat": "roasted meat",
    "roasted nut": "roasted nut",
    "robust": "robust",
    "robustly": "robustly",
    "rock": "rock",
    "rocky": "rocky",
    "room": "room",
    "root": "root",
    "rose": "rose",
    "rose violet": "rose violet",
    "rosemary": "rosemary",
    "rosewater": "rosewater",
    "rough": "rough",
    "round": "round",
    "rounded": "rounded",
    "roundness": "roundness",
    "rubber": "rubber",
    "ruby color": "ruby color",
    "rum cake": "rum cake",
    "run": "run",
    "russian river valley": "russian river valley",
    "rustic": "rustic",
    "rusty": "rusty",
    "saddle leather": "saddle leather",
    "saffron": "saffron",
    "sage": "sage",
    "saline": "saline",
    "salinity": "salinity",
    "salt": "salt",
    "salted": "salted",
    "salted caramel": "salted caramel",
    "saltiness": "saltiness",
    "salty": "salty",
    "san": "san",
    "sandalwood": "sandalwood",
    "sangiacomo": "sangiacomo",
    "sanguine": "sanguine",
    "sappy": "sappy",
    "sassafras": "sassafras",
    "satiny": "satiny",
    "satisfying": "satisfying",
    "sauce": "sauce",
    "sauvignon blanc": "sauvignon blanc",
    "savory": "savory",
    "sawdust": "sawdust",
    "scent": "scent",
    "scorched earth": "scorched earth",
    "scratchy": "scratchy",
    "sea": "sea",
    "sea salt": "sea salt",
    "sea salt caramel": "sea salt caramel",
    "sea spray": "sea spray",
    "seafood": "seafood",
    "seamless": "seamless",
    "seamlessly": "seamlessly",
    "seared": "seared",
    "seared lemon": "seared lemon",
    "seasoned": "seasoned",
    "second": "second",
    "secondary": "secondary",
    "seductive": "seductive",
    "see": "see",
    "seem": "seem",
    "seemingly": "seemingly",
    "seems": "seems",
    "seems bit": "seems bit",
    "selection": "selection",
    "semisweet": "semisweet",
    "sensation": "sensation",
    "sense": "sense",
    "sense balance": "sense balance",
    "series": "series",
    "serious": "serious",
    "serve": "serve",
    "set": "set",
    "settle": "settle",
    "settling": "settling",
    "several": "several",
    "several year": "several year",
    "shape": "shape",
    "sharp": "sharp",
    "sharply": "sharply",
    "sharpness": "sharpness",
    "shellfish": "shellfish",
    "shimmer": "shimmer",
    "shine": "shine",
    "shines": "shines",
    "shoe polish": "shoe polish",
    "short": "short",
    "shot": "shot",
    "show": "show",
    "show nose": "show nose",
    "show nose bottling": "show nose bottling",
    "show sip": "show sip",
    "showcases": "showcases",
    "showing": "showing",
    "showy": "showy",
    "shy": "shy",
    "side": "side",
    "sign": "sign",
    "silky": "silky",
    "similar": "similar",
    "similarly": "similarly",
    "simple": "simple",
    "simply": "simply",
    "since": "since",
    "sinewy": "sinewy",
    "sing": "sing",
    "single": "single",
    "single vineyard": "single vineyard",
    "sip": "sip",
    "sipped": "sipped",
    "sipper": "sipper",
    "site": "site",
    "sits": "sits",
    "situated": "situated",
    "six": "six",
    "sizzle acidity": "sizzle acidity",
    "sizzling": "sizzling",
    "skin": "skin",
    "slate": "slate",
    "sleek": "sleek",
    "slice": "slice",
    "sliced": "sliced",
    "slick": "slick",
    "slight": "slight",
    "slight hint": "slight hint",
    "slightly": "slightly",
    "slightly bitter": "slightly bitter",
    "slightly sour": "slightly sour",
    "slightly sweet": "slightly sweet",
    "slippery": "slippery",
    "slope": "slope",
    "slowly": "slowly",
    "small": "small",
    "smelling": "smelling",
    "smells": "smells",
    "smells like": "smells like",
    "smoke": "smoke",
    "smoked": "smoked",
    "smoked bacon": "smoked bacon",
    "smoked meat": "smoked meat",
    "smoked nut": "smoked nut",
    "smoky": "smoky",
    "smooth": "smooth",
    "smooth creamy": "smooth creamy",
    "smoothly textured": "smoothly textured",
    "snappy": "snappy",
    "soapy": "soapy",
    "soda": "soda",
    "soft": "soft",
    "soften": "soften",
    "softly": "softly",
    "softly textured": "softly textured",
    "softness": "softness",
    "soil": "soil",
    "solid": "solid",
    "something": "something",
    "somewhat": "somewhat",
    "soon": "soon",
    "sophisticated": "sophisticated",
    "sorbet": "sorbet",
    "sour": "sour",
    "sour cream": "sour cream",
    "source": "source",
    "sourced": "sourced",
    "sourdough": "sourdough",
    "south": "south",
    "southern": "southern",
    "soy": "soy",
    "soy sauce": "soy sauce",
    "sparkler": "sparkler",
    "sparkling": "sparkling",
    "speak": "speak",
    "speaks": "speaks",
    "spearmint": "spearmint",
    "special": "special",
    "spent": "spent",
    "spice": "spice",
    "spice cake": "spice cake",
    "spice wood aging": "spice wood aging",
    "spiced": "spiced",
    "spiciness": "spiciness",
    "spicy": "spicy",
    "spicy nutmeg": "spicy nutmeg",
    "spiky": "spiky",
    "spine": "spine",
    "spray": "spray",
    "spring": "spring",
    "spring flower": "spring flower",
    "spritz": "spritz",
    "spritzy": "spritzy",
    "squash": "squash",
    "squeezed": "squeezed",
    "squeezed lemon": "squeezed lemon",
    "squeezed lime": "squeezed lime",
    "sta": "sta",
    "stage": "stage",
    "stainless": "stainless",
    "stainless steel": "stainless steel",
    "stalky": "stalky",
    "stand": "stand",
    "standard": "standard",
    "stands": "stands",
    "star": "star",
    "star anise": "star anise",
    "start": "start",
    "start finish": "start finish",
    "starting": "starting",
    "starts": "starts",
    "stay": "stay",
    "stays": "stays",
    "steady": "steady",
    "steak": "steak",
    "steel": "steel",
    "steeliness": "steeliness",
    "steely": "steely",
    "steely edge": "steely edge",
    "stemmy": "stemmy",
    "steve": "steve",
    "stewed plum": "stewed plum",
    "stewed prune": "stewed prune",
    "sticky": "sticky",
    "still": "still",
    "still developing": "still developing",
    "still young": "still young",
    "stone": "stone",
    "stone fruit": "stone fruit",
    "stony": "stony",
    "stony mineral": "stony mineral",
    "stony minerality": "stony minerality",
    "stout": "stout",
    "straight": "straight",
    "straightforward": "straightforward",
    "straw": "straw",
    "strawberry": "strawberry",
    "streak": "streak",
    "streaks": "streaks",
    "strong": "strong",
    "strong mineral": "strong mineral",
    "strongly": "strongly",
    "struck flint": "struck flint",
    "struck match": "struck match",
    "structure": "structure",
    "structured": "structured",
    "study": "study",
    "stunning": "stunning",
    "sturdy": "sturdy",
    "style": "style",
    "styled": "styled",
    "stylish": "stylish",
    "subdued": "subdued",
    "sublime": "sublime",
    "substantial": "substantial",
    "subtle": "subtle",
    "subtlety": "subtlety",
    "subtly": "subtly",
    "succulence": "succulence",
    "succulent": "succulent",
    "sugar": "sugar",
    "suggest": "suggest",
    "suggesting": "suggesting",
    "suggestion": "suggestion",
    "suggests": "suggests",
    "sulfur": "sulfur",
    "sultry": "sultry",
    "summer": "summer",
    "sumptuous": "sumptuous",
    "sunny": "sunny",
    "super rich": "super rich",
    "super ripe": "super ripe",
    "superb": "superb",
    "supple": "supple",
    "support": "support",
    "supported": "supported",
    "supporting": "supporting",
    "supportive": "supportive",
    "supports": "supports",
    "surprisingly": "surprisingly",
    "surrounded": "surrounded",
    "swathes": "swathes",
    "sweat": "sweat",
    "sweet": "sweet",
    "sweetness": "sweetness",
    "swirl": "swirl",
    "syrup": "syrup",
    "syrupy": "syrupy",
    "table": "table",
    "tad": "tad",
    "take": "take",
    "takes": "takes",
    "taking": "taking",
    "tang": "tang",
    "tangerine": "tangerine",
    "tangerine peel": "tangerine peel",
    "tangy": "tangy",
    "tangy zesty": "tangy zesty",
    "tannic": "tannic",
    "tannin": "tannin",
    "tar": "tar",
    "tarragon": "tarragon",
    "tart": "tart",
    "tart green apple": "tart green apple",
    "tartness": "tartness",
    "taste": "taste",
    "taste like": "taste like",
    "tastes": "tastes",
    "tasting": "tasting",
    "tasty": "tasty",
    "taut": "taut",
    "tea": "tea",
    "team": "team",
    "tease": "tease",
    "tempting": "tempting",
    "tense": "tense",
    "tension": "tension",
    "term": "term",
    "textural": "textural",
    "textured": "textured",
    "thank": "thank",
    "thick": "thick",
    "thin": "thin",
    "thing": "thing",
    "third": "third",
    "though": "though",
    "thread": "thread",
    "three": "three",
    "throughout": "throughout",
    "thyme": "thyme",
    "tight": "tight",
    "tight mineral": "tight mineral",
    "tight nervy": "tight nervy",
    "tightens": "tightens",
    "tightly": "tightly",
    "tightly textured": "tightly textured",
    "tightly wound": "tightly wound",
    "tightly woven": "tightly woven",
    "tightness": "tightness",
    "time": "time",
    "tingling": "tingling",
    "tingly": "tingly",
    "tiny": "tiny",
    "tire rubber": "tire rubber",
    "toast": "toast",
    "toasted": "toasted",
    "toasted almond": "toasted almond",
    "toasted bread": "toasted bread",
    "toasted brioche": "toasted brioche",
    "toasted coconut": "toasted coconut",
    "toasted hazelnut": "toasted hazelnut",
    "toasted marshmallow": "toasted marshmallow",
    "toasted nut": "toasted nut",
    "toasted oak": "toasted oak",
    "toastiness": "toastiness",
    "toasty": "toasty",
    "toasty oak": "toasty oak",
    "tobacco": "tobacco",
    "toffee": "toffee",
    "together": "together",
    "tomato": "tomato",
    "tone": "tone",
    "tongue": "tongue",
    "top": "top",
    "totally": "totally",
    "touched": "touched",
    "touches": "touches",
    "touches wood": "touches wood",
    "toward": "toward",
    "toward finish": "toward finish",
    "towards": "towards",
    "town": "town",
    "tree bark": "tree bark",
    "tree fruit": "tree fruit",
    "tremendous": "tremendous",
    "tropical": "tropical",
    "tropical fruit": "tropical fruit",
    "tropical mango": "tropical mango",
    "tropicality": "tropicality",
    "true": "true",
    "truffle": "truffle",
    "tuberose": "tuberose",
    "turn": "turn",
    "turns": "turns",
    "twist": "twist",
    "two": "two",
    "typical": "typical",
    "ultimately": "ultimately",
    "umami": "umami",
    "unctuous": "unctuous",
    "undeniable": "undeniable",
    "undergrowth": "undergrowth",
    "underlying": "underlying",
    "underneath": "underneath",
    "underripe": "underripe",
    "understated": "understated",
    "undertone": "undertone",
    "unfold": "unfold",
    "unique": "unique",
    "unoaked": "unoaked",
    "unoaked chardonnay": "unoaked chardonnay",
    "unripe": "unripe",
    "unusual": "unusual",
    "unusually": "unusually",
    "upfront": "upfront",
    "upon": "upon",
    "use oak": "use oak",
    "used": "used",
    "valley": "valley",
    "value": "value",
    "vanilla": "vanilla",
    "vanilla bean": "vanilla bean",
    "vanilla coconut": "vanilla coconut",
    "vanilla cream": "vanilla cream",
    "vanilla custard": "vanilla custard",
    "vanilla dill": "vanilla dill",
    "vanilla wafer": "vanilla wafer",
    "varietal": "varietal",
    "variety": "variety",
    "veer": "veer",
    "vegetal": "vegetal",
    "vein": "vein",
    "velvety": "velvety",
    "velvety tannin": "velvety tannin",
    "versatile": "versatile",
    "verve": "verve",
    "veteran": "veteran",
    "vibrancy": "vibrancy",
    "vibrant": "vibrant",
    "vibrantly": "vibrantly",
    "village": "village",
    "vine": "vine",
    "vine planted": "vine planted",
    "vinegar": "vinegar",
    "vineyard": "vineyard",
    "vineyard planted": "vineyard planted",
    "vineyard site": "vineyard site",
    "vintage": "vintage",
    "vintages": "vintages",
    "viognier": "viognier",
    "violet": "violet",
    "violet rose": "violet rose",
    "viscosity": "viscosity",
    "viscous": "viscous",
    "vivacious": "vivacious",
    "vivid": "vivid",
    "voluptuous": "voluptuous",
    "voluptuously": "voluptuously",
    "voluptuousness": "voluptuousness",
    "waft": "waft",
    "wait": "wait",
    "walnut": "walnut",
    "warm": "warm",
    "warm vintage": "warm vintage",
    "warmth": "warmth",
    "water": "water",
    "watermelon": "watermelon",
    "watery": "watery",
    "wave": "wave",
    "wax": "wax",
    "waxy": "waxy",
    "way": "way",
    "wealth": "wealth",
    "weed": "weed",
    "weight": "weight",
    "weighty": "weighty",
    "welcome": "welcome",
    "well integrated": "well integrated",
    "wente": "wente",
    "wet": "wet",
    "wet clay": "wet clay",
    "wet earth": "wet earth",
    "wet rock": "wet rock",
    "wet slate": "wet slate",
    "wet stone": "wet stone",
    "whiff": "whiff",
    "whiffs": "whiffs",
    "white": "white",
    "white almond": "white almond",
    "white blossom": "white blossom",
    "white currant": "white currant",
    "white flower": "white flower",
    "white fruit": "white fruit",
    "white peach": "white peach",
    "white pepper": "white pepper",
    "white stone fruit": "white stone fruit",
    "white wine": "white wine",
    "whole": "whole",
    "wide": "wide",
    "wild": "wild",
    "wild berry": "wild berry",
    "wild flower": "wild flower",
    "wildflower": "wildflower",
    "wine": "wine",
    "winemaker": "winemaker",
    "winemaking": "winemaking",
    "winery": "winery",
    "within": "within",
    "without": "without",
    "wonderful": "wonderful",
    "wonderfully": "wonderfully",
    "wood": "wood",
    "wood age": "wood age",
    "wood aging": "wood aging",
    "wood resin": "wood resin",
    "wood spice": "wood spice",
    "woodspice": "woodspice",
    "woody": "woody",
    "woody berry": "woody berry",
    "work": "work",
    "works": "works",
    "worth": "worth",
    "would": "would",
    "wound": "wound",
    "wrapped": "wrapped",
    "year": "year",
    "yeast": "yeast",
    "yeastiness": "yeastiness",
    "yeasty": "yeasty",
    "yellow": "yellow",
    "yellow apple": "yellow apple",
    "yellow color": "yellow color",
    "yellow flower": "yellow flower",
    "yellow fruit": "yellow fruit",
    "yet": "yet",
    "yogurt": "yogurt",
    "young": "young",
    "youth": "youth",
    "youthful": "youthful",
    "zest": "zest",
    "zesty": "zesty",
    "zing": "zing",
    "zingy": "zingy",
    "zip": "zip",
    "zippy": "zippy",
}
